"""cocotb integration testbench for aes_128_core — golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  For AES-128: drive start=1, wait 1 posedge (sampled), deassert start.
  DUT now at golden[1] state (ROUND_0). Compare golden[1:] against DUT,
  advancing 1 posedge per golden cycle. Data held throughout comparison.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles

CLK_PERIOD_NS = 10.0    # 100 MHz — FULL period (1000/100 = 10 ns)
RESET_CYCLE_SKIP = 1    # Golden cycle 0 is the reset state; comparison starts at cycle 1
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0           # Accumulates across ALL tests; do NOT reset inside individual tests

# ─── Golden model import ────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        from golden_model import TEST_VECTORS
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# ─── Port configuration ─────────────────────────────────────────────────
INPUT_PORTS = {
    "start": 1,
    "data_in": 128,
    "key_in": 128,
}
OUTPUT_PORTS = {
    "data_out": 128,
    "valid": 1,
}
VALID_OUTPUT_PORTS = ["valid"]
HANDSHAKE_PORTS = {}       # AES has no input ready/valid handshake — start is a pulse
HOLD_UNTIL_ACK_PORTS = []

# DRIVE_PHASE_CYCLES: golden_to_rtl_offset_cycles = 11 (pipeline depth).
# Used only as the data hold requirement: data_in/key_in must remain stable
# for 12 cycles (1 sampling + 11 hold) after start assertion.
# The comparison loop starts immediately after start is sampled (DUT = golden[1]).
DRIVE_PHASE_CYCLES = 11

# ─── Divergence collection ──────────────────────────────────────────────
MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _record_divergence(divergences, sig_name, expected_val, actual_val,
                       cycle_idx, width, kind=None):
    """Append a divergence dict to `divergences`.

    Returns True when the caller should stop collecting (cap reached or
    fail-fast mode).
    """
    div = {
        "cycle": cycle_idx,
        "signal": sig_name,
        "expected": expected_val,
        "actual": actual_val,
        "width": width,
    }
    if kind:
        div["kind"] = kind
    divergences.append(div)
    return FAIL_FAST or len(divergences) >= MAX_COLLECTED_DIVERGENCES


def _format_divergence_block(div, tag):
    """Format one divergence as a [tag] FIRST DIVERGENCE-shaped block."""
    width = div.get("width") or 32
    hex_digits = max((width + 3) // 4, 1)
    kind = div.get("kind")
    kind_tag = f" kind={kind}" if kind else ""
    hint = (
        "\n  (testbench driver wrong — DUT input doesn't match golden stimulus)"
        if kind == "stimulus_mismatch" else ""
    )
    return (
        f"[{tag}] FIRST DIVERGENCE at cycle={div['cycle']} "
        f"signal={div['signal']} (width={width}b){kind_tag}:\n"
        f"  expected = 0x{div['expected']:0{hex_digits}x}\n"
        f"  actual   = 0x{div['actual']:0{hex_digits}x}\n"
        f"  xor diff = 0x{div['expected'] ^ div['actual']:0{hex_digits}x}"
        f"{hint}"
    )


def _finalize_divergences(dut, divergences, tag):
    """Emit each divergence and raise AssertionError with a summary."""
    blocks = [_format_divergence_block(d, tag) for d in divergences]
    for b in blocks:
        dut._log.error(b)
    head = blocks[0]
    if len(blocks) > 1:
        more = "\n\n".join(blocks[1:])
        msg = (
            f"{head}\n\n"
            f"(+{len(blocks) - 1} additional divergence(s) collected; "
            f"set COCOTB_FAIL_FAST=1 to stop at the first):\n\n{more}"
        )
    else:
        msg = head
    raise AssertionError(msg)


# ─── Clock management ───────────────────────────────────────────────────
async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Reset (async active-low rst_n) ─────────────────────────────────────
async def reset_dut(dut):
    """Apply async active-low reset and wait for outputs to settle."""
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = False
    dut.rst_n.value = 0          # Assert reset (active low)
    # Zero all input ports
    for name in INPUT_PORTS:
        sig = getattr(dut, name, None)
        if sig is not None:
            sig.value = 0
    await ClockCycles(dut.clk, 3)
    dut.rst_n.value = 1          # Deassert reset
    await RisingEdge(dut.clk)    # rst deassert sampled, outputs stable


# ─── AES-specific drive ─────────────────────────────────────────────────
# AES has a simple start pulse (no ready/valid handshake on inputs).
# Data must be held for at least DRIVE_PHASE_CYCLES+1 = 12 cycles after
# start assertion (the comparison loop provides the hold duration).

_STIMULUS_DELIVERED = False


async def drive_aes_start(dut, data_val, key_val):
    """Drive AES start pulse with plaintext and key.

    After return, DUT is at golden[1] state (ROUND_0, state_reg=plaintext).
    Caller is responsible for holding data_in/key_in and clearing them after
    the comparison loop completes.
    """
    global _STIMULUS_DELIVERED
    # Drive all inputs simultaneously (NBA for DUT inputs)
    dut.data_in.value = data_val
    dut.key_in.value = key_val
    dut.start.value = 1

    # Wait one posedge — DUT samples start=1, data_in, key_in
    await RisingEdge(dut.clk)

    # Deassert start (single-cycle pulse)
    dut.start.value = 0

    _STIMULUS_DELIVERED = True
    # data_in and key_in remain held — caller must clear after comparison


def _lookup_signal_width(sig_name: str, default: int = 32) -> int:
    """Best-effort width lookup from spec-populated port dicts."""
    seen: set[str] = {sig_name}
    candidates: list[str] = [sig_name]
    cursor = 0
    while cursor < len(candidates):
        n = candidates[cursor]
        cursor += 1
        for stripped in (
            n.rsplit(".", 1)[-1] if "." in n else "",
            n[:-4] if n.endswith("_reg") else "",
            n.split("[", 1)[0] if "[" in n else "",
        ):
            if stripped and stripped not in seen:
                seen.add(stripped)
                candidates.append(stripped)
    for name in candidates:
        if name in OUTPUT_PORTS:
            return OUTPUT_PORTS[name]
    for name in candidates:
        if name in INPUT_PORTS:
            return INPUT_PORTS[name]
    return default


def _align_trace(expected_cycles):
    """Slice the golden trace to skip the reset state (cycle 0)."""
    return expected_cycles[RESET_CYCLE_SKIP:]


def _validate_trace_signal_names(expected_cycles, dut, test_name):
    """Pre-check that golden trace signal names exist in DUT hierarchy."""
    if not expected_cycles:
        return [], []
    all_trace_keys = set()
    for entry in expected_cycles:
        if isinstance(entry, dict):
            all_trace_keys.update(entry.keys())
    found = []
    missing = []
    for sig_name in sorted(all_trace_keys):
        if sig_name == "fsm_state_name":
            continue  # String identifier, not a hardware signal
        try:
            if '.' in sig_name:
                parts = sig_name.split('.')
                obj = dut
                for part in parts:
                    while '[' in part:
                        arr_name, rest = part.split('[', 1)
                        if arr_name:
                            obj = getattr(obj, arr_name)
                        idx_str, part = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                    if part:
                        obj = getattr(obj, part)
            elif '[' in sig_name:
                base, rest = sig_name.split('[', 1)
                obj = getattr(dut, base)
                idx_str, _ = rest.split(']', 1)
                obj = obj[int(idx_str)]
            else:
                getattr(dut, sig_name)
            found.append(sig_name)
        except (AttributeError, IndexError):
            missing.append(sig_name)
    if missing:
        dut._log.warning(
            f"[{test_name}] {len(missing)} golden trace signal(s) not found in DUT: "
            f"{missing[:10]}"
        )
    return found, missing


# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")
    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_internal_signals(dut):
    """Test 2: Per-cycle internal signal comparison against golden model.

    This is the KEY verification test. Drives all 3 test vectors and compares
    internal registers (state_reg, round_reg, valid_reg, data_out_reg) against
    the golden model trace on EVERY clock cycle via VPI.

    Timing:
      - drive_aes_start() samples start, DUT now at golden[1] (ROUND_0)
      - Compare golden[1:] against DUT, advancing 1 posedge per golden cycle
      - data_in/key_in held throughout; cleared after comparison
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)

    all_passed = True
    total_cycles_checked = 0
    total_signals_compared = 0

    for vec_idx, tv in enumerate(TEST_VECTORS):
        await reset_dut(dut)

        tv_name = tv["name"]
        dut._log.info(f"[INTERNAL] Vector {vec_idx}: {tv_name}")

        # Drive AES start
        await drive_aes_start(dut, tv["inputs"]["data_in"], tv["inputs"]["key_in"])

        # Get golden trace for this vector
        golden = golden_run(vec_idx)
        if not golden:
            dut._log.info(f"[SKIP] test_internal_signals: golden_run({vec_idx}) returned no data")
            dut.data_in.value = 0
            dut.key_in.value = 0
            continue

        dut._log.info(f"[INTERNAL] Vector {vec_idx}: comparing {len(golden)} golden cycles (skip reset)")

        # Pre-validate signal names
        _validate_trace_signal_names(golden, dut, "test_internal_signals")

        # Alignment: skip golden cycle 0 (reset state)
        compare_cycles = _align_trace(golden)

        divergences: list[dict] = []
        signals_not_found = []

        for cycle_idx, expected in enumerate(compare_cycles):
            stop_outer = False
            for sig_name, expected_val in expected.items():
                # Skip string identifiers
                if sig_name == "fsm_state_name":
                    continue

                # Skip input ports (not internal signals)
                if sig_name in INPUT_PORTS:
                    continue

                try:
                    # Navigate VPI hierarchy for module-qualified names
                    if '.' in sig_name:
                        parts = sig_name.split('.')
                        obj = dut
                        for part in parts:
                            while '[' in part:
                                arr_name, rest = part.split('[', 1)
                                if arr_name:
                                    obj = getattr(obj, arr_name)
                                idx_str, part = rest.split(']', 1)
                                obj = obj[int(idx_str)]
                            if part:
                                obj = getattr(obj, part)
                        actual_val = int(obj.value)
                    else:
                        sig = getattr(dut, sig_name)
                        actual_val = int(sig.value)

                    total_signals_compared += 1
                    if actual_val != expected_val:
                        # Try to get signal width for proper hex formatting
                        try:
                            sig_width = len(obj if '.' in sig_name else sig)
                        except Exception:
                            sig_width = _lookup_signal_width(sig_name)
                        if _record_divergence(
                            divergences, sig_name, expected_val, actual_val,
                            cycle_idx, sig_width,
                        ):
                            stop_outer = True
                            break
                except (AttributeError, IndexError):
                    if sig_name not in signals_not_found:
                        signals_not_found.append(sig_name)

            total_cycles_checked += 1
            if stop_outer:
                break

            # Advance DUT one cycle for the NEXT golden entry
            await RisingEdge(dut.clk)

        # Clear held data inputs
        dut.data_in.value = 0
        dut.key_in.value = 0

        # Warn about signals that could not be found
        if signals_not_found:
            dut._log.warning(
                f"[INTERNAL] vec={vec_idx}: {len(signals_not_found)} signal(s) not found, "
                f"skipped: {signals_not_found[:5]}"
            )

        if divergences:
            FAIL_COUNT += len(divergences)
            all_passed = False
            dut._log.error(
                f"[INTERNAL] Vector {vec_idx} ({tv_name}): "
                f"{len(divergences)} divergence(s) found"
            )
            # Report first divergence but continue to next vector
            for d in divergences[:1]:
                dut._log.error(_format_divergence_block(d, "INTERNAL"))
        else:
            dut._log.info(
                f"[INTERNAL] Vector {vec_idx} ({tv_name}): PASS — "
                f"{total_signals_compared} signal values matched across {total_cycles_checked} cycles"
            )

    # Stimulus sanity check
    if not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_internal_signals: drive_aes_start() was never called (no stimulus delivered)"
        )

    if total_signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared — golden trace signal names "
            "do not match any DUT signals. Check naming convention (_reg suffix)."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if all_passed:
        dut._log.info(
            f"[INTERNAL] ALL 3 VECTORS PASSED — "
            f"{total_signals_compared} signal values matched across all cycles"
        )


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification — output port comparison against golden model.

    Compares top-level output ports (valid, data_out) against golden model
    registered output values (valid_reg, data_out_reg) per cycle.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)

    # Map golden trace signal names to DUT top-level port names
    GOLDEN_TO_PORT = {
        "valid_reg": "valid",
        "data_out_reg": "data_out",
    }

    all_passed = True
    total_cycles_checked = 0
    total_signals_compared = 0

    for vec_idx, tv in enumerate(TEST_VECTORS):
        await reset_dut(dut)

        tv_name = tv["name"]
        dut._log.info(f"[LAYERED] Vector {vec_idx}: {tv_name}")

        await drive_aes_start(dut, tv["inputs"]["data_in"], tv["inputs"]["key_in"])

        golden = golden_run(vec_idx)
        compare_cycles = _align_trace(golden)

        divergences: list[dict] = []
        signals_not_found = []

        for cycle_idx, expected in enumerate(compare_cycles):
            stop_outer = False
            for sig_name, expected_val in expected.items():
                dut_name = GOLDEN_TO_PORT.get(sig_name)
                if dut_name is None:
                    continue
                try:
                    sig = getattr(dut, dut_name)
                    actual_val = int(sig.value)
                    total_signals_compared += 1
                    if actual_val != expected_val:
                        if _record_divergence(
                            divergences, sig_name, expected_val, actual_val,
                            cycle_idx, len(sig),
                        ):
                            stop_outer = True
                            break
                except AttributeError:
                    if dut_name not in signals_not_found:
                        signals_not_found.append(dut_name)

            total_cycles_checked += 1
            if stop_outer:
                break

            await RisingEdge(dut.clk)

        # Clear held data inputs
        dut.data_in.value = 0
        dut.key_in.value = 0

        if signals_not_found:
            dut._log.warning(
                f"[LAYERED] vec={vec_idx}: {len(signals_not_found)} port(s) not found, "
                f"skipped: {signals_not_found[:5]}"
            )

        if divergences:
            FAIL_COUNT += len(divergences)
            all_passed = False
            dut._log.error(
                f"[LAYERED] Vector {vec_idx} ({tv_name}): "
                f"{len(divergences)} divergence(s) found"
            )
            _finalize_divergences(dut, divergences, "LAYERED")
        else:
            dut._log.info(
                f"[LAYERED] Vector {vec_idx} ({tv_name}): PASS"
            )

    if total_signals_compared == 0:
        raise AssertionError(
            "test_layered: ZERO signals were compared — GOLDEN_TO_PORT keys "
            "do not match any golden trace signal names"
        )

    if all_passed:
        dut._log.info(
            f"[LAYERED] ALL 3 VECTORS PASSED — "
            f"{total_signals_compared} signal values matched across {total_cycles_checked} cycles"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    MUST be the last test defined in this file — cocotb runs tests in
    definition order.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
