"""cocotb integration testbench for resnet_basic_block — golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (ready, valid_out, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 5.0   # 200 MHz -> 5 ns full period
RESET_CYCLE_SKIP = 1  # Golden cycle 0 is the reset state; comparison starts at cycle 1
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0  # Accumulates across ALL tests; do NOT reset inside individual tests
_STIMULUS_DELIVERED = False  # Set True by drive_inputs(); checked by comparison tests

# ─── Golden model import ────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run, INPUT_4X4
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# ─── Port configuration ─────────────────────────────────────────────────
INPUT_PORTS = {"in_valid_i": 1, "in_data_i": 8}
OUTPUT_PORTS = {"out_valid_o": 1, "out_data_o": 8}
VALID_OUTPUT_PORTS = ["out_valid_o"]
HANDSHAKE_PORTS = {}
HOLD_UNTIL_ACK_PORTS = []

DRIVE_PHASE_CYCLES = 7  # from spec.json timing_convention.golden_to_rtl_offset_cycles

# Verilog parameter overrides — passed to iverilog as -P flags
# Test vectors use 4x4 feature map, so override default 16x16
VERILOG_PARAMS = {
    "WIDTH": 4,
    "HEIGHT": 4,
    "CHANNELS": 1,
}

# ─── Divergence collection ──────────────────────────────────────────────
MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _record_divergence(divergences, sig_name, expected_val, actual_val,
                       cycle_idx, width, kind=None):
    div = {
        "cycle": cycle_idx,
        "signal": sig_name,
        "expected": expected_val,
        "actual": actual_val,
        "width": width,
    }
    if kind:
        div["kind"] = kind
    divergences.append(div)
    return FAIL_FAST or len(divergences) >= MAX_COLLECTED_DIVERGENCES


def _format_divergence_block(div, tag):
    width = div.get("width") or 32
    hex_digits = max((width + 3) // 4, 1)
    kind = div.get("kind")
    kind_tag = f" kind={kind}" if kind else ""
    hint = (
        "\n  (testbench driver wrong — DUT input doesn't match golden stimulus)"
        if kind == "stimulus_mismatch" else ""
    )
    return (
        f"[{tag}] FIRST DIVERGENCE at cycle={div['cycle']} "
        f"signal={div['signal']} (width={width}b){kind_tag}:\n"
        f"  expected = 0x{div['expected']:0{hex_digits}x}\n"
        f"  actual   = 0x{div['actual']:0{hex_digits}x}\n"
        f"  xor diff = 0x{div['expected'] ^ div['actual']:0{hex_digits}x}"
        f"{hint}"
    )


def _finalize_divergences(dut, divergences, tag):
    blocks = [_format_divergence_block(d, tag) for d in divergences]
    for b in blocks:
        dut._log.error(b)
    head = blocks[0]
    if len(blocks) > 1:
        more = "\n\n".join(blocks[1:])
        msg = (
            f"{head}\n\n"
            f"(+{len(blocks) - 1} additional divergence(s) collected; "
            f"set COCOTB_FAIL_FAST=1 to stop at the first):\n\n{more}"
        )
    else:
        msg = head
    raise AssertionError(msg)


# ─── Clock management ───────────────────────────────────────────────────
async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Helpers ────────────────────────────────────────────────────────────

def _lookup_signal_width(sig_name: str, default: int = 32) -> int:
    seen = {sig_name}
    candidates = [sig_name]
    cursor = 0
    while cursor < len(candidates):
        n = candidates[cursor]
        cursor += 1
        for stripped in (
            n.rsplit(".", 1)[-1] if "." in n else "",
            n[:-4] if n.endswith("_reg") else "",
            n.split("[", 1)[0] if "[" in n else "",
        ):
            if stripped and stripped not in seen:
                seen.add(stripped)
                candidates.append(stripped)

    for name in candidates:
        if name in OUTPUT_PORTS:
            return OUTPUT_PORTS[name]
    for name in candidates:
        if name in INPUT_PORTS:
            return INPUT_PORTS[name]
    return default


async def reset_dut(dut):
    """Apply synchronous reset and wait for outputs to settle."""
    global FAIL_COUNT
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = False
    dut.rst.value = 1
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    for valid_name in HANDSHAKE_PORTS:
        try:
            getattr(dut, valid_name).value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst.value = 0
    await RisingEdge(dut.clk)


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


def _validate_trace_signal_names(expected_cycles, dut, test_name):
    if not expected_cycles:
        return [], []

    all_trace_keys = set()
    for entry in expected_cycles:
        if isinstance(entry, dict):
            all_trace_keys.update(entry.keys())

    found = []
    missing = []
    for sig_name in sorted(all_trace_keys):
        try:
            if '.' in sig_name:
                parts = sig_name.split('.')
                obj = dut
                for part in parts:
                    while '[' in part:
                        arr_name, rest = part.split('[', 1)
                        if arr_name:
                            obj = getattr(obj, arr_name)
                        idx_str, part = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                    if part:
                        obj = getattr(obj, part)
            elif '[' in sig_name:
                base, rest = sig_name.split('[', 1)
                obj = getattr(dut, base)
                idx_str, _ = rest.split(']', 1)
                obj = obj[int(idx_str)]
            else:
                getattr(dut, sig_name)
            found.append(sig_name)
        except (AttributeError, IndexError):
            missing.append(sig_name)

    if missing:
        dut._log.warning(
            f"[{test_name}] {len(missing)} golden trace signal(s) not found in DUT: "
            f"{missing[:10]}"
        )
    return found, missing


def _align_trace(expected_cycles):
    return expected_cycles[RESET_CYCLE_SKIP:]


async def drive_inputs(dut, input_values, valid_name='in_valid_i',
                       ready_name=None,
                       hold_data_cycles=None):
    """Drive valid=1 with input values, then hold data for hold_data_cycles."""
    if hold_data_cycles is None:
        hold_data_cycles = DRIVE_PHASE_CYCLES

    for port_name, value in input_values.items():
        getattr(dut, port_name).value = value
    getattr(dut, valid_name).value = 1

    await RisingEdge(dut.clk)

    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = True

    getattr(dut, valid_name).value = 0
    for _ in range(hold_data_cycles):
        await RisingEdge(dut.clk)
    for port_name in input_values:
        if port_name != valid_name:
            getattr(dut, port_name).value = 0


async def wait_valid(dut, valid_name='out_valid_o', max_cycles=200):
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1


# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance — reset clears outputs."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification — collect all DUT outputs and compare
    against golden model final expected values.

    For streaming conv designs, the golden model uses instantaneous software
    semantics and does NOT model line-buffer fill latency.  Per-cycle
    comparison therefore fails on startup cycles.  Instead we:
      1. Stream all inputs
      2. Collect every out_data where out_valid==1
      3. Compare the collected list against golden_model's expected output list.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Build input stream
    input_stream = []
    for row in INPUT_4X4:
        for val in row:
            input_stream.append(val)

    # Stream inputs: one pixel per cycle
    for pixel in input_stream:
        dut.in_valid_i.value = 1
        dut.in_data_i.value = pixel
        await RisingEdge(dut.clk)
    dut.in_valid_i.value = 0
    dut.in_data_i.value = 0

    # Collect DUT outputs while out_valid is high
    # For a 4x4 input with padding=1, output is 6x6 = 36 pixels.
    # Wait up to 200 cycles for all outputs.
    dut_outputs = []
    for _ in range(200):
        await RisingEdge(dut.clk)
        if int(dut.out_valid_o.value) == 1:
            dut_outputs.append(int(dut.out_data_o.value))
        # Stop once we have 36 outputs (6x6) and valid drops
        if len(dut_outputs) >= 36 and int(dut.out_valid_o.value) == 0:
            break

    # Compute golden expected outputs
    from golden_model import resnet_basic_block
    golden_map = resnet_basic_block(INPUT_4X4)
    golden_outputs = []
    for row in golden_map:
        for val in row:
            golden_outputs.append(val)

    dut._log.info(
        f"[LAYERED] DUT outputs: {len(dut_outputs)} pixels, "
        f"golden expects: {len(golden_outputs)} pixels"
    )

    mismatches = 0
    for i, (exp, act) in enumerate(zip(golden_outputs, dut_outputs)):
        if exp != act:
            mismatches += 1
            if mismatches <= 5:
                dut._log.error(
                    f"[LAYERED] mismatch pixel {i}: expected={exp} actual={act}"
                )

    if len(dut_outputs) != len(golden_outputs):
        dut._log.error(
            f"[LAYERED] output count mismatch: expected {len(golden_outputs)}, "
            f"got {len(dut_outputs)}"
        )
        mismatches += abs(len(dut_outputs) - len(golden_outputs))

    if mismatches:
        FAIL_COUNT += mismatches
        raise AssertionError(
            f"[LAYERED] FAILED: {mismatches} mismatches out of {len(golden_outputs)} pixels"
        )
    else:
        dut._log.info(
            f"[LAYERED] PASS — all {len(golden_outputs)} output pixels match golden model"
        )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model."""
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    has_internal = any('.' in k or k.endswith('_reg')
                       for entry in expected_cycles for k in entry.keys())
    if not has_internal:
        dut._log.info("[SKIP] test_internal_signals: golden trace has no internal signals")
        return

    dut._log.info(f"[INTERNAL] Comparing {len(expected_cycles)} cycles, internal signals")

    _validate_trace_signal_names(expected_cycles, dut, "test_internal_signals")

    # Drive 16 input pixels one per cycle
    input_stream = []
    for row in INPUT_4X4:
        for val in row:
            input_stream.append(val)

    # Stream input: one pixel per cycle, continuous
    for pixel in input_stream:
        dut.in_valid_i.value = 1
        dut.in_data_i.value = pixel
        await RisingEdge(dut.clk)
    dut.in_valid_i.value = 0
    dut.in_data_i.value = 0
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = True

    divergences = []
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    compare_cycles = _align_trace(expected_cycles)

    for cycle_idx, expected in enumerate(compare_cycles):
        stop_outer = False
        for sig_name, expected_val in expected.items():
            if sig_name in INPUT_PORTS:
                try:
                    actual_val = int(getattr(dut, sig_name).value)
                    signals_compared += 1
                    if actual_val != expected_val:
                        if _record_divergence(
                            divergences, sig_name, expected_val, actual_val,
                            cycle_idx, _lookup_signal_width(sig_name),
                            kind="stimulus_mismatch",
                        ):
                            stop_outer = True
                            break
                except (AttributeError, ValueError):
                    pass
                continue

            try:
                if '.' in sig_name:
                    parts = sig_name.split('.')
                    obj = dut
                    for part in parts:
                        while '[' in part:
                            arr_name, rest = part.split('[', 1)
                            if arr_name:
                                obj = getattr(obj, arr_name)
                            idx_str, part = rest.split(']', 1)
                            idx = int(idx_str)
                            obj = obj[idx]
                        if part:
                            obj = getattr(obj, part)
                    actual_val = int(obj.value)
                else:
                    if '[' in sig_name:
                        base, rest = sig_name.split('[', 1)
                        obj = getattr(dut, base)
                        idx_str, _ = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                        actual_val = int(obj.value)
                    else:
                        sig = getattr(dut, sig_name)
                        actual_val = int(sig.value)

                signals_compared += 1
                if actual_val != expected_val:
                    try:
                        sig_width = len(obj if '.' in sig_name else sig)
                    except Exception:
                        sig_width = _lookup_signal_width(sig_name)
                    if _record_divergence(
                        divergences, sig_name, expected_val, actual_val,
                        cycle_idx, sig_width,
                    ):
                        stop_outer = True
                        break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        cycles_checked += 1
        if stop_outer:
            break

        await RisingEdge(dut.clk)

    if INPUT_PORTS and not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_internal_signals: drive_inputs() was never called (no stimulus delivered)"
        )

    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (f" ... and {len(signals_not_found)-5} more" if len(signals_not_found) > 5 else "")
        )

    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared — golden trace signal names "
            "do not match any DUT signals. Check naming convention."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if divergences:
        FAIL_COUNT += len(divergences)
        _finalize_divergences(dut, divergences, "INTERNAL")
    else:
        dut._log.info(
            f"[INTERNAL] PASS — {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    MUST be the last test defined in this file — cocotb runs tests in
    definition order. This test reads the accumulated FAIL_COUNT.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
