"""cocotb integration testbench for axi4_lite_async_bridge -- golden model cross-check.
Generated by VeriFlow-CC.

This is a multi-clock-domain AXI4-Lite async bridge. The golden model is
transaction-level (not per-cycle) so the standard drive_inputs/compare cycle
loop from the template does NOT apply. Instead, this testbench implements:

  1. AXI4-Lite Master BFM  (drives the slave-side s_axi_* interface)
  2. AXI4-Lite Slave BFM   (responds on the master-side m_axi_* interface)
  3. Per-transaction comparison against golden_model.compute() outputs

Both clock domains (s_axi_aclk, m_axi_aclk) are driven at DIFFERENT
frequencies to stress the asynchronous crossing.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clocks() to start fresh clock instances.
"""

import os
import sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, Timer, ReadOnly, Combine
import asyncio

# ---------------------------------------------------------------------------
# Constants from spec.json
# ---------------------------------------------------------------------------

# Clock periods: slave domain 100 MHz (10 ns), master domain ~77 MHz (13 ns)
# Different frequencies stress the async crossing.
S_CLK_PERIOD_NS = 10   # 100 MHz
M_CLK_PERIOD_NS = 13   # ~77 MHz

TIMEOUT_CYCLES = 500
FAIL_COUNT = 0  # Accumulates across ALL tests

# ---------------------------------------------------------------------------
# Port configuration from spec.json
# ---------------------------------------------------------------------------

INPUT_PORTS = {
    "s_axi_aclk":      1,
    "s_axi_aresetn":   1,
    "m_axi_aclk":      1,
    "m_axi_aresetn":   1,
    "s_axi_awvalid":   1,
    "s_axi_awaddr":    32,
    "s_axi_awprot":    3,
    "s_axi_wvalid":    1,
    "s_axi_wdata":     32,
    "s_axi_wstrb":     4,
    "s_axi_bready":    1,
    "s_axi_arvalid":   1,
    "s_axi_araddr":    32,
    "s_axi_arprot":    3,
    "s_axi_rready":    1,
    "m_axi_awready":   1,
    "m_axi_wready":    1,
    "m_axi_bvalid":    1,
    "m_axi_bresp":     2,
    "m_axi_arready":   1,
    "m_axi_rvalid":    1,
    "m_axi_rdata":     32,
    "m_axi_rresp":     2,
}

OUTPUT_PORTS = {
    "s_axi_awready":   1,
    "s_axi_wready":    1,
    "s_axi_bvalid":    1,
    "s_axi_bresp":     2,
    "s_axi_arready":   1,
    "s_axi_rvalid":    1,
    "s_axi_rdata":     32,
    "s_axi_rresp":     2,
    "m_axi_awvalid":   1,
    "m_axi_awaddr":    32,
    "m_axi_awprot":    3,
    "m_axi_wvalid":    1,
    "m_axi_wdata":     32,
    "m_axi_wstrb":     4,
    "m_axi_bready":    1,
    "m_axi_arvalid":   1,
    "m_axi_araddr":    32,
    "m_axi_arprot":    3,
    "m_axi_rready":    1,
}

VALID_OUTPUT_PORTS = [
    "s_axi_bvalid", "s_axi_rvalid",
    "m_axi_awvalid", "m_axi_wvalid", "m_axi_arvalid",
]

HANDSHAKE_PORTS = {
    "s_axi_awvalid": "s_axi_awready",
    "s_axi_wvalid":  "s_axi_wready",
    "s_axi_bvalid":  "s_axi_bready",   # output valid -> input ready
    "s_axi_arvalid": "s_axi_arready",
    "s_axi_rvalid":  "s_axi_rready",   # output valid -> input ready
    "m_axi_awvalid": "m_axi_awready",
    "m_axi_wvalid":  "m_axi_wready",
    "m_axi_bvalid":  "m_axi_bready",
    "m_axi_arvalid": "m_axi_arready",
    "m_axi_rvalid":  "m_axi_rready",
}

HOLD_UNTIL_ACK_PORTS = [
    "s_axi_awvalid", "s_axi_wvalid", "s_axi_bready",
    "s_axi_arvalid", "s_axi_rready",
    "m_axi_awready", "m_axi_wready", "m_axi_arready",
]

DRIVE_PHASE_CYCLES = 2  # from spec.json timing_convention.golden_to_rtl_offset_cycles
CLK_PERIOD_NS = S_CLK_PERIOD_NS  # primary clock for template compatibility
DIGEST_OUTPUT_PORT = None  # not a digest/hash design -- no multi-block chaining

# ---------------------------------------------------------------------------
# Golden model import
# ---------------------------------------------------------------------------

GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import compute, get_test_vectors, TEST_VECTORS
        from golden_model import RESP_OKAY, RESP_SLVERR
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Tests will be skipped.")

# ---------------------------------------------------------------------------
# Divergence helpers (RULE 4 compliant error messages)
# ---------------------------------------------------------------------------

MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _format_txn_mismatch(test_name, txn_idx, field, expected, actual, width=32):
    """Format a transaction-level mismatch with full hex and diagnostic data."""
    hex_digits = max((width + 3) // 4, 1)
    return (
        f"[FAIL] test={test_name} txn={txn_idx} signal={field} "
        f"(width={width}b):\n"
        f"  expected = 0x{expected:0{hex_digits}x}\n"
        f"  actual   = 0x{actual:0{hex_digits}x}\n"
        f"  xor diff = 0x{expected ^ actual:0{hex_digits}x}"
    )


# ---------------------------------------------------------------------------
# Clock management (RULE 6: first await must be ensure_clocks)
# ---------------------------------------------------------------------------

async def ensure_clocks(dut):
    """Start both async clock domains. MUST be the first await in every test.

    s_axi_aclk at 10 ns (100 MHz), m_axi_aclk at 13 ns (~77 MHz).
    Different frequencies to stress the async crossing.
    """
    s_clk = Clock(dut.s_axi_aclk, S_CLK_PERIOD_NS, unit="ns")
    m_clk = Clock(dut.m_axi_aclk, M_CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(s_clk.start())
    cocotb.start_soon(m_clk.start())
    # Wait for both clocks to produce at least one edge
    await RisingEdge(dut.s_axi_aclk)
    await RisingEdge(dut.m_axi_aclk)


async def ensure_clock(dut):
    """Template-compatible wrapper -- starts both clocks."""
    await ensure_clocks(dut)


# ---------------------------------------------------------------------------
# Reset
# ---------------------------------------------------------------------------

async def reset_dut(dut):
    """Apply active-low async reset to both domains and wait for settling."""
    global FAIL_COUNT
    dut.s_axi_aresetn.value = 0
    dut.m_axi_aresetn.value = 0
    # Zero all slave-side master inputs
    dut.s_axi_awvalid.value = 0
    dut.s_axi_awaddr.value = 0
    dut.s_axi_awprot.value = 0
    dut.s_axi_wvalid.value = 0
    dut.s_axi_wdata.value = 0
    dut.s_axi_wstrb.value = 0
    dut.s_axi_bready.value = 0
    dut.s_axi_arvalid.value = 0
    dut.s_axi_araddr.value = 0
    dut.s_axi_arprot.value = 0
    dut.s_axi_rready.value = 0
    # Zero all master-side slave inputs
    dut.m_axi_awready.value = 0
    dut.m_axi_wready.value = 0
    dut.m_axi_bvalid.value = 0
    dut.m_axi_bresp.value = 0
    dut.m_axi_arready.value = 0
    dut.m_axi_rvalid.value = 0
    dut.m_axi_rdata.value = 0
    dut.m_axi_rresp.value = 0
    # Hold reset for sufficient time in both domains
    await Timer(100, units="ns")
    dut.s_axi_aresetn.value = 1
    dut.m_axi_aresetn.value = 1
    await Timer(50, units="ns")
    # Wait for a few edges in both domains to ensure clean settling
    for _ in range(3):
        await RisingEdge(dut.s_axi_aclk)
    for _ in range(3):
        await RisingEdge(dut.m_axi_aclk)


# ---------------------------------------------------------------------------
# AXI4-Lite Master BFM (drives slave-side s_axi_* ports)
# Simulates an AXI master connected to the bridge's slave interface.
# ---------------------------------------------------------------------------

async def axi_write(dut, addr, data, strb=0xF, prot=0, timeout_cycles=200):
    """Execute a single AXI4-Lite write transaction on the slave-side interface.

    Drives AW and W channels simultaneously (legal in AXI), waits for
    both handshakes, then waits for B response.

    Returns: bresp (int)
    """
    # Drive AW channel
    dut.s_axi_awaddr.value = addr
    dut.s_axi_awprot.value = prot
    dut.s_axi_awvalid.value = 1

    # Drive W channel
    dut.s_axi_wdata.value = data
    dut.s_axi_wstrb.value = strb
    dut.s_axi_wvalid.value = 1

    # Drive B ready (accept response when it comes)
    dut.s_axi_bready.value = 1

    # Wait for AW handshake
    aw_done = False
    w_done = False
    for _ in range(timeout_cycles):
        await RisingEdge(dut.s_axi_aclk)
        if not aw_done and int(dut.s_axi_awready.value) == 1:
            dut.s_axi_awvalid.value = 0
            aw_done = True
        if not w_done and int(dut.s_axi_wready.value) == 1:
            dut.s_axi_wvalid.value = 0
            w_done = False  # Keep valid until both done -- actually deassert
            w_done = True
            dut.s_axi_wvalid.value = 0
        if aw_done and w_done:
            break
    else:
        raise AssertionError(
            f"[TIMEOUT] axi_write: AW({'done' if aw_done else 'pending'}) "
            f"W({'done' if w_done else 'pending'}) after {timeout_cycles} s_clk cycles"
        )

    # Clear data after handshake
    dut.s_axi_awaddr.value = 0
    dut.s_axi_awprot.value = 0
    dut.s_axi_wdata.value = 0
    dut.s_axi_wstrb.value = 0

    # Wait for B response
    for _ in range(timeout_cycles):
        await RisingEdge(dut.s_axi_aclk)
        if int(dut.s_axi_bvalid.value) == 1:
            bresp = int(dut.s_axi_bresp.value)
            dut.s_axi_bready.value = 0
            return bresp

    raise AssertionError(
        f"[TIMEOUT] axi_write: B channel response not received after "
        f"{timeout_cycles} s_clk cycles"
    )


async def axi_read(dut, addr, prot=0, timeout_cycles=200):
    """Execute a single AXI4-Lite read transaction on the slave-side interface.

    Returns: (rdata, rresp)
    """
    # Drive AR channel
    dut.s_axi_araddr.value = addr
    dut.s_axi_arprot.value = prot
    dut.s_axi_arvalid.value = 1

    # Drive R ready
    dut.s_axi_rready.value = 1

    # Wait for AR handshake
    for _ in range(timeout_cycles):
        await RisingEdge(dut.s_axi_aclk)
        if int(dut.s_axi_arready.value) == 1:
            dut.s_axi_arvalid.value = 0
            dut.s_axi_araddr.value = 0
            dut.s_axi_arprot.value = 0
            break
    else:
        raise AssertionError(
            f"[TIMEOUT] axi_read: AR handshake not completed after "
            f"{timeout_cycles} s_clk cycles"
        )

    # Wait for R response
    for _ in range(timeout_cycles):
        await RisingEdge(dut.s_axi_aclk)
        if int(dut.s_axi_rvalid.value) == 1:
            rdata = int(dut.s_axi_rdata.value)
            rresp = int(dut.s_axi_rresp.value)
            dut.s_axi_rready.value = 0
            return rdata, rresp

    raise AssertionError(
        f"[TIMEOUT] axi_read: R channel response not received after "
        f"{timeout_cycles} s_clk cycles"
    )


# ---------------------------------------------------------------------------
# AXI4-Lite Slave BFM (responds on master-side m_axi_* ports)
# Simulates an AXI slave connected to the bridge's master interface.
# Runs as concurrent coroutines.
# ---------------------------------------------------------------------------

class AxiSlaveBFM:
    """Simple AXI4-Lite slave that responds to transactions on the
    master-side interface of the bridge.

    Usage:
        slave = AxiSlaveBFM(dut)
        slave.start()
        # ... run master-side transactions ...
        slave.stop()

    The slave always accepts writes (awready=1, wready=1) and provides
    configurable responses for B and R channels.
    """

    def __init__(self, dut):
        self.dut = dut
        self._running = False
        self._tasks = []
        # Response queues: populated by test, consumed by BFM coroutines
        self.b_responses = asyncio.Queue()   # items: {"bresp": int}
        self.r_responses = asyncio.Queue()   # items: {"rdata": int, "rresp": int}
        # Observed transactions (for debugging)
        self.observed_writes = []  # list of {"addr": int, "data": int, "strb": int}
        self.observed_reads = []   # list of {"addr": int}

    def start(self):
        """Start all slave BFM coroutines."""
        self._running = True
        self._tasks = [
            cocotb.start_soon(self._aw_channel()),
            cocotb.start_soon(self._w_channel()),
            cocotb.start_soon(self._ar_channel()),
        ]

    def stop(self):
        """Signal all coroutines to stop."""
        self._running = False

    async def _aw_channel(self):
        """Handle AW channel: accept write addresses, always ready."""
        dut = self.dut
        while self._running:
            dut.m_axi_awready.value = 1
            await RisingEdge(dut.m_axi_aclk)
            if int(dut.m_axi_awvalid.value) == 1:
                addr = int(dut.m_axi_awaddr.value)
                # Address stored for cross-reference with W channel
                self._last_aw_addr = addr

    async def _w_channel(self):
        """Handle W+B channels: accept write data, provide B response."""
        dut = self.dut
        while self._running:
            dut.m_axi_wready.value = 1
            await RisingEdge(dut.m_axi_aclk)
            if int(dut.m_axi_wvalid.value) == 1:
                data = int(dut.m_axi_wdata.value)
                strb = int(dut.m_axi_wstrb.value)
                addr = getattr(self, '_last_aw_addr', 0)
                self.observed_writes.append({"addr": addr, "data": data, "strb": strb})

                # Wait a couple of m_clk cycles to simulate slave latency,
                # then drive B response
                for _ in range(2):
                    await RisingEdge(dut.m_axi_aclk)

                # Get response from queue or default to OKAY
                try:
                    resp = self.b_responses.get_nowait()
                except asyncio.QueueEmpty:
                    resp = {"bresp": 0}  # RESP_OKAY

                dut.m_axi_bresp.value = resp["bresp"]
                dut.m_axi_bvalid.value = 1
                # Wait for bready from bridge
                for _ in range(200):
                    await RisingEdge(dut.m_axi_aclk)
                    if int(dut.m_axi_bready.value) == 1:
                        break
                dut.m_axi_bvalid.value = 0

    async def _ar_channel(self):
        """Handle AR+R channels: accept read addresses, provide R response."""
        dut = self.dut
        while self._running:
            dut.m_axi_arready.value = 1
            await RisingEdge(dut.m_axi_aclk)
            if int(dut.m_axi_arvalid.value) == 1:
                addr = int(dut.m_axi_araddr.value)
                self.observed_reads.append({"addr": addr})

                # Wait a couple of m_clk cycles for slave latency
                for _ in range(2):
                    await RisingEdge(dut.m_axi_aclk)

                # Get response from queue or default to 0/OKAY
                try:
                    resp = self.r_responses.get_nowait()
                except asyncio.QueueEmpty:
                    resp = {"rdata": 0, "rresp": 0}  # RESP_OKAY

                dut.m_axi_rdata.value = resp["rdata"]
                dut.m_axi_rresp.value = resp["rresp"]
                dut.m_axi_rvalid.value = 1
                # Wait for rready from bridge
                for _ in range(200):
                    await RisingEdge(dut.m_axi_aclk)
                    if int(dut.m_axi_rready.value) == 1:
                        break
                dut.m_axi_rvalid.value = 0


# ---------------------------------------------------------------------------
# Per-test helper: run one golden test vector and compare results
# ---------------------------------------------------------------------------

async def run_test_vector(dut, test_name, tv, slave):
    """Drive a golden model test vector through the DUT and compare results.

    Args:
        dut: cocotb DUT handle
        test_name: test vector name string
        tv: test vector dict from golden_model.TEST_VECTORS
        slave: AxiSlaveBFM instance

    Returns: number of failures (0 = pass)
    """
    global FAIL_COUNT
    failures = 0

    transactions = tv["inputs"]["transactions"]
    master_responses = list(tv["inputs"].get("master_responses", []))
    expected_results = tv["expected"]["transactions"]
    resp_idx = 0

    # Pre-load slave response queues
    for resp in master_responses:
        if "bresp" in resp:
            await slave.b_responses.put(resp)
        elif "rdata" in resp:
            await slave.r_responses.put(resp)

    results = []
    for txn in transactions:
        if txn["type"] == "write":
            addr = txn["addr"]
            data = txn.get("data", 0)
            strb = txn.get("strb", 0xF)
            prot = txn.get("prot", 0)
            bresp = await axi_write(dut, addr, data, strb, prot)
            results.append({
                "type": "write",
                "addr": addr,
                "data": data,
                "bresp": bresp,
            })
            # Small gap between transactions for FIFO crossing
            for _ in range(3):
                await RisingEdge(dut.s_axi_aclk)

        elif txn["type"] == "read":
            addr = txn["addr"]
            prot = txn.get("prot", 0)
            rdata, rresp = await axi_read(dut, addr, prot)
            results.append({
                "type": "read",
                "addr": addr,
                "rdata": rdata,
                "rresp": rresp,
            })
            # Small gap between transactions for FIFO crossing
            for _ in range(3):
                await RisingEdge(dut.s_axi_aclk)

    # Compare results
    if len(results) != len(expected_results):
        dut._log.error(
            f"[{test_name}] Transaction count mismatch: "
            f"got {len(results)}, expected {len(expected_results)}"
        )
        return len(expected_results)

    for i, (actual, expected) in enumerate(zip(results, expected_results)):
        if actual["type"] != expected["type"]:
            dut._log.error(
                _format_txn_mismatch(test_name, i, "type",
                                     expected["type"], actual["type"], 8)
            )
            failures += 1
            continue

        if actual["type"] == "write":
            if actual["bresp"] != expected["bresp"]:
                dut._log.error(
                    _format_txn_mismatch(test_name, i, "bresp",
                                         expected["bresp"], actual["bresp"], 2)
                )
                failures += 1

        elif actual["type"] == "read":
            if actual["rdata"] != expected["rdata"]:
                dut._log.error(
                    _format_txn_mismatch(test_name, i, "rdata",
                                         expected["rdata"], actual["rdata"], 32)
                )
                failures += 1
            if actual["rresp"] != expected["rresp"]:
                dut._log.error(
                    _format_txn_mismatch(test_name, i, "rresp",
                                         expected["rresp"], actual["rresp"], 2)
                )
                failures += 1

    FAIL_COUNT += failures
    return failures


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior -- outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    reset_ok = True
    # After reset, valid outputs should be 0
    for port_name in ["s_axi_awready", "s_axi_wready", "s_axi_bvalid",
                       "s_axi_arready", "s_axi_rvalid",
                       "m_axi_awvalid", "m_axi_wvalid", "m_axi_arvalid",
                       "m_axi_bready", "m_axi_rready"]:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance -- valid signals cleared after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset, all valid output ports must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_single_write(dut):
    """Test 3: Single AXI write transaction."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_single_write: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[0]  # single_write
    failures = await run_test_vector(dut, "single_write", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] single_write")
    else:
        dut._log.error(f"[FAIL] single_write: {failures} mismatch(es)")


@cocotb.test()
async def test_single_read(dut):
    """Test 4: Single AXI read transaction."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_single_read: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[1]  # single_read
    failures = await run_test_vector(dut, "single_read", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] single_read")
    else:
        dut._log.error(f"[FAIL] single_read: {failures} mismatch(es)")


@cocotb.test()
async def test_back_to_back_writes(dut):
    """Test 5: Back-to-back write transactions (FIFO stress)."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_back_to_back_writes: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[2]  # back_to_back_writes
    failures = await run_test_vector(dut, "back_to_back_writes", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] back_to_back_writes")
    else:
        dut._log.error(f"[FAIL] back_to_back_writes: {failures} mismatch(es)")


@cocotb.test()
async def test_write_read_interleaved(dut):
    """Test 6: Interleaved write and read transactions."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_write_read_interleaved: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[3]  # write_read_interleaved
    failures = await run_test_vector(dut, "write_read_interleaved", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] write_read_interleaved")
    else:
        dut._log.error(f"[FAIL] write_read_interleaved: {failures} mismatch(es)")


@cocotb.test()
async def test_fifo_full_backpressure(dut):
    """Test 7: FIFO full backpressure (4 writes to fill FIFO depth)."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_fifo_full_backpressure: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[4]  # fifo_full_backpressure
    failures = await run_test_vector(dut, "fifo_full_backpressure", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] fifo_full_backpressure")
    else:
        dut._log.error(f"[FAIL] fifo_full_backpressure: {failures} mismatch(es)")


@cocotb.test()
async def test_partial_strb_write(dut):
    """Test 8: Partial strobe write transaction."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_partial_strb_write: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[5]  # partial_strb_write
    failures = await run_test_vector(dut, "partial_strb_write", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] partial_strb_write")
    else:
        dut._log.error(f"[FAIL] partial_strb_write: {failures} mismatch(es)")


@cocotb.test()
async def test_read_slave_error(dut):
    """Test 9: Read transaction with slave error response."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_read_slave_error: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    slave = AxiSlaveBFM(dut)
    slave.start()

    tv = TEST_VECTORS[6]  # read_slave_error
    failures = await run_test_vector(dut, "read_slave_error", tv, slave)

    slave.stop()
    if failures == 0:
        dut._log.info("[PASS] read_slave_error")
    else:
        dut._log.error(f"[FAIL] read_slave_error: {failures} mismatch(es)")


@cocotb.test()
async def test_timing_contract(dut):
    """Test 10: Verify timing contract invariants at runtime.

    Checks that registered outputs remain stable between posedge and negedge.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Registered outputs from spec.json timing_contract
    REGISTERED_OUTPUTS = [
        "s_axi_awready", "s_axi_wready", "s_axi_bvalid", "s_axi_bresp",
        "s_axi_arready", "s_axi_rvalid", "s_axi_rdata", "s_axi_rresp",
        "m_axi_awvalid", "m_axi_awaddr", "m_axi_awprot",
        "m_axi_wvalid", "m_axi_wdata", "m_axi_wstrb",
        "m_axi_bready",
        "m_axi_arvalid", "m_axi_araddr", "m_axi_arprot",
        "m_axi_rready",
    ]

    violations = []
    for cycle in range(20):
        # Sample registered outputs at posedge of s_axi_aclk
        for port_name in REGISTERED_OUTPUTS:
            try:
                sig = getattr(dut, port_name)
                posedge_val = int(sig.value)
                await FallingEdge(dut.s_axi_aclk)
                negedge_val = int(sig.value)
                if posedge_val != negedge_val:
                    violations.append(
                        f"cycle={cycle} {port_name}: changed between "
                        f"posedge ({posedge_val}) and negedge ({negedge_val}) "
                        f"-- registered output must be stable"
                    )
            except (AttributeError, ValueError):
                pass
        await RisingEdge(dut.s_axi_aclk)

        if any(v.startswith("cycle") for v in violations):
            break

    if violations:
        for v in violations[:5]:
            dut._log.error(f"[TIMING CONTRACT] {v}")
        FAIL_COUNT += len(violations)
        raise AssertionError(f"Timing contract violated: {violations[0]}")
    else:
        dut._log.info("[TIMING CONTRACT] PASS -- all invariants hold")


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    MUST be the last test defined in this file -- cocotb runs tests in
    definition order. This test reads the accumulated FAIL_COUNT.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.s_axi_aclk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
