// Auto-generated by VeriFlow DSL from module pipeline_register
`resetall
`timescale 1ns / 1ps
`default_nettype none

module pipeline_register
(
    input  wire         clk,
    input  wire         rst,
    output wire [31:0] data_0_reg,
    output wire [31:0] data_1_reg,
    output wire [31:0] data_2_reg,
    output wire valid_0_reg,
    output wire valid_1_reg,
    output wire valid_2_reg,
    input  wire [31:0] data_in,
    input  wire valid_in
);

reg [31:0] data_0_reg_reg = 32'd0;
reg [31:0] data_1_reg_reg = 32'd0;
reg [31:0] data_2_reg_reg = 32'd0;
reg [0:0] valid_0_reg_reg = 1'd0;
reg [0:0] valid_1_reg_reg = 1'd0;
reg [0:0] valid_2_reg_reg = 1'd0;

// Sequential logic (register update)
always @(posedge clk) begin
    data_0_reg_reg <= (valid_in ? data_in : 1'd0);
    valid_0_reg_reg <= valid_in;
    data_1_reg_reg <= (valid_0_reg_reg ? data_0_reg_reg : 1'd0);
    valid_1_reg_reg <= valid_0_reg_reg;
    data_2_reg_reg <= (valid_1_reg_reg ? data_1_reg_reg : 1'd0);
    valid_2_reg_reg <= valid_1_reg_reg;
    if (rst) begin
        data_0_reg_reg <= 32'd0;
        valid_0_reg_reg <= 1'd0;
        data_1_reg_reg <= 32'd0;
        valid_1_reg_reg <= 1'd0;
        data_2_reg_reg <= 32'd0;
        valid_2_reg_reg <= 1'd0;
    end
end

// Output wire assignments
assign data_0_reg = data_0_reg_reg;
assign data_1_reg = data_1_reg_reg;
assign data_2_reg = data_2_reg_reg;
assign valid_0_reg = valid_0_reg_reg;
assign valid_1_reg = valid_1_reg_reg;
assign valid_2_reg = valid_2_reg_reg;

endmodule

`resetall