"""Anchor trace.md drift guard.

Each anchor under src/claude_skills/vf-rtl/anchors/<name>/ MUST have:
  - timing_model.py (already required for emit)
  - module.v
  - trace.md generated by veriflow_dsl.trace_export

These tests catch:
  - Missing trace.md (anchor added without regenerating)
  - Empty/malformed trace.md
  - Anchor names that the trace exporter cannot adapt
  - Schema mismatch between trace columns and timing_model parameters

If you add a new anchor, regenerate trace.md via:
    PYTHONPATH=src python -m veriflow_dsl.trace_export \
        --timing-model src/claude_skills/vf-rtl/anchors/<name>/timing_model.py \
        --block <name> --cycles N \
        [--inputs <inputs.json>] \
        --output src/claude_skills/vf-rtl/anchors/<name>/trace.md
"""

import importlib.util
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ANCHORS_DIR = REPO_ROOT / "src/claude_skills/vf-rtl/anchors"

sys.path.insert(0, str(REPO_ROOT / "src"))


def _list_anchors() -> list[str]:
    """Return anchor directory names that have a timing_model.py."""
    return sorted(
        d.name for d in ANCHORS_DIR.iterdir()
        if d.is_dir() and (d / "timing_model.py").is_file()
    )


def _load_block(anchor: str):
    """Import the @vf_block function named after the anchor."""
    tm_path = ANCHORS_DIR / anchor / "timing_model.py"
    spec = importlib.util.spec_from_file_location(
        f"_anchor_tm_{anchor}", str(tm_path),
    )
    module_obj = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(tm_path.parent))
    try:
        spec.loader.exec_module(module_obj)
    finally:
        sys.path.remove(str(tm_path.parent))
    if not hasattr(module_obj, anchor):
        raise AttributeError(
            f"{tm_path} does not define a function named {anchor!r} "
            f"(expected to match the directory name)"
        )
    return getattr(module_obj, anchor)


class TestAnchorTracesPresent(unittest.TestCase):
    """Every anchor with a timing_model.py must ship a trace.md."""

    def test_each_anchor_has_trace_file(self):
        anchors = _list_anchors()
        self.assertGreater(len(anchors), 0, "No anchors found — directory layout broken?")
        missing = [
            a for a in anchors
            if not (ANCHORS_DIR / a / "trace.md").is_file()
        ]
        self.assertEqual(
            missing, [],
            "Anchors missing trace.md — regenerate via trace_export CLI:\n  "
            + "\n  ".join(missing),
        )

    def test_each_trace_is_non_empty(self):
        for anchor in _list_anchors():
            with self.subTest(anchor=anchor):
                trace_path = ANCHORS_DIR / anchor / "trace.md"
                content = trace_path.read_text().strip()
                self.assertGreater(
                    len(content), 0,
                    f"{trace_path} is empty",
                )

    def test_each_trace_has_table(self):
        """Trace must contain a markdown table (lines starting with '|')."""
        for anchor in _list_anchors():
            with self.subTest(anchor=anchor):
                trace_path = ANCHORS_DIR / anchor / "trace.md"
                table_lines = [
                    ln for ln in trace_path.read_text().splitlines()
                    if ln.startswith("|")
                ]
                # header + separator + at least 1 data row
                self.assertGreaterEqual(
                    len(table_lines), 3,
                    f"{trace_path} missing markdown table",
                )

    def test_each_trace_header_names_anchor(self):
        """Trace's '## ...' line must mention the anchor (so SKILL.md can
        embed multiple traces in one prompt without ambiguity)."""
        for anchor in _list_anchors():
            with self.subTest(anchor=anchor):
                trace_path = ANCHORS_DIR / anchor / "trace.md"
                heading = next(
                    (ln for ln in trace_path.read_text().splitlines()
                     if ln.startswith("##")),
                    "",
                )
                self.assertIn(
                    anchor, heading,
                    f"{trace_path}: heading {heading!r} does not name {anchor!r}",
                )


class TestAnchorTracesRegenerable(unittest.TestCase):
    """Each anchor's @vf_block function must adapt and simulate without error.

    This guards against future timing_model.py edits that would break the
    trace pipeline silently.
    """

    def test_each_anchor_block_adapts_and_simulates(self):
        from veriflow_dsl import from_timing_model
        from veriflow_dsl._simulator import CycleSimulator

        for anchor in _list_anchors():
            with self.subTest(anchor=anchor):
                func = _load_block(anchor)
                self.assertTrue(
                    hasattr(func, "_vf_block_type"),
                    f"{anchor}: function is not @vf_block decorated",
                )
                m = from_timing_model(func)
                sim = CycleSimulator(m)
                # 1 cycle is enough to verify the simulator can step.
                sim.step()


class TestAnchorTraceColumnsMatchPorts(unittest.TestCase):
    """Trace table columns must include every signal the simulator records,
    so a regenerated trace cannot silently drop signals.
    """

    def test_trace_columns_cover_register_names(self):
        from veriflow_dsl import from_timing_model

        for anchor in _list_anchors():
            with self.subTest(anchor=anchor):
                trace_path = ANCHORS_DIR / anchor / "trace.md"
                func = _load_block(anchor)
                m = from_timing_model(func)
                analysis = m.analyze()
                reg_names = [
                    n for n, info in analysis["signals"].items()
                    if info["timing"] == "reg_next"
                ]

                content = trace_path.read_text()
                table_header = next(
                    (ln for ln in content.splitlines() if ln.startswith("| cycle")),
                    "",
                )
                self.assertNotEqual(table_header, "", f"{trace_path}: no header row")

                missing = [n for n in reg_names if n not in table_header]
                self.assertEqual(
                    missing, [],
                    f"{trace_path}: register columns missing from header: {missing}",
                )


if __name__ == "__main__":
    unittest.main()
