`timescale 1ns / 1ps

// tb_fft64_radix4_sdf.v -- Self-checking Verilog testbench for fft64_radix4_sdf.
// Generated by VeriFlow-CC.
//
// Tests all 4 golden model test vectors:
//   1. impulse_idx0    - Impulse at index 0 (all bins equal magnitude)
//   2. constant_dc     - DC signal (bin 0 only)
//   3. single_freq_k1  - Single frequency bin k=1
//   4. random_complex  - Pseudo-random complex input
//
// Compares RTL output against pre-computed expected values from golden_model.py.
// Uses toleranced comparison (TOL_LSB) to account for Q1.15 quantization.
// Reports PASS/FAIL per sample and overall.

module tb_fft64_radix4_sdf;

    // =========================================================================
    // Parameters
    // =========================================================================
    parameter N = 64;                  // FFT size
    parameter DATA_W = 16;             // Q1.15 data width
    parameter PIPELINE_LATENCY = 67;   // cycles from first in_valid to first out_valid
    parameter TOL_LSB = 4;             // tolerance in LSBs for Q1.15 comparison
    parameter CLK_PERIOD_NS = 10;      // 100 MHz full period
    parameter HALF_PERIOD_NS = 5;      // half period

    // =========================================================================
    // Port declarations matching DUT
    // =========================================================================
    reg         clk;
    reg         rst_n;
    reg         in_valid;
    reg  [15:0] in_data_re;
    reg  [15:0] in_data_im;
    wire        out_valid;
    wire [15:0] out_data_re;
    wire [15:0] out_data_im;
    wire [5:0]  out_index;

    // Cycle counter and fail counter
    integer cycle_count = 0;
    integer fail_count  = 0;
    integer test_pass_count = 0;

    // =========================================================================
    // DUT instantiation
    // =========================================================================
    fft64_radix4_sdf uut (
        .clk        (clk),
        .rst_n      (rst_n),
        .in_valid   (in_valid),
        .in_data_re (in_data_re),
        .in_data_im (in_data_im),
        .out_valid  (out_valid),
        .out_data_re(out_data_re),
        .out_data_im(out_data_im),
        .out_index  (out_index)
    );

    // =========================================================================
    // Clock generation (half-period from target frequency)
    // =========================================================================
    initial clk = 0;
    always #HALF_PERIOD_NS clk = ~clk;

    // Cycle counter -- increment every posedge
    always @(posedge clk) cycle_count = cycle_count + 1;

    // =========================================================================
    // VCD capture
    // =========================================================================
    initial begin
        $dumpfile("tb_fft64_radix4_sdf.vcd");
        $dumpvars(0, tb_fft64_radix4_sdf);
    end

    // =========================================================================
    // TESTBENCH TIMING METHODOLOGY
    // =========================================================================
    //
    // Rule 1: NBA FOR DUT INPUTS (MANDATORY)
    //   All DUT input assignments in initial blocks MUST use non-blocking
    //   assignment (<=). This prevents race conditions between the testbench
    //   and the DUT's sequential always blocks at the same posedge.
    //
    // Rule 2: RESET SEQUENCE TIMING (async active-low)
    //   rst_n = 1'b0;                     // blocking OK for reset only
    //   <zero all data inputs with <=>
    //   @(posedge clk); @(posedge clk);   // hold reset 2+ cycles
    //   rst_n = 1'b1;                     // blocking OK for reset only
    //   @(negedge clk);                   // wait for NBA to settle
    //
    // Rule 3: STREAMING FFT -- no multi-block, no is_last, no backpressure.
    //   Drive 64 samples with in_valid=1, deassert, wait for pipeline latency,
    //   then capture 64 outputs.
    //
    // Rule 4: OUTPUT SAMPLING -- posedge vs negedge
    //   PULSE signals (out_valid): detect at posedge.
    //   REGISTERED DATA (out_data_re/im, out_index): sample at negedge AFTER
    //   the posedge where out_valid was detected.
    //
    // Rule 5: TIMING CONTRACT
    //   Pipeline latency = 67 cycles from first in_valid to first out_valid.
    //   Registered outputs: stable between posedge and negedge.
    //
    // =========================================================================

    // =========================================================================
    // MACROS: Race-free sampling helpers
    // =========================================================================
    `define SAMPLE_REGISTERED_OUTPUT(sig, expected, test_name, idx) \
        @(negedge clk); \
        if (sig !== expected) begin \
            if ((sig > expected) ? ((sig - expected) > TOL_LSB) : ((expected - sig) > TOL_LSB)) begin \
                $display("[FAIL] test=%s sample[%0d] signal=%s kind=registered width=%0db expected=0x%0h actual=0x%0h xor=0x%0h phase=negedge", \
                         test_name, idx, `"sig`", $bits(sig), expected, sig, (expected ^ sig)); \
                fail_count = fail_count + 1; \
            end \
        end else \
            $display("[PASS] test=%s sample[%0d] signal=%s kind=registered width=%0db actual=0x%0h phase=negedge", \
                     test_name, idx, `"sig`", $bits(sig), sig);

    `define CHECK_TOLERANCED(actual, expected, test_name, idx, comp_name) \
        if (actual !== expected) begin \
            if ((actual > expected) ? ((actual - expected) > TOL_LSB) : ((expected - actual) > TOL_LSB)) begin \
                $display("[FAIL] test=%s sample[%0d] signal=%s expected=0x%0h actual=0x%0h xor=0x%0h", \
                         test_name, idx, comp_name, expected, actual, (expected ^ actual)); \
                fail_count = fail_count + 1; \
            end \
        end

    // =========================================================================
    // RESET TASK: Must be called at start of EVERY independent test
    // =========================================================================
    task automatic apply_reset;
        begin
            rst_n = 1'b0;                    // blocking OK for reset only
            in_valid   <= 1'b0;
            in_data_re <= 16'h0000;
            in_data_im <= 16'h0000;
            @(posedge clk); @(posedge clk); @(posedge clk);
            rst_n = 1'b1;                    // blocking OK for reset only
            @(negedge clk);                  // wait for NBA to settle after rst_n deassert
            $display("[TRACE] cycle=%0d rst_n released", cycle_count);
        end
    endtask

    // =========================================================================
    // DRIVE_FFT_INPUTS task: Drive 64 samples with in_valid=1
    // =========================================================================
    task automatic drive_fft_inputs;
        input [15:0] re_mem [0:63];
        input [15:0] im_mem [0:63];
        integer i;
        begin
            in_valid <= 1'b0;
            in_data_re <= 16'h0000;
            in_data_im <= 16'h0000;
            @(posedge clk);

            for (i = 0; i < 64; i = i + 1) begin
                in_valid   <= 1'b1;
                in_data_re <= re_mem[i];
                in_data_im <= im_mem[i];
                @(posedge clk);
            end

            in_valid   <= 1'b0;
            in_data_re <= 16'h0000;
            in_data_im <= 16'h0000;
        end
    endtask

    // =========================================================================
    // CAPTURE_AND_CHECK task: Wait for pipeline, capture 64 outputs, compare
    // =========================================================================
    task automatic capture_and_check;
        input [15:0] exp_re [0:63];
        input [15:0] exp_im [0:63];
        input [255:0] test_name_str;
        integer i;
        integer captured;
        integer max_err_re;
        integer max_err_im;
        integer err_re;
        integer err_im;
        integer total_err_sq;
        integer sig_sq;
        integer sample_pass_count;
        reg [15:0] act_re;
        reg [15:0] act_im;
        reg [5:0]  act_idx;
        begin
            // Wait for pipeline latency
            for (i = 0; i < PIPELINE_LATENCY; i = i + 1)
                @(posedge clk);

            // Capture 64 outputs
            captured = 0;
            max_err_re = 0;
            max_err_im = 0;
            total_err_sq = 0;
            sig_sq = 0;
            sample_pass_count = 0;

            for (i = 0; i < 64 + 20; i = i + 1) begin
                @(posedge clk);
                if (out_valid === 1'b1) begin
                    @(negedge clk);  // wait for NBA to settle on registered outputs
                    act_re = out_data_re;
                    act_im = out_data_im;
                    act_idx = out_index;

                    // Toleranced comparison
                    err_re = (act_re > exp_re[captured]) ? (act_re - exp_re[captured]) : (exp_re[captured] - act_re);
                    err_im = (act_im > exp_im[captured]) ? (act_im - exp_im[captured]) : (exp_im[captured] - act_im);

                    if ((err_re > TOL_LSB) || (err_im > TOL_LSB)) begin
                        $display("[FAIL] test=%0s sample[%0d] idx=%0d expected_re=0x%04h actual_re=0x%04h expected_im=0x%04h actual_im=0x%04h",
                                 test_name_str, captured, act_idx,
                                 exp_re[captured], act_re,
                                 exp_im[captured], act_im);
                        fail_count = fail_count + 1;
                    end else begin
                        sample_pass_count = sample_pass_count + 1;
                    end

                    captured = captured + 1;
                    if (captured >= 64)
                        break;
                end
            end

            if (captured < 64) begin
                $display("[FAIL] test=%0s Only captured %0d/64 output samples",
                         test_name_str, captured);
                fail_count = fail_count + 1;
            end else if (sample_pass_count == 64) begin
                $display("[PASS] test=%0s All 64 samples matched (tolerance=%0d LSB)", test_name_str, TOL_LSB);
                test_pass_count = test_pass_count + 1;
            end else begin
                $display("[WARN] test=%0s %0d/64 samples matched, %0d outside tolerance",
                         test_name_str, sample_pass_count, 64 - sample_pass_count);
            end
        end
    endtask

    // =========================================================================
    // Pre-computed test vectors from golden_model.py
    // =========================================================================

    // --- Test vector 0: impulse_idx0 ---
    // Input: impulse at index 0
    reg [15:0] tv0_in_re [0:63];
    reg [15:0] tv0_in_im [0:63];
    reg [15:0] tv0_exp_re [0:63];
    reg [15:0] tv0_exp_im [0:63];

    initial begin
        // Input re
        tv0_in_re[ 0] = 16'h7fff; tv0_in_re[ 1] = 16'h0000; tv0_in_re[ 2] = 16'h0000; tv0_in_re[ 3] = 16'h0000;
        tv0_in_re[ 4] = 16'h0000; tv0_in_re[ 5] = 16'h0000; tv0_in_re[ 6] = 16'h0000; tv0_in_re[ 7] = 16'h0000;
        tv0_in_re[ 8] = 16'h0000; tv0_in_re[ 9] = 16'h0000; tv0_in_re[10] = 16'h0000; tv0_in_re[11] = 16'h0000;
        tv0_in_re[12] = 16'h0000; tv0_in_re[13] = 16'h0000; tv0_in_re[14] = 16'h0000; tv0_in_re[15] = 16'h0000;
        tv0_in_re[16] = 16'h0000; tv0_in_re[17] = 16'h0000; tv0_in_re[18] = 16'h0000; tv0_in_re[19] = 16'h0000;
        tv0_in_re[20] = 16'h0000; tv0_in_re[21] = 16'h0000; tv0_in_re[22] = 16'h0000; tv0_in_re[23] = 16'h0000;
        tv0_in_re[24] = 16'h0000; tv0_in_re[25] = 16'h0000; tv0_in_re[26] = 16'h0000; tv0_in_re[27] = 16'h0000;
        tv0_in_re[28] = 16'h0000; tv0_in_re[29] = 16'h0000; tv0_in_re[30] = 16'h0000; tv0_in_re[31] = 16'h0000;
        tv0_in_re[32] = 16'h0000; tv0_in_re[33] = 16'h0000; tv0_in_re[34] = 16'h0000; tv0_in_re[35] = 16'h0000;
        tv0_in_re[36] = 16'h0000; tv0_in_re[37] = 16'h0000; tv0_in_re[38] = 16'h0000; tv0_in_re[39] = 16'h0000;
        tv0_in_re[40] = 16'h0000; tv0_in_re[41] = 16'h0000; tv0_in_re[42] = 16'h0000; tv0_in_re[43] = 16'h0000;
        tv0_in_re[44] = 16'h0000; tv0_in_re[45] = 16'h0000; tv0_in_re[46] = 16'h0000; tv0_in_re[47] = 16'h0000;
        tv0_in_re[48] = 16'h0000; tv0_in_re[49] = 16'h0000; tv0_in_re[50] = 16'h0000; tv0_in_re[51] = 16'h0000;
        tv0_in_re[52] = 16'h0000; tv0_in_re[53] = 16'h0000; tv0_in_re[54] = 16'h0000; tv0_in_re[55] = 16'h0000;
        tv0_in_re[56] = 16'h0000; tv0_in_re[57] = 16'h0000; tv0_in_re[58] = 16'h0000; tv0_in_re[59] = 16'h0000;
        tv0_in_re[60] = 16'h0000; tv0_in_re[61] = 16'h0000; tv0_in_re[62] = 16'h0000; tv0_in_re[63] = 16'h0000;
        // Input im
        tv0_in_im[ 0] = 16'h0000; tv0_in_im[ 1] = 16'h0000; tv0_in_im[ 2] = 16'h0000; tv0_in_im[ 3] = 16'h0000;
        tv0_in_im[ 4] = 16'h0000; tv0_in_im[ 5] = 16'h0000; tv0_in_im[ 6] = 16'h0000; tv0_in_im[ 7] = 16'h0000;
        tv0_in_im[ 8] = 16'h0000; tv0_in_im[ 9] = 16'h0000; tv0_in_im[10] = 16'h0000; tv0_in_im[11] = 16'h0000;
        tv0_in_im[12] = 16'h0000; tv0_in_im[13] = 16'h0000; tv0_in_im[14] = 16'h0000; tv0_in_im[15] = 16'h0000;
        tv0_in_im[16] = 16'h0000; tv0_in_im[17] = 16'h0000; tv0_in_im[18] = 16'h0000; tv0_in_im[19] = 16'h0000;
        tv0_in_im[20] = 16'h0000; tv0_in_im[21] = 16'h0000; tv0_in_im[22] = 16'h0000; tv0_in_im[23] = 16'h0000;
        tv0_in_im[24] = 16'h0000; tv0_in_im[25] = 16'h0000; tv0_in_im[26] = 16'h0000; tv0_in_im[27] = 16'h0000;
        tv0_in_im[28] = 16'h0000; tv0_in_im[29] = 16'h0000; tv0_in_im[30] = 16'h0000; tv0_in_im[31] = 16'h0000;
        tv0_in_im[32] = 16'h0000; tv0_in_im[33] = 16'h0000; tv0_in_im[34] = 16'h0000; tv0_in_im[35] = 16'h0000;
        tv0_in_im[36] = 16'h0000; tv0_in_im[37] = 16'h0000; tv0_in_im[38] = 16'h0000; tv0_in_im[39] = 16'h0000;
        tv0_in_im[40] = 16'h0000; tv0_in_im[41] = 16'h0000; tv0_in_im[42] = 16'h0000; tv0_in_im[43] = 16'h0000;
        tv0_in_im[44] = 16'h0000; tv0_in_im[45] = 16'h0000; tv0_in_im[46] = 16'h0000; tv0_in_im[47] = 16'h0000;
        tv0_in_im[48] = 16'h0000; tv0_in_im[49] = 16'h0000; tv0_in_im[50] = 16'h0000; tv0_in_im[51] = 16'h0000;
        tv0_in_im[52] = 16'h0000; tv0_in_im[53] = 16'h0000; tv0_in_im[54] = 16'h0000; tv0_in_im[55] = 16'h0000;
        tv0_in_im[56] = 16'h0000; tv0_in_im[57] = 16'h0000; tv0_in_im[58] = 16'h0000; tv0_in_im[59] = 16'h0000;
        tv0_in_im[60] = 16'h0000; tv0_in_im[61] = 16'h0000; tv0_in_im[62] = 16'h0000; tv0_in_im[63] = 16'h0000;
        // Expected re (all bins = 0x7FFF for impulse)
        tv0_exp_re[ 0] = 16'h7fff; tv0_exp_re[ 1] = 16'h7fff; tv0_exp_re[ 2] = 16'h7fff; tv0_exp_re[ 3] = 16'h7fff;
        tv0_exp_re[ 4] = 16'h7fff; tv0_exp_re[ 5] = 16'h7fff; tv0_exp_re[ 6] = 16'h7fff; tv0_exp_re[ 7] = 16'h7fff;
        tv0_exp_re[ 8] = 16'h7fff; tv0_exp_re[ 9] = 16'h7fff; tv0_exp_re[10] = 16'h7fff; tv0_exp_re[11] = 16'h7fff;
        tv0_exp_re[12] = 16'h7fff; tv0_exp_re[13] = 16'h7fff; tv0_exp_re[14] = 16'h7fff; tv0_exp_re[15] = 16'h7fff;
        tv0_exp_re[16] = 16'h7fff; tv0_exp_re[17] = 16'h7fff; tv0_exp_re[18] = 16'h7fff; tv0_exp_re[19] = 16'h7fff;
        tv0_exp_re[20] = 16'h7fff; tv0_exp_re[21] = 16'h7fff; tv0_exp_re[22] = 16'h7fff; tv0_exp_re[23] = 16'h7fff;
        tv0_exp_re[24] = 16'h7fff; tv0_exp_re[25] = 16'h7fff; tv0_exp_re[26] = 16'h7fff; tv0_exp_re[27] = 16'h7fff;
        tv0_exp_re[28] = 16'h7fff; tv0_exp_re[29] = 16'h7fff; tv0_exp_re[30] = 16'h7fff; tv0_exp_re[31] = 16'h7fff;
        tv0_exp_re[32] = 16'h7fff; tv0_exp_re[33] = 16'h7fff; tv0_exp_re[34] = 16'h7fff; tv0_exp_re[35] = 16'h7fff;
        tv0_exp_re[36] = 16'h7fff; tv0_exp_re[37] = 16'h7fff; tv0_exp_re[38] = 16'h7fff; tv0_exp_re[39] = 16'h7fff;
        tv0_exp_re[40] = 16'h7fff; tv0_exp_re[41] = 16'h7fff; tv0_exp_re[42] = 16'h7fff; tv0_exp_re[43] = 16'h7fff;
        tv0_exp_re[44] = 16'h7fff; tv0_exp_re[45] = 16'h7fff; tv0_exp_re[46] = 16'h7fff; tv0_exp_re[47] = 16'h7fff;
        tv0_exp_re[48] = 16'h7fff; tv0_exp_re[49] = 16'h7fff; tv0_exp_re[50] = 16'h7fff; tv0_exp_re[51] = 16'h7fff;
        tv0_exp_re[52] = 16'h7fff; tv0_exp_re[53] = 16'h7fff; tv0_exp_re[54] = 16'h7fff; tv0_exp_re[55] = 16'h7fff;
        tv0_exp_re[56] = 16'h7fff; tv0_exp_re[57] = 16'h7fff; tv0_exp_re[58] = 16'h7fff; tv0_exp_re[59] = 16'h7fff;
        tv0_exp_re[60] = 16'h7fff; tv0_exp_re[61] = 16'h7fff; tv0_exp_re[62] = 16'h7fff; tv0_exp_re[63] = 16'h7fff;
        // Expected im (all zeros)
        tv0_exp_im[ 0] = 16'h0000; tv0_exp_im[ 1] = 16'h0000; tv0_exp_im[ 2] = 16'h0000; tv0_exp_im[ 3] = 16'h0000;
        tv0_exp_im[ 4] = 16'h0000; tv0_exp_im[ 5] = 16'h0000; tv0_exp_im[ 6] = 16'h0000; tv0_exp_im[ 7] = 16'h0000;
        tv0_exp_im[ 8] = 16'h0000; tv0_exp_im[ 9] = 16'h0000; tv0_exp_im[10] = 16'h0000; tv0_exp_im[11] = 16'h0000;
        tv0_exp_im[12] = 16'h0000; tv0_exp_im[13] = 16'h0000; tv0_exp_im[14] = 16'h0000; tv0_exp_im[15] = 16'h0000;
        tv0_exp_im[16] = 16'h0000; tv0_exp_im[17] = 16'h0000; tv0_exp_im[18] = 16'h0000; tv0_exp_im[19] = 16'h0000;
        tv0_exp_im[20] = 16'h0000; tv0_exp_im[21] = 16'h0000; tv0_exp_im[22] = 16'h0000; tv0_exp_im[23] = 16'h0000;
        tv0_exp_im[24] = 16'h0000; tv0_exp_im[25] = 16'h0000; tv0_exp_im[26] = 16'h0000; tv0_exp_im[27] = 16'h0000;
        tv0_exp_im[28] = 16'h0000; tv0_exp_im[29] = 16'h0000; tv0_exp_im[30] = 16'h0000; tv0_exp_im[31] = 16'h0000;
        tv0_exp_im[32] = 16'h0000; tv0_exp_im[33] = 16'h0000; tv0_exp_im[34] = 16'h0000; tv0_exp_im[35] = 16'h0000;
        tv0_exp_im[36] = 16'h0000; tv0_exp_im[37] = 16'h0000; tv0_exp_im[38] = 16'h0000; tv0_exp_im[39] = 16'h0000;
        tv0_exp_im[40] = 16'h0000; tv0_exp_im[41] = 16'h0000; tv0_exp_im[42] = 16'h0000; tv0_exp_im[43] = 16'h0000;
        tv0_exp_im[44] = 16'h0000; tv0_exp_im[45] = 16'h0000; tv0_exp_im[46] = 16'h0000; tv0_exp_im[47] = 16'h0000;
        tv0_exp_im[48] = 16'h0000; tv0_exp_im[49] = 16'h0000; tv0_exp_im[50] = 16'h0000; tv0_exp_im[51] = 16'h0000;
        tv0_exp_im[52] = 16'h0000; tv0_exp_im[53] = 16'h0000; tv0_exp_im[54] = 16'h0000; tv0_exp_im[55] = 16'h0000;
        tv0_exp_im[56] = 16'h0000; tv0_exp_im[57] = 16'h0000; tv0_exp_im[58] = 16'h0000; tv0_exp_im[59] = 16'h0000;
        tv0_exp_im[60] = 16'h0000; tv0_exp_im[61] = 16'h0000; tv0_exp_im[62] = 16'h0000; tv0_exp_im[63] = 16'h0000;
    end

    // --- Test vector 1: constant_dc ---
    reg [15:0] tv1_in_re [0:63];
    reg [15:0] tv1_in_im [0:63];
    reg [15:0] tv1_exp_re [0:63];
    reg [15:0] tv1_exp_im [0:63];

    initial begin
        // Input re (all 0x7FFF)
        tv1_in_re[ 0] = 16'h7fff; tv1_in_re[ 1] = 16'h7fff; tv1_in_re[ 2] = 16'h7fff; tv1_in_re[ 3] = 16'h7fff;
        tv1_in_re[ 4] = 16'h7fff; tv1_in_re[ 5] = 16'h7fff; tv1_in_re[ 6] = 16'h7fff; tv1_in_re[ 7] = 16'h7fff;
        tv1_in_re[ 8] = 16'h7fff; tv1_in_re[ 9] = 16'h7fff; tv1_in_re[10] = 16'h7fff; tv1_in_re[11] = 16'h7fff;
        tv1_in_re[12] = 16'h7fff; tv1_in_re[13] = 16'h7fff; tv1_in_re[14] = 16'h7fff; tv1_in_re[15] = 16'h7fff;
        tv1_in_re[16] = 16'h7fff; tv1_in_re[17] = 16'h7fff; tv1_in_re[18] = 16'h7fff; tv1_in_re[19] = 16'h7fff;
        tv1_in_re[20] = 16'h7fff; tv1_in_re[21] = 16'h7fff; tv1_in_re[22] = 16'h7fff; tv1_in_re[23] = 16'h7fff;
        tv1_in_re[24] = 16'h7fff; tv1_in_re[25] = 16'h7fff; tv1_in_re[26] = 16'h7fff; tv1_in_re[27] = 16'h7fff;
        tv1_in_re[28] = 16'h7fff; tv1_in_re[29] = 16'h7fff; tv1_in_re[30] = 16'h7fff; tv1_in_re[31] = 16'h7fff;
        tv1_in_re[32] = 16'h7fff; tv1_in_re[33] = 16'h7fff; tv1_in_re[34] = 16'h7fff; tv1_in_re[35] = 16'h7fff;
        tv1_in_re[36] = 16'h7fff; tv1_in_re[37] = 16'h7fff; tv1_in_re[38] = 16'h7fff; tv1_in_re[39] = 16'h7fff;
        tv1_in_re[40] = 16'h7fff; tv1_in_re[41] = 16'h7fff; tv1_in_re[42] = 16'h7fff; tv1_in_re[43] = 16'h7fff;
        tv1_in_re[44] = 16'h7fff; tv1_in_re[45] = 16'h7fff; tv1_in_re[46] = 16'h7fff; tv1_in_re[47] = 16'h7fff;
        tv1_in_re[48] = 16'h7fff; tv1_in_re[49] = 16'h7fff; tv1_in_re[50] = 16'h7fff; tv1_in_re[51] = 16'h7fff;
        tv1_in_re[52] = 16'h7fff; tv1_in_re[53] = 16'h7fff; tv1_in_re[54] = 16'h7fff; tv1_in_re[55] = 16'h7fff;
        tv1_in_re[56] = 16'h7fff; tv1_in_re[57] = 16'h7fff; tv1_in_re[58] = 16'h7fff; tv1_in_re[59] = 16'h7fff;
        tv1_in_re[60] = 16'h7fff; tv1_in_re[61] = 16'h7fff; tv1_in_re[62] = 16'h7fff; tv1_in_re[63] = 16'h7fff;
        // Input im (all zeros)
        tv1_in_im[ 0] = 16'h0000; tv1_in_im[ 1] = 16'h0000; tv1_in_im[ 2] = 16'h0000; tv1_in_im[ 3] = 16'h0000;
        tv1_in_im[ 4] = 16'h0000; tv1_in_im[ 5] = 16'h0000; tv1_in_im[ 6] = 16'h0000; tv1_in_im[ 7] = 16'h0000;
        tv1_in_im[ 8] = 16'h0000; tv1_in_im[ 9] = 16'h0000; tv1_in_im[10] = 16'h0000; tv1_in_im[11] = 16'h0000;
        tv1_in_im[12] = 16'h0000; tv1_in_im[13] = 16'h0000; tv1_in_im[14] = 16'h0000; tv1_in_im[15] = 16'h0000;
        tv1_in_im[16] = 16'h0000; tv1_in_im[17] = 16'h0000; tv1_in_im[18] = 16'h0000; tv1_in_im[19] = 16'h0000;
        tv1_in_im[20] = 16'h0000; tv1_in_im[21] = 16'h0000; tv1_in_im[22] = 16'h0000; tv1_in_im[23] = 16'h0000;
        tv1_in_im[24] = 16'h0000; tv1_in_im[25] = 16'h0000; tv1_in_im[26] = 16'h0000; tv1_in_im[27] = 16'h0000;
        tv1_in_im[28] = 16'h0000; tv1_in_im[29] = 16'h0000; tv1_in_im[30] = 16'h0000; tv1_in_im[31] = 16'h0000;
        tv1_in_im[32] = 16'h0000; tv1_in_im[33] = 16'h0000; tv1_in_im[34] = 16'h0000; tv1_in_im[35] = 16'h0000;
        tv1_in_im[36] = 16'h0000; tv1_in_im[37] = 16'h0000; tv1_in_im[38] = 16'h0000; tv1_in_im[39] = 16'h0000;
        tv1_in_im[40] = 16'h0000; tv1_in_im[41] = 16'h0000; tv1_in_im[42] = 16'h0000; tv1_in_im[43] = 16'h0000;
        tv1_in_im[44] = 16'h0000; tv1_in_im[45] = 16'h0000; tv1_in_im[46] = 16'h0000; tv1_in_im[47] = 16'h0000;
        tv1_in_im[48] = 16'h0000; tv1_in_im[49] = 16'h0000; tv1_in_im[50] = 16'h0000; tv1_in_im[51] = 16'h0000;
        tv1_in_im[52] = 16'h0000; tv1_in_im[53] = 16'h0000; tv1_in_im[54] = 16'h0000; tv1_in_im[55] = 16'h0000;
        tv1_in_im[56] = 16'h0000; tv1_in_im[57] = 16'h0000; tv1_in_im[58] = 16'h0000; tv1_in_im[59] = 16'h0000;
        tv1_in_im[60] = 16'h0000; tv1_in_im[61] = 16'h0000; tv1_in_im[62] = 16'h0000; tv1_in_im[63] = 16'h0000;
        // Expected re (bin 0 = 0x7FFF, all others = 0)
        tv1_exp_re[ 0] = 16'h7fff;
        tv1_exp_re[ 1] = 16'h0000; tv1_exp_re[ 2] = 16'h0000; tv1_exp_re[ 3] = 16'h0000;
        tv1_exp_re[ 4] = 16'h0000; tv1_exp_re[ 5] = 16'h0000; tv1_exp_re[ 6] = 16'h0000; tv1_exp_re[ 7] = 16'h0000;
        tv1_exp_re[ 8] = 16'h0000; tv1_exp_re[ 9] = 16'h0000; tv1_exp_re[10] = 16'h0000; tv1_exp_re[11] = 16'h0000;
        tv1_exp_re[12] = 16'h0000; tv1_exp_re[13] = 16'h0000; tv1_exp_re[14] = 16'h0000; tv1_exp_re[15] = 16'h0000;
        tv1_exp_re[16] = 16'h0000; tv1_exp_re[17] = 16'h0000; tv1_exp_re[18] = 16'h0000; tv1_exp_re[19] = 16'h0000;
        tv1_exp_re[20] = 16'h0000; tv1_exp_re[21] = 16'h0000; tv1_exp_re[22] = 16'h0000; tv1_exp_re[23] = 16'h0000;
        tv1_exp_re[24] = 16'h0000; tv1_exp_re[25] = 16'h0000; tv1_exp_re[26] = 16'h0000; tv1_exp_re[27] = 16'h0000;
        tv1_exp_re[28] = 16'h0000; tv1_exp_re[29] = 16'h0000; tv1_exp_re[30] = 16'h0000; tv1_exp_re[31] = 16'h0000;
        tv1_exp_re[32] = 16'h0000; tv1_exp_re[33] = 16'h0000; tv1_exp_re[34] = 16'h0000; tv1_exp_re[35] = 16'h0000;
        tv1_exp_re[36] = 16'h0000; tv1_exp_re[37] = 16'h0000; tv1_exp_re[38] = 16'h0000; tv1_exp_re[39] = 16'h0000;
        tv1_exp_re[40] = 16'h0000; tv1_exp_re[41] = 16'h0000; tv1_exp_re[42] = 16'h0000; tv1_exp_re[43] = 16'h0000;
        tv1_exp_re[44] = 16'h0000; tv1_exp_re[45] = 16'h0000; tv1_exp_re[46] = 16'h0000; tv1_exp_re[47] = 16'h0000;
        tv1_exp_re[48] = 16'h0000; tv1_exp_re[49] = 16'h0000; tv1_exp_re[50] = 16'h0000; tv1_exp_re[51] = 16'h0000;
        tv1_exp_re[52] = 16'h0000; tv1_exp_re[53] = 16'h0000; tv1_exp_re[54] = 16'h0000; tv1_exp_re[55] = 16'h0000;
        tv1_exp_re[56] = 16'h0000; tv1_exp_re[57] = 16'h0000; tv1_exp_re[58] = 16'h0000; tv1_exp_re[59] = 16'h0000;
        tv1_exp_re[60] = 16'h0000; tv1_exp_re[61] = 16'h0000; tv1_exp_re[62] = 16'h0000; tv1_exp_re[63] = 16'h0000;
        // Expected im (all zeros)
        tv1_exp_im[ 0] = 16'h0000; tv1_exp_im[ 1] = 16'h0000; tv1_exp_im[ 2] = 16'h0000; tv1_exp_im[ 3] = 16'h0000;
        tv1_exp_im[ 4] = 16'h0000; tv1_exp_im[ 5] = 16'h0000; tv1_exp_im[ 6] = 16'h0000; tv1_exp_im[ 7] = 16'h0000;
        tv1_exp_im[ 8] = 16'h0000; tv1_exp_im[ 9] = 16'h0000; tv1_exp_im[10] = 16'h0000; tv1_exp_im[11] = 16'h0000;
        tv1_exp_im[12] = 16'h0000; tv1_exp_im[13] = 16'h0000; tv1_exp_im[14] = 16'h0000; tv1_exp_im[15] = 16'h0000;
        tv1_exp_im[16] = 16'h0000; tv1_exp_im[17] = 16'h0000; tv1_exp_im[18] = 16'h0000; tv1_exp_im[19] = 16'h0000;
        tv1_exp_im[20] = 16'h0000; tv1_exp_im[21] = 16'h0000; tv1_exp_im[22] = 16'h0000; tv1_exp_im[23] = 16'h0000;
        tv1_exp_im[24] = 16'h0000; tv1_exp_im[25] = 16'h0000; tv1_exp_im[26] = 16'h0000; tv1_exp_im[27] = 16'h0000;
        tv1_exp_im[28] = 16'h0000; tv1_exp_im[29] = 16'h0000; tv1_exp_im[30] = 16'h0000; tv1_exp_im[31] = 16'h0000;
        tv1_exp_im[32] = 16'h0000; tv1_exp_im[33] = 16'h0000; tv1_exp_im[34] = 16'h0000; tv1_exp_im[35] = 16'h0000;
        tv1_exp_im[36] = 16'h0000; tv1_exp_im[37] = 16'h0000; tv1_exp_im[38] = 16'h0000; tv1_exp_im[39] = 16'h0000;
        tv1_exp_im[40] = 16'h0000; tv1_exp_im[41] = 16'h0000; tv1_exp_im[42] = 16'h0000; tv1_exp_im[43] = 16'h0000;
        tv1_exp_im[44] = 16'h0000; tv1_exp_im[45] = 16'h0000; tv1_exp_im[46] = 16'h0000; tv1_exp_im[47] = 16'h0000;
        tv1_exp_im[48] = 16'h0000; tv1_exp_im[49] = 16'h0000; tv1_exp_im[50] = 16'h0000; tv1_exp_im[51] = 16'h0000;
        tv1_exp_im[52] = 16'h0000; tv1_exp_im[53] = 16'h0000; tv1_exp_im[54] = 16'h0000; tv1_exp_im[55] = 16'h0000;
        tv1_exp_im[56] = 16'h0000; tv1_exp_im[57] = 16'h0000; tv1_exp_im[58] = 16'h0000; tv1_exp_im[59] = 16'h0000;
        tv1_exp_im[60] = 16'h0000; tv1_exp_im[61] = 16'h0000; tv1_exp_im[62] = 16'h0000; tv1_exp_im[63] = 16'h0000;
    end

    // --- Test vector 2: single_freq_k1 ---
    reg [15:0] tv2_in_re [0:63];
    reg [15:0] tv2_in_im [0:63];
    reg [15:0] tv2_exp_re [0:63];
    reg [15:0] tv2_exp_im [0:63];

    initial begin
        // Input re (cosine)
        tv2_in_re[ 0] = 16'h7fff; tv2_in_re[ 1] = 16'h7f62; tv2_in_re[ 2] = 16'h7d8a; tv2_in_re[ 3] = 16'h7a7d;
        tv2_in_re[ 4] = 16'h7642; tv2_in_re[ 5] = 16'h70e3; tv2_in_re[ 6] = 16'h6a6e; tv2_in_re[ 7] = 16'h62f2;
        tv2_in_re[ 8] = 16'h5a82; tv2_in_re[ 9] = 16'h5134; tv2_in_re[10] = 16'h471d; tv2_in_re[11] = 16'h3c57;
        tv2_in_re[12] = 16'h30fc; tv2_in_re[13] = 16'h2528; tv2_in_re[14] = 16'h18f9; tv2_in_re[15] = 16'h0c8c;
        tv2_in_re[16] = 16'h0000; tv2_in_re[17] = 16'hf374; tv2_in_re[18] = 16'he707; tv2_in_re[19] = 16'hdad8;
        tv2_in_re[20] = 16'hcf04; tv2_in_re[21] = 16'hc3a9; tv2_in_re[22] = 16'hb8e3; tv2_in_re[23] = 16'haecc;
        tv2_in_re[24] = 16'ha57e; tv2_in_re[25] = 16'h9d0e; tv2_in_re[26] = 16'h9592; tv2_in_re[27] = 16'h8f1d;
        tv2_in_re[28] = 16'h89be; tv2_in_re[29] = 16'h8583; tv2_in_re[30] = 16'h8276; tv2_in_re[31] = 16'h809e;
        tv2_in_re[32] = 16'h8000; tv2_in_re[33] = 16'h809e; tv2_in_re[34] = 16'h8276; tv2_in_re[35] = 16'h8583;
        tv2_in_re[36] = 16'h89be; tv2_in_re[37] = 16'h8f1d; tv2_in_re[38] = 16'h9592; tv2_in_re[39] = 16'h9d0e;
        tv2_in_re[40] = 16'ha57e; tv2_in_re[41] = 16'haecc; tv2_in_re[42] = 16'hb8e3; tv2_in_re[43] = 16'hc3a9;
        tv2_in_re[44] = 16'hcf04; tv2_in_re[45] = 16'hdad8; tv2_in_re[46] = 16'he707; tv2_in_re[47] = 16'hf374;
        tv2_in_re[48] = 16'h0000; tv2_in_re[49] = 16'h0c8c; tv2_in_re[50] = 16'h18f9; tv2_in_re[51] = 16'h2528;
        tv2_in_re[52] = 16'h30fc; tv2_in_re[53] = 16'h3c57; tv2_in_re[54] = 16'h471d; tv2_in_re[55] = 16'h5134;
        tv2_in_re[56] = 16'h5a82; tv2_in_re[57] = 16'h62f2; tv2_in_re[58] = 16'h6a6e; tv2_in_re[59] = 16'h70e3;
        tv2_in_re[60] = 16'h7642; tv2_in_re[61] = 16'h7a7d; tv2_in_re[62] = 16'h7d8a; tv2_in_re[63] = 16'h7f62;
        // Input im (sine)
        tv2_in_im[ 0] = 16'h0000; tv2_in_im[ 1] = 16'h0c8c; tv2_in_im[ 2] = 16'h18f9; tv2_in_im[ 3] = 16'h2528;
        tv2_in_im[ 4] = 16'h30fc; tv2_in_im[ 5] = 16'h3c57; tv2_in_im[ 6] = 16'h471d; tv2_in_im[ 7] = 16'h5134;
        tv2_in_im[ 8] = 16'h5a82; tv2_in_im[ 9] = 16'h62f2; tv2_in_im[10] = 16'h6a6e; tv2_in_im[11] = 16'h70e3;
        tv2_in_im[12] = 16'h7642; tv2_in_im[13] = 16'h7a7d; tv2_in_im[14] = 16'h7d8a; tv2_in_im[15] = 16'h7f62;
        tv2_in_im[16] = 16'h7fff; tv2_in_im[17] = 16'h7f62; tv2_in_im[18] = 16'h7d8a; tv2_in_im[19] = 16'h7a7d;
        tv2_in_im[20] = 16'h7642; tv2_in_im[21] = 16'h70e3; tv2_in_im[22] = 16'h6a6e; tv2_in_im[23] = 16'h62f2;
        tv2_in_im[24] = 16'h5a82; tv2_in_im[25] = 16'h5134; tv2_in_im[26] = 16'h471d; tv2_in_im[27] = 16'h3c57;
        tv2_in_im[28] = 16'h30fc; tv2_in_im[29] = 16'h2528; tv2_in_im[30] = 16'h18f9; tv2_in_im[31] = 16'h0c8c;
        tv2_in_im[32] = 16'h0000; tv2_in_im[33] = 16'hf374; tv2_in_im[34] = 16'he707; tv2_in_im[35] = 16'hdad8;
        tv2_in_im[36] = 16'hcf04; tv2_in_im[37] = 16'hc3a9; tv2_in_im[38] = 16'hb8e3; tv2_in_im[39] = 16'haecc;
        tv2_in_im[40] = 16'ha57e; tv2_in_im[41] = 16'h9d0e; tv2_in_im[42] = 16'h9592; tv2_in_im[43] = 16'h8f1d;
        tv2_in_im[44] = 16'h89be; tv2_in_im[45] = 16'h8583; tv2_in_im[46] = 16'h8276; tv2_in_im[47] = 16'h809e;
        tv2_in_im[48] = 16'h8000; tv2_in_im[49] = 16'h809e; tv2_in_im[50] = 16'h8276; tv2_in_im[51] = 16'h8583;
        tv2_in_im[52] = 16'h89be; tv2_in_im[53] = 16'h8f1d; tv2_in_im[54] = 16'h9592; tv2_in_im[55] = 16'h9d0e;
        tv2_in_im[56] = 16'ha57e; tv2_in_im[57] = 16'haecc; tv2_in_im[58] = 16'hb8e3; tv2_in_im[59] = 16'hc3a9;
        tv2_in_im[60] = 16'hcf04; tv2_in_im[61] = 16'hdad8; tv2_in_im[62] = 16'he707; tv2_in_im[63] = 16'hf374;
        // Expected re
        tv2_exp_re[ 0] = 16'hffff; tv2_exp_re[ 1] = 16'h7fff; tv2_exp_re[ 2] = 16'hffff; tv2_exp_re[ 3] = 16'h0000;
        tv2_exp_re[ 4] = 16'hffff; tv2_exp_re[ 5] = 16'hfffd; tv2_exp_re[ 6] = 16'hffff; tv2_exp_re[ 7] = 16'h0000;
        tv2_exp_re[ 8] = 16'hffff; tv2_exp_re[ 9] = 16'hfffa; tv2_exp_re[10] = 16'hffff; tv2_exp_re[11] = 16'h0000;
        tv2_exp_re[12] = 16'hffff; tv2_exp_re[13] = 16'h0009; tv2_exp_re[14] = 16'hffff; tv2_exp_re[15] = 16'h0000;
        tv2_exp_re[16] = 16'hffff; tv2_exp_re[17] = 16'h0000; tv2_exp_re[18] = 16'hffff; tv2_exp_re[19] = 16'h0000;
        tv2_exp_re[20] = 16'hffff; tv2_exp_re[21] = 16'h0005; tv2_exp_re[22] = 16'hffff; tv2_exp_re[23] = 16'h0000;
        tv2_exp_re[24] = 16'hffff; tv2_exp_re[25] = 16'hfff5; tv2_exp_re[26] = 16'hffff; tv2_exp_re[27] = 16'h0000;
        tv2_exp_re[28] = 16'hffff; tv2_exp_re[29] = 16'h0000; tv2_exp_re[30] = 16'hffff; tv2_exp_re[31] = 16'h0000;
        tv2_exp_re[32] = 16'hffff; tv2_exp_re[33] = 16'hfffd; tv2_exp_re[34] = 16'hffff; tv2_exp_re[35] = 16'h0000;
        tv2_exp_re[36] = 16'hffff; tv2_exp_re[37] = 16'h0000; tv2_exp_re[38] = 16'hffff; tv2_exp_re[39] = 16'h0000;
        tv2_exp_re[40] = 16'hffff; tv2_exp_re[41] = 16'hffff; tv2_exp_re[42] = 16'hffff; tv2_exp_re[43] = 16'h0000;
        tv2_exp_re[44] = 16'hffff; tv2_exp_re[45] = 16'h0001; tv2_exp_re[46] = 16'hffff; tv2_exp_re[47] = 16'h0000;
        tv2_exp_re[48] = 16'hffff; tv2_exp_re[49] = 16'hfffc; tv2_exp_re[50] = 16'hffff; tv2_exp_re[51] = 16'h0000;
        tv2_exp_re[52] = 16'hffff; tv2_exp_re[53] = 16'h0004; tv2_exp_re[54] = 16'hffff; tv2_exp_re[55] = 16'h0000;
        tv2_exp_re[56] = 16'hffff; tv2_exp_re[57] = 16'hfff3; tv2_exp_re[58] = 16'hffff; tv2_exp_re[59] = 16'h0000;
        tv2_exp_re[60] = 16'hffff; tv2_exp_re[61] = 16'hfff6; tv2_exp_re[62] = 16'hffff; tv2_exp_re[63] = 16'h0000;
        // Expected im
        tv2_exp_im[ 0] = 16'hffff; tv2_exp_im[ 1] = 16'h0000; tv2_exp_im[ 2] = 16'h0001; tv2_exp_im[ 3] = 16'h0000;
        tv2_exp_im[ 4] = 16'hffff; tv2_exp_im[ 5] = 16'h0000; tv2_exp_im[ 6] = 16'h0001; tv2_exp_im[ 7] = 16'h0000;
        tv2_exp_im[ 8] = 16'hffff; tv2_exp_im[ 9] = 16'h0000; tv2_exp_im[10] = 16'h0001; tv2_exp_im[11] = 16'h0000;
        tv2_exp_im[12] = 16'hffff; tv2_exp_im[13] = 16'h0000; tv2_exp_im[14] = 16'h0001; tv2_exp_im[15] = 16'h0000;
        tv2_exp_im[16] = 16'hffff; tv2_exp_im[17] = 16'h0000; tv2_exp_im[18] = 16'h0001; tv2_exp_im[19] = 16'h0000;
        tv2_exp_im[20] = 16'hffff; tv2_exp_im[21] = 16'h0000; tv2_exp_im[22] = 16'h0001; tv2_exp_im[23] = 16'h0000;
        tv2_exp_im[24] = 16'hffff; tv2_exp_im[25] = 16'h0000; tv2_exp_im[26] = 16'h0001; tv2_exp_im[27] = 16'h0000;
        tv2_exp_im[28] = 16'hffff; tv2_exp_im[29] = 16'h0000; tv2_exp_im[30] = 16'h0001; tv2_exp_im[31] = 16'h0000;
        tv2_exp_im[32] = 16'hffff; tv2_exp_im[33] = 16'h0000; tv2_exp_im[34] = 16'h0001; tv2_exp_im[35] = 16'h0000;
        tv2_exp_im[36] = 16'hffff; tv2_exp_im[37] = 16'h0000; tv2_exp_im[38] = 16'h0001; tv2_exp_im[39] = 16'h0000;
        tv2_exp_im[40] = 16'hffff; tv2_exp_im[41] = 16'h0000; tv2_exp_im[42] = 16'h0001; tv2_exp_im[43] = 16'h0000;
        tv2_exp_im[44] = 16'hffff; tv2_exp_im[45] = 16'h0000; tv2_exp_im[46] = 16'h0001; tv2_exp_im[47] = 16'h0000;
        tv2_exp_im[48] = 16'hffff; tv2_exp_im[49] = 16'h0000; tv2_exp_im[50] = 16'h0001; tv2_exp_im[51] = 16'h0000;
        tv2_exp_im[52] = 16'hffff; tv2_exp_im[53] = 16'h0000; tv2_exp_im[54] = 16'h0001; tv2_exp_im[55] = 16'h0000;
        tv2_exp_im[56] = 16'hffff; tv2_exp_im[57] = 16'h0000; tv2_exp_im[58] = 16'h0001; tv2_exp_im[59] = 16'h0000;
        tv2_exp_im[60] = 16'hffff; tv2_exp_im[61] = 16'h0000; tv2_exp_im[62] = 16'h0001; tv2_exp_im[63] = 16'h0000;
    end

    // --- Test vector 3: random_complex ---
    reg [15:0] tv3_in_re [0:63];
    reg [15:0] tv3_in_im [0:63];
    reg [15:0] tv3_exp_re [0:63];
    reg [15:0] tv3_exp_im [0:63];

    initial begin
        // Input re (pseudo-random)
        tv3_in_re[ 0] = 16'h2544; tv3_in_re[ 1] = 16'h2144; tv3_in_re[ 2] = 16'h1dd2; tv3_in_re[ 3] = 16'h31ba;
        tv3_in_re[ 4] = 16'h1b10; tv3_in_re[ 5] = 16'h0222; tv3_in_re[ 6] = 16'h1ab6; tv3_in_re[ 7] = 16'h33c2;
        tv3_in_re[ 8] = 16'h2730; tv3_in_re[ 9] = 16'h2dc0; tv3_in_re[10] = 16'h0baa; tv3_in_re[11] = 16'h2109;
        tv3_in_re[12] = 16'h23f7; tv3_in_re[13] = 16'h0fea; tv3_in_re[14] = 16'h3ada; tv3_in_re[15] = 16'h0718;
        tv3_in_re[16] = 16'h2a22; tv3_in_re[17] = 16'h1505; tv3_in_re[18] = 16'h0bdb; tv3_in_re[19] = 16'h2af1;
        tv3_in_re[20] = 16'h3acc; tv3_in_re[21] = 16'h086a; tv3_in_re[22] = 16'h1a47; tv3_in_re[23] = 16'h3658;
        tv3_in_re[24] = 16'h1a37; tv3_in_re[25] = 16'h0217; tv3_in_re[26] = 16'h243b; tv3_in_re[27] = 16'h3374;
        tv3_in_re[28] = 16'h097b; tv3_in_re[29] = 16'h39ca; tv3_in_re[30] = 16'h1eb8; tv3_in_re[31] = 16'h1cdd;
        tv3_in_re[32] = 16'h2d17; tv3_in_re[33] = 16'h3572; tv3_in_re[34] = 16'h31de; tv3_in_re[35] = 16'h27f9;
        tv3_in_re[36] = 16'h0e5c; tv3_in_re[37] = 16'h2909; tv3_in_re[38] = 16'h3b09; tv3_in_re[39] = 16'h0fc9;
        tv3_in_re[40] = 16'h05bc; tv3_in_re[41] = 16'h3dc7; tv3_in_re[42] = 16'h12d4; tv3_in_re[43] = 16'h060c;
        tv3_in_re[44] = 16'h3bf7; tv3_in_re[45] = 16'h16ba; tv3_in_re[46] = 16'h34f2; tv3_in_re[47] = 16'h10c4;
        tv3_in_re[48] = 16'h102b; tv3_in_re[49] = 16'h08bd; tv3_in_re[50] = 16'h07ed; tv3_in_re[51] = 16'h3a1f;
        tv3_in_re[52] = 16'h10c0; tv3_in_re[53] = 16'h1bc9; tv3_in_re[54] = 16'h22c8; tv3_in_re[55] = 16'h18bb;
        tv3_in_re[56] = 16'h1537; tv3_in_re[57] = 16'h0bb1; tv3_in_re[58] = 16'h0e77; tv3_in_re[59] = 16'h164c;
        tv3_in_re[60] = 16'h26d9; tv3_in_re[61] = 16'h1e34; tv3_in_re[62] = 16'h2141; tv3_in_re[63] = 16'h3aa3;
        // Input im (pseudo-random)
        tv3_in_im[ 0] = 16'h0643; tv3_in_im[ 1] = 16'h0476; tv3_in_im[ 2] = 16'h31fd; tv3_in_im[ 3] = 16'h2112;
        tv3_in_im[ 4] = 16'h3bd5; tv3_in_im[ 5] = 16'h1dd3; tv3_in_im[ 6] = 16'h012f; tv3_in_im[ 7] = 16'h1e34;
        tv3_in_im[ 8] = 16'h0100; tv3_in_im[ 9] = 16'h1216; tv3_in_im[10] = 16'h1609; tv3_in_im[11] = 16'h3c14;
        tv3_in_im[12] = 16'h3072; tv3_in_im[13] = 16'h1911; tv3_in_im[14] = 16'h2d43; tv3_in_im[15] = 16'h12af;
        tv3_in_im[16] = 16'h0b29; tv3_in_im[17] = 16'h2591; tv3_in_im[18] = 16'h37e1; tv3_in_im[19] = 16'h22de;
        tv3_in_im[20] = 16'h005d; tv3_in_im[21] = 16'h09b1; tv3_in_im[22] = 16'h07ca; tv3_in_im[23] = 16'h3999;
        tv3_in_im[24] = 16'h064d; tv3_in_im[25] = 16'h0a9a; tv3_in_im[26] = 16'h284b; tv3_in_im[27] = 16'h01a0;
        tv3_in_im[28] = 16'h31f1; tv3_in_im[29] = 16'h398b; tv3_in_im[30] = 16'h0072; tv3_in_im[31] = 16'h097e;
        tv3_in_im[32] = 16'h1b84; tv3_in_im[33] = 16'h085d; tv3_in_im[34] = 16'h3d4c; tv3_in_im[35] = 16'h23f1;
        tv3_in_im[36] = 16'h3df6; tv3_in_im[37] = 16'h2f4d; tv3_in_im[38] = 16'h2205; tv3_in_im[39] = 16'h28af;
        tv3_in_im[40] = 16'h1f37; tv3_in_im[41] = 16'h1a3b; tv3_in_im[42] = 16'h3be4; tv3_in_im[43] = 16'h3b8d;
        tv3_in_im[44] = 16'h2f65; tv3_in_im[45] = 16'h333b; tv3_in_im[46] = 16'h182a; tv3_in_im[47] = 16'h2004;
        tv3_in_im[48] = 16'h2cdb; tv3_in_im[49] = 16'h008d; tv3_in_im[50] = 16'h39d2; tv3_in_im[51] = 16'h3f18;
        tv3_in_im[52] = 16'h3b21; tv3_in_im[53] = 16'h2bf0; tv3_in_im[54] = 16'h2d29; tv3_in_im[55] = 16'h259c;
        tv3_in_im[56] = 16'h3ab5; tv3_in_im[57] = 16'h295e; tv3_in_im[58] = 16'h3754; tv3_in_im[59] = 16'h20da;
        tv3_in_im[60] = 16'h0fbd; tv3_in_im[61] = 16'h131b; tv3_in_im[62] = 16'h3fa7; tv3_in_im[63] = 16'h3f99;
        // Expected re
        tv3_exp_re[ 0] = 16'h7fff; tv3_exp_re[ 1] = 16'h8000; tv3_exp_re[ 2] = 16'h7fff; tv3_exp_re[ 3] = 16'h8000;
        tv3_exp_re[ 4] = 16'h6807; tv3_exp_re[ 5] = 16'h6980; tv3_exp_re[ 6] = 16'h7fff; tv3_exp_re[ 7] = 16'h1d26;
        tv3_exp_re[ 8] = 16'h4468; tv3_exp_re[ 9] = 16'hf029; tv3_exp_re[10] = 16'h8000; tv3_exp_re[11] = 16'h8000;
        tv3_exp_re[12] = 16'h8000; tv3_exp_re[13] = 16'h8000; tv3_exp_re[14] = 16'h3de5; tv3_exp_re[15] = 16'hc075;
        tv3_exp_re[16] = 16'h8000; tv3_exp_re[17] = 16'h2a4b; tv3_exp_re[18] = 16'h9e58; tv3_exp_re[19] = 16'h7fff;
        tv3_exp_re[20] = 16'h7fff; tv3_exp_re[21] = 16'h8000; tv3_exp_re[22] = 16'h5220; tv3_exp_re[23] = 16'h7fff;
        tv3_exp_re[24] = 16'h8000; tv3_exp_re[25] = 16'hdca1; tv3_exp_re[26] = 16'h8000; tv3_exp_re[27] = 16'h8000;
        tv3_exp_re[28] = 16'h27d8; tv3_exp_re[29] = 16'h7586; tv3_exp_re[30] = 16'h8000; tv3_exp_re[31] = 16'h7fff;
        tv3_exp_re[32] = 16'hf81e; tv3_exp_re[33] = 16'h877e; tv3_exp_re[34] = 16'h8000; tv3_exp_re[35] = 16'h2885;
        tv3_exp_re[36] = 16'h65da; tv3_exp_re[37] = 16'hd1fa; tv3_exp_re[38] = 16'h36d4; tv3_exp_re[39] = 16'hdc64;
        tv3_exp_re[40] = 16'h7fff; tv3_exp_re[41] = 16'h8000; tv3_exp_re[42] = 16'h7fff; tv3_exp_re[43] = 16'h8000;
        tv3_exp_re[44] = 16'h7ed8; tv3_exp_re[45] = 16'h7fff; tv3_exp_re[46] = 16'h8000; tv3_exp_re[47] = 16'h7fff;
        tv3_exp_re[48] = 16'h7fff; tv3_exp_re[49] = 16'h22fb; tv3_exp_re[50] = 16'h5e8b; tv3_exp_re[51] = 16'h7fff;
        tv3_exp_re[52] = 16'h9d6e; tv3_exp_re[53] = 16'h6cda; tv3_exp_re[54] = 16'h7fff; tv3_exp_re[55] = 16'h1da4;
        tv3_exp_re[56] = 16'h8000; tv3_exp_re[57] = 16'h7fff; tv3_exp_re[58] = 16'h320f; tv3_exp_re[59] = 16'h8f87;
        tv3_exp_re[60] = 16'h5121; tv3_exp_re[61] = 16'h7fff; tv3_exp_re[62] = 16'h6d03; tv3_exp_re[63] = 16'h7fff;
        // Expected im
        tv3_exp_im[ 0] = 16'h7fff; tv3_exp_im[ 1] = 16'hf5e3; tv3_exp_im[ 2] = 16'h8000; tv3_exp_im[ 3] = 16'hd337;
        tv3_exp_im[ 4] = 16'hf182; tv3_exp_im[ 5] = 16'h7fff; tv3_exp_im[ 6] = 16'h37e3; tv3_exp_im[ 7] = 16'h7fff;
        tv3_exp_im[ 8] = 16'h8000; tv3_exp_im[ 9] = 16'hf327; tv3_exp_im[10] = 16'h8000; tv3_exp_im[11] = 16'h7fff;
        tv3_exp_im[12] = 16'h8000; tv3_exp_im[13] = 16'h9e43; tv3_exp_im[14] = 16'hc2c1; tv3_exp_im[15] = 16'h7fff;
        tv3_exp_im[16] = 16'h1768; tv3_exp_im[17] = 16'he42e; tv3_exp_im[18] = 16'h36a4; tv3_exp_im[19] = 16'ha63a;
        tv3_exp_im[20] = 16'hfc3e; tv3_exp_im[21] = 16'h8000; tv3_exp_im[22] = 16'hf00c; tv3_exp_im[23] = 16'hf8de;
        tv3_exp_im[24] = 16'h8000; tv3_exp_im[25] = 16'ha08d; tv3_exp_im[26] = 16'h7fff; tv3_exp_im[27] = 16'h4a48;
        tv3_exp_im[28] = 16'h32f1; tv3_exp_im[29] = 16'h8000; tv3_exp_im[30] = 16'h55bd; tv3_exp_im[31] = 16'h1897;
        tv3_exp_im[32] = 16'h7024; tv3_exp_im[33] = 16'hd6b1; tv3_exp_im[34] = 16'h1a18; tv3_exp_im[35] = 16'h0b96;
        tv3_exp_im[36] = 16'h7fff; tv3_exp_im[37] = 16'h5368; tv3_exp_im[38] = 16'h8000; tv3_exp_im[39] = 16'hed0d;
        tv3_exp_im[40] = 16'h7fff; tv3_exp_im[41] = 16'hf750; tv3_exp_im[42] = 16'hb35e; tv3_exp_im[43] = 16'h8000;
        tv3_exp_im[44] = 16'hf582; tv3_exp_im[45] = 16'h8000; tv3_exp_im[46] = 16'h02ef; tv3_exp_im[47] = 16'h9650;
        tv3_exp_im[48] = 16'h8000; tv3_exp_im[49] = 16'h8000; tv3_exp_im[50] = 16'h2870; tv3_exp_im[51] = 16'h8000;
        tv3_exp_im[52] = 16'h991e; tv3_exp_im[53] = 16'h7958; tv3_exp_im[54] = 16'h6005; tv3_exp_im[55] = 16'h3d10;
        tv3_exp_im[56] = 16'h8000; tv3_exp_im[57] = 16'hde01; tv3_exp_im[58] = 16'h0189; tv3_exp_im[59] = 16'h49ce;
        tv3_exp_im[60] = 16'hfbc3; tv3_exp_im[61] = 16'hbedb; tv3_exp_im[62] = 16'h029d; tv3_exp_im[63] = 16'h7b2f;
    end

    // =========================================================================
    // Test sequence
    // =========================================================================
    initial begin
        $display("========================================");
        $display("FFT64 Radix-4 SDF Pipeline Testbench");
        $display("Pipeline latency: %0d cycles", PIPELINE_LATENCY);
        $display("Comparison tolerance: %0d LSB", TOL_LSB);
        $display("========================================");

        // --- Test 1: impulse_idx0 ---
        $display("\n--- Test 1: impulse_idx0 ---");
        apply_reset();
        drive_fft_inputs(tv0_in_re, tv0_in_im);
        capture_and_check(tv0_exp_re, tv0_exp_im, "impulse_idx0");

        // --- Test 2: constant_dc ---
        $display("\n--- Test 2: constant_dc ---");
        apply_reset();
        drive_fft_inputs(tv1_in_re, tv1_in_im);
        capture_and_check(tv1_exp_re, tv1_exp_im, "constant_dc");

        // --- Test 3: single_freq_k1 ---
        $display("\n--- Test 3: single_freq_k1 ---");
        apply_reset();
        drive_fft_inputs(tv2_in_re, tv2_in_im);
        capture_and_check(tv2_exp_re, tv2_exp_im, "single_freq_k1");

        // --- Test 4: random_complex ---
        $display("\n--- Test 4: random_complex ---");
        apply_reset();
        drive_fft_inputs(tv3_in_re, tv3_in_im);
        capture_and_check(tv3_exp_re, tv3_exp_im, "random_complex");

        // --- Summary ---
        $display("\n========================================");
        if (fail_count == 0)
            $display("ALL TESTS PASSED (%0d test vectors)", test_pass_count);
        else
            $display("FAILED: %0d sample(s) failed across all test vectors", fail_count);
        $display("========================================");
        $finish;
    end

endmodule
