"""cocotb integration testbench for fft64_radix4_sdf -- golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (out_valid, out_data_re, etc.) have a pipeline delay:
  they reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.

Verification approach:
  The FFT64 is a continuous-streaming pipeline design. The golden model's
  `compute()` produces the final 64-point FFT output (digit-reversed order),
  not per-cycle port values. The testbench:
  1. Drives all 64 input samples with in_valid=1 (1 sample/clock)
  2. Waits for pipeline latency (67 cycles) + 64 output cycles
  3. Captures all 64 outputs when out_valid=1
  4. Compares against golden_model output with Q1.15 quantization tolerance
  5. Reports SQNR and max error per test vector

Port configuration constants below are populated from spec.json by the codegen
stage. If codegen does not populate them, defaults are used and only
top-level port signals are checked.
"""

import os, sys, math
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 10  # 100 MHz -> 10 ns full period
RESET_CYCLE_SKIP = 1  # Golden cycle 0 is the reset state; comparison starts at cycle 1
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0  # Accumulates across ALL tests; do NOT reset inside individual tests
_STIMULUS_DELIVERED = False  # Set True by drive_fft_inputs(); checked by comparison tests

# FFT-specific constants
N = 64                       # FFT size
PIPELINE_LATENCY = 67        # cycles from first in_valid to first out_valid
DATA_W = 16                  # Q1.15 width
FRAC_BITS = 15               # fractional bits in Q1.15
SCALE = 1 << FRAC_BITS       # 32768
SIGN_BIT = 1 << (DATA_W - 1)
MAX_ERROR_THRESHOLD = 0.005  # Q1.15 tolerance: max error in normalized float
SQNR_MIN_DB = 40.0           # minimum acceptable SQNR in dB

# --- Golden model import ---
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import (
            compute as golden_compute,
            run as golden_run,
            get_test_vectors as golden_get_test_vectors,
            q115_to_float,
            to_signed,
        )
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# --- Port configuration (populated from spec.json by codegen) ---
INPUT_PORTS = {
    "in_valid":   1,
    "in_data_re": 16,
    "in_data_im": 16,
}
OUTPUT_PORTS = {
    "out_valid":   1,
    "out_data_re": 16,
    "out_data_im": 16,
    "out_index":   6,
}
VALID_OUTPUT_PORTS = ["out_valid"]
HANDSHAKE_PORTS = {}       # No ready/ack -- streaming design
HOLD_UNTIL_ACK_PORTS = []  # No hold_until_ack ports

# DRIVE_PHASE_CYCLES: pipeline latency from spec.json timing_convention
DRIVE_PHASE_CYCLES = 67    # from spec timing_convention.golden_to_rtl_offset_cycles

# Fallback: if codegen didn't set DRIVE_PHASE_CYCLES, try reading spec.json
if DRIVE_PHASE_CYCLES == 0:
    try:
        _spec_path = Path(__file__).parent.parent / "docs" / "spec.json"
        if _spec_path.exists():
            import json as _json
            _spec = _json.loads(_spec_path.read_text())
            _tc = _spec.get("timing_convention", {})
            _offset = _tc.get("golden_to_rtl_offset_cycles")
            if isinstance(_offset, int) and _offset > 0:
                DRIVE_PHASE_CYCLES = _offset
            else:
                _delays = []
                for _m in _spec.get("modules", []):
                    _d = _m.get("timing_contract", {}).get("pipeline_delay_cycles")
                    if isinstance(_d, (int, float)):
                        _delays.append(int(_d))
                if _delays:
                    DRIVE_PHASE_CYCLES = max(_delays)
    except Exception:
        pass


# --- Divergence collection ---
MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _record_divergence(divergences, sig_name, expected_val, actual_val,
                       cycle_idx, width, kind=None):
    """Append a divergence dict to `divergences`.

    Returns True when the caller should stop collecting (cap reached or
    fail-fast mode).
    """
    div = {
        "cycle": cycle_idx,
        "signal": sig_name,
        "expected": expected_val,
        "actual": actual_val,
        "width": width,
    }
    if kind:
        div["kind"] = kind
    divergences.append(div)
    return FAIL_FAST or len(divergences) >= MAX_COLLECTED_DIVERGENCES


def _format_divergence_block(div, tag):
    """Format one divergence as a [tag] FIRST DIVERGENCE-shaped block."""
    width = div.get("width") or 16
    hex_digits = max((width + 3) // 4, 1)
    kind = div.get("kind")
    kind_tag = f" kind={kind}" if kind else ""
    hint = (
        "\n  (testbench driver wrong -- DUT input doesn't match golden stimulus)"
        if kind == "stimulus_mismatch" else ""
    )
    return (
        f"[{tag}] FIRST DIVERGENCE at cycle={div['cycle']} "
        f"signal={div['signal']} (width={width}b){kind_tag}:\n"
        f"  expected = 0x{div['expected']:0{hex_digits}x}\n"
        f"  actual   = 0x{div['actual']:0{hex_digits}x}\n"
        f"  xor diff = 0x{div['expected'] ^ div['actual']:0{hex_digits}x}"
        f"{hint}"
    )


def _finalize_divergences(dut, divergences, tag):
    """Emit each divergence and raise AssertionError with a summary."""
    blocks = [_format_divergence_block(d, d) for d in divergences]
    for b in blocks:
        dut._log.error(b)
    head = blocks[0]
    if len(blocks) > 1:
        more = "\n\n".join(blocks[1:])
        msg = (
            f"{head}\n\n"
            f"(+{len(blocks) - 1} additional divergence(s) collected; "
            f"set COCOTB_FAIL_FAST=1 to stop at the first):\n\n{more}"
        )
    else:
        msg = head
    raise AssertionError(msg)


# --- Clock management ---
async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    assert CLK_PERIOD_NS is not None, (
        "CLK_PERIOD_NS not populated -- codegen must set from spec.timing.target_frequency_mhz"
    )
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# --- Helpers ---

def _lookup_signal_width(sig_name, default=16):
    """Best-effort width lookup from spec-populated port dicts."""
    seen = {sig_name}
    candidates = [sig_name]
    cursor = 0
    while cursor < len(candidates):
        n = candidates[cursor]
        cursor += 1
        for stripped in (
            n.rsplit(".", 1)[-1] if "." in n else "",
            n[:-4] if n.endswith("_reg") else "",
            n.split("[", 1)[0] if "[" in n else "",
        ):
            if stripped and stripped not in seen:
                seen.add(stripped)
                candidates.append(stripped)

    for name in candidates:
        if name in OUTPUT_PORTS:
            return OUTPUT_PORTS[name]
    for name in candidates:
        if name in INPUT_PORTS:
            return INPUT_PORTS[name]
    return default


async def reset_dut(dut):
    """Apply async active-low reset and wait for outputs to settle."""
    global FAIL_COUNT
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = False

    # Async active-low reset
    dut.rst_n.value = 0
    # Zero all input ports
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)  # rst_n deassert sampled, outputs stable


async def drive_fft_inputs(dut, samples_re, samples_im):
    """Drive 64 input samples with in_valid=1, continuous streaming.

    Timing:
    1. Drive in_valid=1 and first sample
    2. Each RisingEdge: advance to next sample
    3. After all 64 samples, deassert in_valid

    After this function returns, the DUT pipeline is full and will produce
    64 output samples starting PIPELINE_LATENCY cycles after the first
    in_valid was asserted.

    Args:
        dut: cocotb DUT handle
        samples_re: list of 64 Q1.15 unsigned values for real part
        samples_im: list of 64 Q1.15 unsigned values for imaginary part
    """
    global _STIMULUS_DELIVERED

    assert len(samples_re) == N and len(samples_im) == N, (
        f"Expected {N} samples, got re={len(samples_re)} im={len(samples_im)}"
    )

    dut.in_valid.value = 0
    dut.in_data_re.value = 0
    dut.in_data_im.value = 0
    await RisingEdge(dut.clk)

    # Drive all 64 samples with in_valid=1
    for i in range(N):
        dut.in_valid.value = 1
        dut.in_data_re.value = int(samples_re[i])
        dut.in_data_im.value = int(samples_im[i])
        await RisingEdge(dut.clk)

    # Deassert in_valid after all samples driven
    dut.in_valid.value = 0
    dut.in_data_re.value = 0
    dut.in_data_im.value = 0

    _STIMULUS_DELIVERED = True


async def capture_fft_outputs(dut, max_wait_cycles=300):
    """Capture all 64 FFT output samples when out_valid=1.

    Waits for PIPELINE_LATENCY cycles first (pipeline filling), then
    captures up to 64 samples with out_valid=1.

    Returns:
        list of dicts with keys: re, im, index (all integers, unsigned Q1.15)
    """
    outputs = []

    # Wait for pipeline latency + margin
    for _ in range(PIPELINE_LATENCY):
        await RisingEdge(dut.clk)

    # Wait for additional cycles and capture outputs
    for _ in range(max_wait_cycles):
        await RisingEdge(dut.clk)
        if int(dut.out_valid.value) == 1:
            re_val = int(dut.out_data_re.value)
            im_val = int(dut.out_data_im.value)
            idx_val = int(dut.out_index.value)
            outputs.append({"re": re_val, "im": im_val, "index": idx_val})
            if len(outputs) >= N:
                break

    return outputs


def compare_fft_results(dut, actual_outputs, expected_re, expected_im, test_name):
    """Compare captured FFT outputs against golden model expected values.

    Reports per-sample errors, max error, SQNR, and PASS/FAIL.

    Args:
        dut: cocotb DUT handle (for logging)
        actual_outputs: list of dicts from capture_fft_outputs
        expected_re: list of 64 expected Q1.15 unsigned real values
        expected_im: list of 64 expected Q1.15 unsigned imaginary values
        test_name: string name for log messages

    Returns:
        True if all samples within tolerance, False otherwise
    """
    global FAIL_COUNT

    if len(actual_outputs) < N:
        dut._log.error(
            f"[{test_name}] Only captured {len(actual_outputs)}/{N} output samples"
        )
        FAIL_COUNT += 1
        return False

    divergences = []
    total_sq_err = 0.0
    total_sq_sig = 0.0
    max_err = 0.0
    max_err_idx = -1

    for i in range(N):
        out = actual_outputs[i]
        actual_re_float = q115_to_float(out["re"])
        actual_im_float = q115_to_float(out["im"])
        expected_re_float = q115_to_float(expected_re[i])
        expected_im_float = q115_to_float(expected_im[i])

        err_re = abs(actual_re_float - expected_re_float)
        err_im = abs(actual_im_float - expected_im_float)
        err = max(err_re, err_im)

        total_sq_err += err_re ** 2 + err_im ** 2
        total_sq_sig += expected_re_float ** 2 + expected_im_float ** 2

        if err > max_err:
            max_err = err
            max_err_idx = i

        # Record sample-level divergence if error exceeds threshold
        if err > MAX_ERROR_THRESHOLD:
            if _record_divergence(
                divergences,
                f"out_sample[{i}]",
                (expected_re[i] << 16) | expected_im[i],  # combined for hex display
                (out["re"] << 16) | out["im"],
                i,
                32,  # combined width
            ):
                break

    # Compute SQNR
    if total_sq_err > 0:
        sqnr_db = 10.0 * math.log10(total_sq_sig / total_sq_err)
    else:
        sqnr_db = float('inf')

    # Log per-sample details for the worst sample
    if max_err_idx >= 0:
        out = actual_outputs[max_err_idx]
        dut._log.info(
            f"[{test_name}] Worst sample[{max_err_idx}]: "
            f"expected_re={q115_to_float(expected_re[max_err_idx]):.6f} "
            f"actual_re={q115_to_float(out['re']):.6f} | "
            f"expected_im={q115_to_float(expected_im[max_err_idx]):.6f} "
            f"actual_im={q115_to_float(out['im']):.6f} | "
            f"max_err={max_err:.6f}"
        )

    # Determine pass/fail
    passed = max_err <= MAX_ERROR_THRESHOLD and sqnr_db >= SQNR_MIN_DB
    status = "PASS" if passed else "FAIL"

    dut._log.info(
        f"[{status}] {test_name}: max_err={max_err:.6f}, SQNR={sqnr_db:.1f}dB, "
        f"samples={len(actual_outputs)}/{N}"
    )

    if not passed:
        FAIL_COUNT += 1
        # Log detailed divergences
        for div in divergences[:MAX_COLLECTED_DIVERGENCES]:
            idx = div["cycle"]
            out = actual_outputs[idx]
            dut._log.error(
                f"[{test_name}] sample[{idx}] index={out['index']}: "
                f"expected_re=0x{expected_re[idx]:04x} actual_re=0x{out['re']:04x} | "
                f"expected_im=0x{expected_im[idx]:04x} actual_im=0x{out['im']:04x}"
            )

    return passed


# --- Tests ---

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior -- outputs quiescent after async active-low reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: verify all output ports are 0
    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance -- valid handshake behavior.

    Checks:
    1. Reset clears out_valid
    2. After driving 64 samples, out_valid eventually asserts
    3. out_valid is high for exactly 64 consecutive cycles
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check 1: After reset, out_valid must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_protocol: golden_model.py not available")
        return

    # Drive impulse test vector for protocol check
    tv = golden_get_test_vectors()[0]  # impulse_idx0
    samples_re = tv["inputs"]["samples_re"]
    samples_im = tv["inputs"]["samples_im"]

    await drive_fft_inputs(dut, samples_re, samples_im)

    # Wait for pipeline latency
    for _ in range(PIPELINE_LATENCY):
        await RisingEdge(dut.clk)

    # Check 2: out_valid should assert after pipeline latency
    valid_count = 0
    for _ in range(N + 20):
        await RisingEdge(dut.clk)
        if int(dut.out_valid.value) == 1:
            valid_count += 1

    if valid_count < N:
        dut._log.error(
            f"[PROTOCOL] Only {valid_count}/{N} valid outputs after pipeline latency"
        )
        FAIL_COUNT += 1
    else:
        dut._log.info(
            f"[PASS] protocol: {valid_count} valid outputs captured"
        )

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification -- golden model output comparison.

    For the FFT streaming pipeline design:
    1. Drive all 64 input samples from each golden model test vector
    2. Wait for pipeline latency
    3. Capture all 64 output samples
    4. Compare against golden_model.compute() expected output
    5. Report SQNR and max error per test vector

    Skipped if golden_model.py is not available.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)

    test_vectors = golden_get_test_vectors()
    dut._log.info(f"[LAYERED] Running {len(test_vectors)} test vectors")

    for vec_idx, tv in enumerate(test_vectors):
        test_name = f"layered_{tv['name']}"

        # Reset before each test vector
        await reset_dut(dut)

        # Get expected output from golden model
        expected = golden_compute(tv["inputs"], trace=False)
        expected_re = expected["samples_re"]
        expected_im = expected["samples_im"]

        # Drive input samples
        samples_re = tv["inputs"]["samples_re"]
        samples_im = tv["inputs"]["samples_im"]
        await drive_fft_inputs(dut, samples_re, samples_im)

        # Capture outputs
        actual_outputs = await capture_fft_outputs(dut)

        # Compare
        compare_fft_results(
            dut, actual_outputs,
            expected_re, expected_im,
            test_name,
        )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    For the FFT design, the golden model trace reports pipeline stage
    completions but does not provide per-cycle internal register values.
    This test verifies:
    1. Pipeline stage progression by checking out_valid timing
    2. Output index sequence follows radix-4 digit-reversed order
    3. Output data stability between posedge and negedge (timing contract)

    Skipped if golden_model.py is not available.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)

    # Use impulse test vector for detailed analysis
    tv = golden_get_test_vectors()[0]
    await reset_dut(dut)

    samples_re = tv["inputs"]["samples_re"]
    samples_im = tv["inputs"]["samples_im"]
    await drive_fft_inputs(dut, samples_re, samples_im)

    # --- Timing contract check ---
    # Verify out_valid first assertion at cycle T+67 (within +/- 1 cycle tolerance)
    dut._log.info("[INTERNAL] Checking pipeline latency timing")
    found_valid = False
    first_valid_cycle = 0
    for cyc in range(PIPELINE_LATENCY + 20):
        await RisingEdge(dut.clk)
        if int(dut.out_valid.value) == 1:
            if not found_valid:
                first_valid_cycle = cyc
                found_valid = True
                break

    if not found_valid:
        dut._log.error(
            f"[INTERNAL] out_valid never asserted within "
            f"{PIPELINE_LATENCY + 20} cycles of stimulus"
        )
        FAIL_COUNT += 1
        return

    latency_offset = abs(first_valid_cycle - PIPELINE_LATENCY)
    if latency_offset > 2:
        dut._log.warning(
            f"[INTERNAL] Pipeline latency offset={latency_offset} cycles "
            f"(expected ~{PIPELINE_LATENCY}, got {first_valid_cycle})"
        )
    else:
        dut._log.info(
            f"[INTERNAL] Pipeline latency: first out_valid at cycle {first_valid_cycle} "
            f"(expected ~{PIPELINE_LATENCY}, delta={latency_offset})"
        )

    # --- Registered output stability check ---
    # Verify out_data_re/im don't change between posedge and negedge when out_valid=1
    dut._log.info("[INTERNAL] Checking registered output stability")
    violations = []

    # Reset and re-drive for stability check
    await reset_dut(dut)
    await drive_fft_inputs(dut, samples_re, samples_im)

    for _ in range(PIPELINE_LATENCY):
        await RisingEdge(dut.clk)

    for cyc in range(N + 10):
        await RisingEdge(dut.clk)
        if int(dut.out_valid.value) == 1:
            posedge_re = int(dut.out_data_re.value)
            posedge_im = int(dut.out_data_im.value)
            posedge_idx = int(dut.out_index.value)

            await FallingEdge(dut.clk)
            negedge_re = int(dut.out_data_re.value)
            negedge_im = int(dut.out_data_im.value)
            negedge_idx = int(dut.out_index.value)

            if posedge_re != negedge_re:
                violations.append(
                    f"cycle={cyc} out_data_re: posedge={posedge_re} negedge={negedge_re}"
                )
            if posedge_im != negedge_im:
                violations.append(
                    f"cycle={cyc} out_data_im: posedge={posedge_im} negedge={negedge_im}"
                )
            if posedge_idx != negedge_idx:
                violations.append(
                    f"cycle={cyc} out_index: posedge={posedge_idx} negedge={negedge_idx}"
                )

            if len(violations) >= MAX_COLLECTED_DIVERGENCES:
                break

    if violations:
        dut._log.error(
            f"[INTERNAL] {len(violations)} registered output stability violation(s):"
        )
        for v in violations[:5]:
            dut._log.error(f"  {v}")
        FAIL_COUNT += len(violations)
    else:
        dut._log.info("[INTERNAL] PASS -- registered output stability verified")

    # Stimulus sanity check
    if INPUT_PORTS and not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_internal_signals: drive_fft_inputs() was never called "
            "(no stimulus delivered)"
        )

    if not violations:
        dut._log.info("[INTERNAL] PASS -- internal signal checks passed")


@cocotb.test()
async def test_timing_contract(dut):
    """Test 5: Verify timing contract invariants at runtime.

    Checks:
    1. Registered outputs (out_valid, out_data_re, out_data_im, out_index)
       are stable between posedge and negedge -- they must be NBA-driven.
    2. Pipeline delay from first in_valid to first out_valid matches
       spec.json timing_contract.pipeline_delay_cycles (67 cycles).
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_timing_contract: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Drive impulse vector for timing measurement
    tv = golden_get_test_vectors()[0]
    await drive_fft_inputs(dut, tv["inputs"]["samples_re"], tv["inputs"]["samples_im"])

    REGISTERED_OUTPUTS = ["out_valid", "out_data_re", "out_data_im", "out_index"]
    PIPELINE_DELAY_CYCLES = 67

    violations = []
    first_in_valid_cycle = None
    first_out_valid_cycle = None
    cycle = 0

    for cycle in range(PIPELINE_DELAY_CYCLES + N + 20):
        await RisingEdge(dut.clk)
        cycle += 1

        # Track first in_valid assertion (already driven by drive_fft_inputs,
        # but check from this test's perspective)
        in_v = int(dut.in_valid.value)
        if in_v == 1 and first_in_valid_cycle is None:
            first_in_valid_cycle = cycle

        # Track first out_valid assertion
        out_v = int(dut.out_valid.value)
        if out_v == 1 and first_out_valid_cycle is None:
            first_out_valid_cycle = cycle

            # Measure pipeline latency
            if first_in_valid_cycle is not None:
                measured_latency = first_out_valid_cycle - first_in_valid_cycle
                if abs(measured_latency - PIPELINE_DELAY_CYCLES) > 2:
                    violations.append(
                        f"Pipeline latency: measured={measured_latency} "
                        f"expected={PIPELINE_DELAY_CYCLES} "
                        f"delta={abs(measured_latency - PIPELINE_DELAY_CYCLES)}"
                    )

        # Registered output stability check when out_valid is high
        if out_v == 1:
            for port_name in REGISTERED_OUTPUTS:
                try:
                    sig = getattr(dut, port_name)
                    posedge_val = int(sig.value)
                    await FallingEdge(dut.clk)
                    negedge_val = int(sig.value)
                    if posedge_val != negedge_val:
                        violations.append(
                            f"cycle={cycle} {port_name}: changed between "
                            f"posedge ({posedge_val}) and negedge ({negedge_val}) "
                            f"-- registered output must be stable"
                        )
                    await RisingEdge(dut.clk)
                    # Note: we advanced one extra cycle for the FallingEdge/RisingEdge
                    # This is acceptable for a sampling-based check
                    break  # only check first few valid outputs
                except AttributeError:
                    pass
            if violations:
                break  # fail-fast on first timing violation

        if first_out_valid_cycle is not None and cycle > first_out_valid_cycle + N:
            break

    if violations:
        dut._log.error(f"[TIMING CONTRACT] {len(violations)} violation(s):")
        for v in violations[:5]:
            dut._log.error(f"  {v}")
        FAIL_COUNT += 1
        raise AssertionError(
            f"Timing contract violated: {violations[0]}"
        )
    else:
        dut._log.info("[TIMING CONTRACT] PASS -- all invariants hold")


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    MUST be the last test defined in this file -- cocotb runs tests in
    definition order. This test reads the accumulated FAIL_COUNT.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
