// Auto-generated by VeriFlow DSL from module shift_register
`resetall
`timescale 1ns / 1ps
`default_nettype none

module shift_register
(
    input  wire         clk,
    input  wire         rst,
    output wire [7:0] shift_reg,
    input  wire shift_en,
    input  wire data_in
);

reg [7:0] shift_reg_reg = 8'd0;

// Sequential logic (register update)
always @(posedge clk) begin
    shift_reg_reg <= (shift_en ? {data_in, shift_reg_reg[6:0]} : shift_reg_reg);
    if (rst) begin
        shift_reg_reg <= 8'd0;
    end
end

// Output wire assignments
assign shift_reg = shift_reg_reg;

endmodule

`resetall