"""cocotb integration testbench for <design_name> — golden model cross-check.
Generated by VeriFlow-CC Stage 3.

Uses await RisingEdge(dut.clk) which fires AFTER NBA region completes.
No @(negedge clk) workarounds needed — registered outputs are always
stable when the coroutine resumes.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 5   # 200 MHz default (half-period = 2.5 ns)
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0

# ─── Golden model import (if available) ─────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# ─── Helpers ────────────────────────────────────────────────────────────

async def reset_dut(dut):
    """Apply synchronous reset and verify quiescent outputs."""
    dut.rst.value = 1
    # Set all input ports to 0 during reset
    for name in [p for p in dir(dut) if not p.startswith('_') and p not in ('clk','rst')]:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst.value = 0
    await RisingEdge(dut.clk)  # rst deassert sampled, outputs stable

def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle (e.g., dut.data_out)."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:08x} got=0x{actual:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)

def check_dut(dut, expected, signal, test_name, cycle):
    """Convenience: check_dut(dut, 0x1234, dut.data_out, 'test1', 5)."""
    check(dut, expected, signal, test_name, cycle)

# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent, ready=1 after reset."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await reset_dut(dut)
    # After reset: await RisingEdge for post-NBA stable values
    # Example: assert dut.ready.value == 1, "ready not asserted after reset"
    dut._log.info("PASS — reset behavior correct")

# ─── Cycle-accurate test pattern ────────────────────────────────────────
# Each test follows this cycle pattern:
#
#   # Drive inputs
#   dut.data_in.value = 0xDEADBEEF
#   await RisingEdge(dut.clk)    # DUT samples inputs, NBA applies
#   # Outputs are NOW stable — check immediately after RisingEdge returns
#   check_dut(dut, 0xEXPECTED, dut.data_out, 'test_name', cycle)
#
# Key insight: RisingEdge returns AFTER the NBA region. No delay needed.
# This is the fundamental advantage of cocotb over Verilog testbenches.
#
# For multi-cycle operations:
#   for cycle in range(N):
#       await RisingEdge(dut.clk)         # posedge + NBA
#       check_dut(dut, expected[cycle], dut.data_out, 'test', cycle)

# Additional per-scenario tests are generated from timing_model.yaml scenarios.
# Each scenario maps to an @cocotb.test() coroutine that:
#  1. Calls reset_dut(dut)
#  2. Drives input stimulus cycle-by-cycle per the scenario's stimulus table
#  3. Awaits RisingEdge(dut.clk) after each input change
#  4. Checks expected values from golden model or spec.json

@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)
    global FAIL_COUNT
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
