"""cocotb integration testbench for <design_name> — golden model cross-check.
Generated by VeriFlow-CC.

Uses VPI-safe timing: feed_block() waits 2 RisingEdges after driving inputs
to ensure iverilog VPI propagation completes before DUT samples.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 5   # 200 MHz default
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0

# ─── Golden model import ────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# ─── Test vector constants ──────────────────────────────────────────────
# These are populated from golden_model.py constants by the codegen stage.
# Example:
# TEST_VECTOR_1_INPUT = 0x...
# TEST_VECTOR_1_EXPECTED = 0x...

# ─── Helpers ────────────────────────────────────────────────────────────

async def reset_dut(dut):
    """Apply synchronous reset and verify quiescent outputs."""
    global FAIL_COUNT
    dut.rst.value = 1
    dut.msg_valid.value = 0
    # Zero all other input ports
    for name in [p for p in dir(dut) if not p.startswith('_') and p not in ('clk', 'rst')]:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst.value = 0
    await RisingEdge(dut.clk)  # rst deassert sampled, outputs stable


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:08x} got=0x{actual:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


def check_wide(dut, expected, signal, test_name, cycle, width=256):
    """Check wide signals (256-bit hash etc)."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{width // 4}x} got=0x{actual:0{width // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


async def feed_block(dut, msg_block_val, is_last_val, msg_valid_name='msg_valid',
                     msg_block_name='msg_block', is_last_name='is_last',
                     ready_name='ready'):
    """Wait for ready, then drive msg_valid=1 with msg_block and is_last.

    Uses VPI-safe 2-RisingEdge timing:
    1. Wait for ready=1
    2. Drive ALL inputs simultaneously (msg_valid, is_last, msg_block)
    3. Wait TWO RisingEdges — first for VPI propagation, second for DUT sampling
    4. Deassert inputs

    This pattern is required because cocotb + iverilog VPI can delay
    wide signal (512-bit) writes. The 2-edge wait ensures the DUT
    sees all inputs correctly before we deassert.
    """
    # Wait for ready
    timeout = TIMEOUT_CYCLES
    ready_sig = getattr(dut, ready_name)
    while int(ready_sig.value) != 1 and timeout > 0:
        await RisingEdge(dut.clk)
        timeout -= 1
    assert timeout > 0, "Timeout waiting for ready before feed_block"

    # Drive all inputs at once
    getattr(dut, is_last_name).value = is_last_val
    getattr(dut, msg_block_name).value = msg_block_val
    getattr(dut, msg_valid_name).value = 1

    # Wait two rising edges — first for VPI propagation, second for DUT sampling
    await RisingEdge(dut.clk)
    await RisingEdge(dut.clk)

    # Deassert after DUT has sampled
    getattr(dut, msg_valid_name).value = 0
    getattr(dut, is_last_name).value = 0
    getattr(dut, msg_block_name).value = 0


async def wait_valid(dut, valid_name='hash_valid', max_cycles=200):
    """Poll for valid=1, return cycle count waited."""
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1  # timeout


# ─── Tests ──────────────────────────────────────────────────────────────
# The codegen stage generates specific tests based on golden_model.py
# test vectors. Common test patterns:

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent, ready=1 after reset."""
    global FAIL_COUNT
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await reset_dut(dut)

    # After reset: ready=1, valid=0
    assert int(dut.ready.value) == 1, "ready not asserted after reset"
    assert int(dut.hash_valid.value) == 0, "hash_valid not 0 after reset"
    dut._log.info("[PASS] reset behavior correct")


# Additional tests generated from golden_model.py vectors follow.
# Each test uses feed_block() and wait_valid() with the VPI-safe pattern.


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    global FAIL_COUNT
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
