// Auto-generated by VeriFlow DSL from module fsm_4state
`resetall
`timescale 1ns / 1ps
`default_nettype none

module fsm_4state
(
    input  wire         clk,
    input  wire         rst,
    output wire [1:0] state_reg,
    output wire load_en,
    output wire process_en,
    output wire done_out,
    input  wire start,
    input  wire done_signal
);

reg [1:0] state_reg_reg = 2'd0;
reg [0:0] load_en_reg = 1'd0;
reg [0:0] process_en_reg = 1'd0;
reg [0:0] done_out_reg = 1'd0;

// Sequential logic (register update)
always @(posedge clk) begin
    state_reg_reg <= ((state_reg_reg == 1'd0) ? (start ? 1'd1 : 1'd0) : ((state_reg_reg == 1'd1) ? 1'd1 : ((state_reg_reg == 2'd2) ? (done_signal ? 2'd3 : 2'd2) : 2'd3)));
    load_en_reg <= (state_reg_reg == 1'd1);
    process_en_reg <= (state_reg_reg == 2'd2);
    done_out_reg <= (state_reg_reg == 2'd3);
    if (rst) begin
        state_reg_reg <= 2'd0;
        load_en_reg <= 1'd0;
        process_en_reg <= 1'd0;
        done_out_reg <= 1'd0;
    end
end

// Output wire assignments
assign state_reg = state_reg_reg;
assign load_en = load_en_reg;
assign process_en = process_en_reg;
assign done_out = done_out_reg;

endmodule

`resetall