// Auto-generated by VeriFlow DSL from module handshake_single_cycle
`resetall
`timescale 1ns / 1ps
`default_nettype none

module handshake_single_cycle
(
    input  wire         clk,
    input  wire         rst,
    output wire sent_reg,
    output wire valid_reg,
    output wire last_reg,
    input  wire trigger
);

reg [0:0] sent_reg_reg = 1'd0;
reg [0:0] valid_reg_reg = 1'd0;
reg [0:0] last_reg_reg = 1'd0;

// Sequential logic (register update)
always @(posedge clk) begin
    if (rst) begin
        sent_reg_reg <= 1'd0;
        valid_reg_reg <= 1'd0;
        last_reg_reg <= 1'd0;
    end else begin
        sent_reg_reg <= (trigger & (~sent_reg_reg));
        valid_reg_reg <= (trigger & (~sent_reg_reg));
        last_reg_reg <= (trigger & (~sent_reg_reg));
    end
end

// Output wire assignments
assign sent_reg = sent_reg_reg;
assign valid_reg = valid_reg_reg;
assign last_reg = last_reg_reg;

endmodule

`resetall