// tb_sha256_core.v -- integration test for sha256_core
// Generated by VeriFlow-CC.
//
// Self-checking Verilog testbench with pre-computed expected values
// from golden_model.py. Zero Python dependencies.
//
// Test vectors:
//   1. empty_string -- SHA-256("") = e3b0c442...
//   2. abc          -- SHA-256("abc") = ba7816bf...
//
// Timing: 100 MHz clock (10 ns period, 5 ns half-period).
// Reset: async active-low (reset_n).

`timescale 1ns / 1ps

module tb_sha256_core;

    // ─── DUT ports ──────────────────────────────────────────────────────
    reg         clk;
    reg         reset_n;
    reg         init;
    reg         next;
    reg  [511:0] block;
    wire        ready;
    wire        digest_valid;
    wire [255:0] digest;

    // ─── Cycle counter and fail counter ─────────────────────────────────
    integer cycle_count = 0;
    integer fail_count  = 0;

    // ─── DUT instantiation ──────────────────────────────────────────────
    sha256_core uut (
        .clk(clk),
        .reset_n(reset_n),
        .init(init),
        .next(next),
        .block(block),
        .ready(ready),
        .digest_valid(digest_valid),
        .digest(digest)
    );

    // ─── Clock generation: 100 MHz, full period = 10 ns ────────────────
    initial clk = 0;
    always #5 clk = ~clk;   // half-period = 5 ns

    // ─── Cycle counter ──────────────────────────────────────────────────
    always @(posedge clk) cycle_count = cycle_count + 1;

    // ─── VCD capture ────────────────────────────────────────────────────
    initial begin
        $dumpfile("tb_sha256_core.vcd");
        $dumpvars(0, tb_sha256_core);
    end

    // =====================================================================
    // TESTBENCH TIMING METHODOLOGY
    // =====================================================================
    //
    // Rule 1: NBA FOR DUT INPUTS
    //   All DUT input assignments in initial blocks use non-blocking
    //   assignment (<=). Exception: reset_n during reset sequence may use
    //   blocking (=).
    //
    // Rule 2: RESET SEQUENCE
    //   Hold reset_n=0 for 2+ posedge cycles, then release to 1.
    //   Wait @(negedge clk) after deassert for NBA to settle.
    //
    // Rule 3: MULTI-BLOCK PATTERN (N/A for single-block test vectors)
    //   init is driven only for the first block of a multi-block message.
    //   next is driven for every block. Both are single-cycle pulses.
    //
    // Rule 4: OUTPUT SAMPLING -- posedge for pulse, negedge for data
    //   - digest_valid: sampled at @(posedge clk) (pulse detection)
    //   - digest:       sampled at @(negedge clk) AFTER pulse (registered data)
    //
    // Rule 5: DATA INPUT HOLD TIME
    //   block data is held stable from init drive through next sampling.
    //   Deasserted after next is deasserted.
    //
    // =====================================================================

    // ─── Expected values (pre-computed from golden_model.py) ─────────────

    // Test vector 1: empty_string
    //   Block (512-bit): the SHA-256 padding of empty message
    //     M = "" -> padded = 0x80 || 0x00*55 || 0x00_00_00_00_00_00_00_00
    //     128 hex digits for 512 bits
    localparam [511:0] BLOCK_EMPTY =
        512'h80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    localparam [255:0] DIGEST_EMPTY =
        256'he3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855;

    // Test vector 2: abc
    //   Block (512-bit): SHA-256 padding of "abc" (3 bytes = 24 bits)
    //     M = "abc" = 0x616263
    //     padded = 0x616263 || 0x80 || 0x00*52 || 0x00_00_00_00_00_00_00_18
    localparam [511:0] BLOCK_ABC =
        512'h61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018;
    localparam [255:0] DIGEST_ABC =
        256'hba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad;

    // ─── Macros: race-free sampling helpers ─────────────────────────────

    `define SAMPLE_REGISTERED_OUTPUT(sig, expected, test_name) \
        @(negedge clk); \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s kind=registered width=%0db expected=0x%0h actual=0x%0h xor=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), expected, sig, (expected ^ sig)); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s kind=registered width=%0db actual=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), sig);

    `define SAMPLE_PULSE_OUTPUT(sig, expected, test_name) \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s kind=pulse width=%0db expected=0x%0h actual=0x%0h xor=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), expected, sig, (expected ^ sig)); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s kind=pulse width=%0db actual=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), sig);

    // ─── Reset task ─────────────────────────────────────────────────────

    task automatic apply_reset;
        begin
            reset_n = 0;                    // assert reset (active low)
            init   <= 1'b0;
            next   <= 1'b0;
            block  <= 512'd0;
            @(posedge clk); @(posedge clk); // hold reset 2 cycles
            reset_n = 1;                    // release reset
            @(negedge clk);                 // wait for NBA to settle
            $display("[TRACE] cycle=%0d reset_n released", cycle_count);
        end
    endtask

    // ─── Wait-for-ready helper ──────────────────────────────────────────

    task automatic wait_ready;
        input integer max_cycles;
        integer waited;
        begin
            waited = 0;
            while (ready !== 1'b1 && waited < max_cycles) begin
                @(posedge clk);
                waited = waited + 1;
            end
            if (waited >= max_cycles) begin
                $display("[TIMEOUT] cycle=%0d wait_ready: ready did not assert within %0d cycles",
                         cycle_count, max_cycles);
            end
        end
    endtask

    // ─── Wait-for-digest_valid helper ───────────────────────────────────

    task automatic wait_digest_valid;
        input integer max_cycles;
        integer waited;
        begin
            waited = 0;
            while (digest_valid !== 1'b1 && waited < max_cycles) begin
                @(posedge clk);
                waited = waited + 1;
            end
            if (waited >= max_cycles) begin
                $display("[TIMEOUT] cycle=%0d wait_digest_valid: digest_valid did not assert within %0d cycles",
                         cycle_count, max_cycles);
            end
        end
    endtask

    // ─── Single test vector runner ──────────────────────────────────────

    task automatic run_test_vector;
        input [511:0] test_block;
        input [255:0] expected_digest;
        input [1023:0] test_name;
        begin
            apply_reset();

            // ── Wait for ready ──
            wait_ready(100);

            // ── Drive init pulse (first cycle) ──
            init  <= 1'b1;
            next  <= 1'b0;
            block <= test_block;
            @(posedge clk);             // DUT samples init=1
            init  <= 1'b0;

            // ── Drive next pulse (very next cycle) ──
            // No need to re-check ready -- init processing keeps ready=1.
            next  <= 1'b1;
            // block already driven, still stable
            @(posedge clk);             // DUT samples next=1, enters COMPUTE
            next  <= 1'b0;

            // ── Deassert block data after sampling ──
            block <= 512'd0;

            // ── Wait for digest_valid pulse ──
            wait_digest_valid(300);

            // Check digest_valid detected correctly (should be 1 at this point)
            `SAMPLE_PULSE_OUTPUT(digest_valid, 1'b1, test_name)

            // ── Sample digest at negedge (registered output) ──
            `SAMPLE_REGISTERED_OUTPUT(digest, expected_digest, test_name)
        end
    endtask

    // =====================================================================
    // Test sequence
    // =====================================================================
    initial begin
        $display("============================================================");
        $display(" tb_sha256_core -- SHA-256 Core Integration Test");
        $display(" Clock: 100 MHz (10 ns period)");
        $display(" Reset: async active-low (reset_n)");
        $display("============================================================");

        // ── Test 1: empty_string ────────────────────────────────────────
        $display("\n--- Test 1: empty_string ---");
        run_test_vector(BLOCK_EMPTY, DIGEST_EMPTY, "empty_string");

        // ── Test 2: abc ─────────────────────────────────────────────────
        $display("\n--- Test 2: abc ---");
        run_test_vector(BLOCK_ABC, DIGEST_ABC, "abc");

        // ── Summary ─────────────────────────────────────────────────────
        $display("\n============================================================");
        if (fail_count == 0)
            $display(" ALL TESTS PASSED");
        else
            $display(" FAILED: %0d assertion(s) failed", fail_count);
        $display("============================================================");
        $finish;
    end

endmodule
