"""cocotb integration testbench for sha256_core -- golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (ready, digest_valid, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.

SHA-256 specific notes:
  - reset_n is active-low. Assert = 0, release = 1.
  - init and next are single-cycle input pulses, driven on separate cycles.
  - The golden model trace has 70 cycles: cycle 0 (reset), cycle 1 (after init),
    cycles 2-66 (COMPUTE t=0..64), cycle 67 (UPDATE_H), cycle 68 (DONE),
    cycle 69 (return to IDLE).
  - After drive_sha256 returns, DUT state corresponds to golden cycle 2
    (COMPUTE, t=0). Comparison starts at golden cycle 2 (skip 0,1).
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer

# ─── Clock ─────────────────────────────────────────────────────────────────
# Full period from 100 MHz: 1000/100 = 10 ns. NOT half-period.
CLK_PERIOD_NS = 10

# ─── Alignment ─────────────────────────────────────────────────────────────
# Golden cycle 0 = post-reset state. Golden cycle 1 = after init (H loaded).
# After drive_sha256() returns, DUT is at golden cycle 2 (COMPUTE, t=0).
# Comparison starts at golden cycle 2.
RESET_CYCLE_SKIP = 2
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0
_STIMULUS_DELIVERED = False

# ─── Golden model import ───────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        from golden_model import TEST_VECTORS as GOLDEN_TEST_VECTORS
        from golden_model import get_test_vectors
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# ─── Port configuration (populated from spec.json) ─────────────────────────
INPUT_PORTS = {
    "init": 1,
    "next": 1,
    "block": 512,
}

OUTPUT_PORTS = {
    "ready": 1,
    "digest_valid": 1,
    "digest": 256,
}

VALID_OUTPUT_PORTS = ["digest_valid"]

HANDSHAKE_PORTS = {}  # init/next are inputs, not valid->ack pairs

HOLD_UNTIL_ACK_PORTS = []  # init/next are single_cycle pulses

# DRIVE_PHASE_CYCLES from spec.json timing_convention.golden_to_rtl_offset_cycles
DRIVE_PHASE_CYCLES = 1

# ─── Divergence collection ─────────────────────────────────────────────────
MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _record_divergence(divergences, sig_name, expected_val, actual_val,
                       cycle_idx, width, kind=None):
    """Append a divergence dict to `divergences`.

    Returns True when the caller should stop collecting (cap reached or
    fail-fast mode).
    """
    div = {
        "cycle": cycle_idx,
        "signal": sig_name,
        "expected": expected_val,
        "actual": actual_val,
        "width": width,
    }
    if kind:
        div["kind"] = kind
    divergences.append(div)
    return FAIL_FAST or len(divergences) >= MAX_COLLECTED_DIVERGENCES


def _format_divergence_block(div, tag):
    """Format one divergence as a [tag] FIRST DIVERGENCE-shaped block."""
    width = div.get("width") or 32
    hex_digits = max((width + 3) // 4, 1)
    kind = div.get("kind")
    kind_tag = f" kind={kind}" if kind else ""
    hint = (
        "\n  (testbench driver wrong -- DUT input doesn't match golden stimulus)"
        if kind == "stimulus_mismatch" else ""
    )
    return (
        f"[{tag}] FIRST DIVERGENCE at cycle={div['cycle']} "
        f"signal={div['signal']} (width={width}b){kind_tag}:\n"
        f"  expected = 0x{div['expected']:0{hex_digits}x}\n"
        f"  actual   = 0x{div['actual']:0{hex_digits}x}\n"
        f"  xor diff = 0x{div['expected'] ^ div['actual']:0{hex_digits}x}"
        f"{hint}"
    )


def _finalize_divergences(dut, divergences, tag):
    """Emit each divergence and raise AssertionError with a summary."""
    blocks = [_format_divergence_block(d, tag) for d in divergences]
    for b in blocks:
        dut._log.error(b)
    head = blocks[0]
    if len(blocks) > 1:
        more = "\n\n".join(blocks[1:])
        msg = (
            f"{head}\n\n"
            f"(+{len(blocks) - 1} additional divergence(s) collected; "
            f"set COCOTB_FAIL_FAST=1 to stop at the first):\n\n{more}"
        )
    else:
        msg = head
    raise AssertionError(msg)


# ─── Clock management ──────────────────────────────────────────────────────

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    assert CLK_PERIOD_NS is not None, (
        "CLK_PERIOD_NS not populated -- codegen must set from spec.timing.target_frequency_mhz"
    )
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Helpers ───────────────────────────────────────────────────────────────

def _lookup_signal_width(sig_name: str, default: int = 32) -> int:
    """Best-effort width lookup from spec-populated port dicts."""
    seen = {sig_name}
    candidates = [sig_name]
    cursor = 0
    while cursor < len(candidates):
        n = candidates[cursor]
        cursor += 1
        for stripped in (
            n.rsplit(".", 1)[-1] if "." in n else "",
            n[:-4] if n.endswith("_reg") else "",
            n.split("[", 1)[0] if "[" in n else "",
        ):
            if stripped and stripped not in seen:
                seen.add(stripped)
                candidates.append(stripped)

    for name in candidates:
        if name in OUTPUT_PORTS:
            return OUTPUT_PORTS[name]
    for name in candidates:
        if name in INPUT_PORTS:
            return INPUT_PORTS[name]
    return default


async def reset_dut(dut):
    """Apply async active-low reset and wait for outputs to settle."""
    global FAIL_COUNT
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = False
    # Assert reset (active low)
    dut.reset_n.value = 0
    # Zero all input ports
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    # Release reset
    dut.reset_n.value = 1
    await RisingEdge(dut.clk)


async def drive_sha256(dut, test_inputs):
    """Drive SHA-256 inputs: init pulse, then next pulse with block data.

    Drives init and next on consecutive cycles to match the RTL FSM flow.
    After this function returns, cocotb sees the DUT state corresponding to
    golden cycle 2 (COMPUTE, t=0, ready=0).

    Args:
        dut: cocotb DUT handle
        test_inputs: dict with keys "init", "next", "block"
    """
    global _STIMULUS_DELIVERED

    block_val = test_inputs["block"]

    # ── Step 1: Wait for ready ──
    timeout = TIMEOUT_CYCLES
    while int(dut.ready.value) != 1 and timeout > 0:
        await RisingEdge(dut.clk)
        timeout -= 1
    assert timeout > 0, (
        f"Timeout waiting for ready before init (cycle budget={TIMEOUT_CYCLES})"
    )

    # ── Step 2: Drive init pulse ──
    dut.init.value = 1
    dut.next.value = 0
    dut.block.value = block_val
    await RisingEdge(dut.clk)   # DUT samples init=1
    dut.init.value = 0          # deassert (single-cycle pulse)

    # ── Step 3: Drive next pulse on the next cycle ──
    # No need to re-check ready here -- init processing doesn't deassert ready.
    dut.next.value = 1
    # block still stable from init drive
    await RisingEdge(dut.clk)   # DUT samples next=1 -> enters COMPUTE
    dut.next.value = 0          # deassert (single-cycle pulse)

    # At this RisingEdge, cocotb sees POST-NBA of the posedge where next was
    # sampled. DUT state = COMPUTE, t=0, a=H0, ... = golden cycle 2.

    _STIMULUS_DELIVERED = True


def _align_trace(expected_cycles):
    """Slice golden trace to skip reset (cycle 0) and post-init (cycle 1).

    DRIVE_PHASE_CYCLES is consumed inside drive_sha256(). Do NOT re-add it here.
    """
    return expected_cycles[RESET_CYCLE_SKIP:]


def _validate_trace_signal_names(expected_cycles, dut, test_name):
    """Pre-check that golden trace signal names exist in DUT hierarchy."""
    if not expected_cycles:
        return [], []

    all_trace_keys = set()
    for entry in expected_cycles:
        if isinstance(entry, dict):
            all_trace_keys.update(entry.keys())

    found = []
    missing = []
    for sig_name in sorted(all_trace_keys):
        try:
            if '.' in sig_name:
                parts = sig_name.split('.')
                obj = dut
                for part in parts:
                    while '[' in part:
                        arr_name, rest = part.split('[', 1)
                        if arr_name:
                            obj = getattr(obj, arr_name)
                        idx_str, part = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                    if part:
                        obj = getattr(obj, part)
            elif '[' in sig_name:
                base, rest = sig_name.split('[', 1)
                obj = getattr(dut, base)
                idx_str, _ = rest.split(']', 1)
                obj = obj[int(idx_str)]
            else:
                getattr(dut, sig_name)
            found.append(sig_name)
        except (AttributeError, IndexError):
            missing.append(sig_name)

    if missing:
        dut._log.warning(
            f"[{test_name}] {len(missing)} golden trace signal(s) not found "
            f"in DUT: {missing[:10]}"
        )
    return found, missing


# ─── Multi-block chaining ──────────────────────────────────────────────────
# SHA-256 is a Merkle-Damgard hash (multi-block design). The golden_model.py
# does not export MULTI_BLOCK_INPUTS/MULTI_BLOCK_EXPECTED_DIGEST in the
# current version, so test_multi_block_chaining will SKIP gracefully.
# When those exports are added, set DIGEST_OUTPUT_PORT to the port name.
DIGEST_OUTPUT_PORT = "digest"


# ===========================================================================
# TESTS
# ===========================================================================

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior -- outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[RESET] {port_name}={val} after reset, expected 0"
                )
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance -- handshake and valid behavior."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check 1: After reset, all valid output ports must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass

    # Check 2: After reset, ready should be 1 (DUT ready to accept input)
    try:
        ready_val = int(dut.ready.value)
        if ready_val != 1:
            FAIL_COUNT += 1
            dut._log.error(
                f"[PROTOCOL] ready={ready_val} after reset, expected 1"
            )
    except AttributeError:
        pass

    # Check 3: init is single-cycle pulse -- verify it's sampled correctly
    # Drive init and verify DUT doesn't require it to be held
    if GOLDEN_AVAILABLE and GOLDEN_TEST_VECTORS:
        vec = GOLDEN_TEST_VECTORS[0]["inputs"]
        await drive_sha256(dut, vec)

        # After driving init+next, ready should drop (DUT is computing)
        # Poll for ready recovery
        timeout = TIMEOUT_CYCLES
        while int(dut.ready.value) != 1 and timeout > 0:
            await RisingEdge(dut.clk)
            timeout -= 1
        if timeout == 0:
            dut._log.warning(
                "[PROTOCOL] ready did not return to 1 within timeout"
            )
        else:
            dut._log.info("[PROTOCOL] ready handshake cycle OK")

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification -- golden model per-cycle output port comparison.

    Compares DUT output ports (ready, digest_valid, digest) against golden
    model expected values on every clock cycle. Reports FIRST DIVERGENCE
    with cycle number, signal name, expected vs actual.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden model expected values
    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_layered: golden model returned no data")
        return

    dut._log.info(
        f"[LAYERED] Comparing {len(expected_cycles)} cycles against golden model"
    )

    # Pre-validate golden trace signal names against DUT hierarchy
    _validate_trace_signal_names(expected_cycles, dut, "test_layered")

    # ── Drive test stimulus ──
    test_vec = GOLDEN_TEST_VECTORS[0]["inputs"]
    await drive_sha256(dut, test_vec)

    # ── Map golden trace names to DUT output ports ──
    GOLDEN_TO_PORT = {
        "ready_reg": "ready",
        "digest_valid_reg": "digest_valid",
        "digest_reg": "digest",
    }

    divergences = []
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    compare_cycles = _align_trace(expected_cycles)

    for cycle_idx, expected in enumerate(compare_cycles):
        stop_outer = False
        for sig_name, expected_val in expected.items():
            dut_name = GOLDEN_TO_PORT.get(sig_name)
            if dut_name is None:
                continue  # not a mapped output port
            try:
                sig = getattr(dut, dut_name)
                actual_val = int(sig.value)
                signals_compared += 1
                if actual_val != expected_val:
                    if _record_divergence(
                        divergences, sig_name, expected_val, actual_val,
                        cycle_idx, len(sig),
                    ):
                        stop_outer = True
                        break
            except AttributeError:
                if dut_name not in signals_not_found:
                    signals_not_found.append(dut_name)

        cycles_checked += 1

        if stop_outer:
            break

        # Advance DUT one cycle for the NEXT golden entry
        await RisingEdge(dut.clk)

    if INPUT_PORTS and not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_layered: drive_sha256() was never called (no stimulus delivered)"
        )

    if signals_not_found:
        dut._log.warning(
            f"[LAYERED] {len(signals_not_found)} port(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
        )

    if signals_compared == 0:
        raise AssertionError(
            "test_layered: ZERO signals compared -- GOLDEN_TO_PORT keys "
            "do not match any golden trace signal names"
        )
    if divergences:
        FAIL_COUNT += len(divergences)
        _finalize_divergences(dut, divergences, "LAYERED")
    else:
        dut._log.info(
            f"[LAYERED] PASS -- {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal register comparison against golden model.

    Reads RTL internal registers via VPI and compares against golden model
    trace on EVERY clock cycle. Catches internal register divergences that
    test_layered misses (e.g., wrong a_reg after round 7, but digest_reg
    eventually corrects due to later rounds masking the error).

    Signal names from golden model (_reg suffix):
      state_reg, t_reg, ready_reg, digest_valid_reg, digest_reg,
      a_reg..h_reg, H0_reg..H7_reg, W0_reg..W15_reg
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    # Check if trace includes internal signals
    has_internal = any(
        '.' in k or k.endswith('_reg')
        for entry in expected_cycles for k in entry.keys()
    )
    if not has_internal:
        dut._log.info(
            "[SKIP] test_internal_signals: golden trace has no internal signals"
        )
        return

    dut._log.info(
        f"[INTERNAL] Comparing {len(expected_cycles)} cycles, internal signals"
    )

    _validate_trace_signal_names(expected_cycles, dut, "test_internal_signals")

    # ── Drive test stimulus ──
    test_vec = GOLDEN_TEST_VECTORS[0]["inputs"]
    await drive_sha256(dut, test_vec)

    divergences = []
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    compare_cycles = _align_trace(expected_cycles)

    for cycle_idx, expected in enumerate(compare_cycles):
        stop_outer = False
        for sig_name, expected_val in expected.items():
            if sig_name in INPUT_PORTS:
                # Stimulus comparison
                try:
                    actual_val = int(getattr(dut, sig_name).value)
                    signals_compared += 1
                    if actual_val != expected_val:
                        if _record_divergence(
                            divergences, sig_name, expected_val, actual_val,
                            cycle_idx, _lookup_signal_width(sig_name),
                            kind="stimulus_mismatch",
                        ):
                            stop_outer = True
                            break
                except (AttributeError, ValueError):
                    pass
                continue

            try:
                if '.' in sig_name:
                    parts = sig_name.split('.')
                    obj = dut
                    for part in parts:
                        while '[' in part:
                            arr_name, rest = part.split('[', 1)
                            if arr_name:
                                obj = getattr(obj, arr_name)
                            idx_str, part = rest.split(']', 1)
                            idx = int(idx_str)
                            obj = obj[idx]
                        if part:
                            obj = getattr(obj, part)
                    actual_val = int(obj.value)
                else:
                    if '[' in sig_name:
                        base, rest = sig_name.split('[', 1)
                        obj = getattr(dut, base)
                        idx_str, _ = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                        actual_val = int(obj.value)
                    else:
                        sig = getattr(dut, sig_name)
                        actual_val = int(sig.value)

                signals_compared += 1
                if actual_val != expected_val:
                    try:
                        sig_width = len(obj if '.' in sig_name else sig)
                    except Exception:
                        sig_width = _lookup_signal_width(sig_name)
                    if _record_divergence(
                        divergences, sig_name, expected_val, actual_val,
                        cycle_idx, sig_width,
                    ):
                        stop_outer = True
                        break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        cycles_checked += 1
        if stop_outer:
            break

        await RisingEdge(dut.clk)

    if INPUT_PORTS and not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_internal_signals: drive_sha256() was never called "
            "(no stimulus delivered)"
        )

    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (
                f" ... and {len(signals_not_found) - 5} more"
                if len(signals_not_found) > 5
                else ""
            )
        )

    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals compared -- golden trace signal names "
            "do not match any DUT signals. Check naming convention."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if divergences:
        FAIL_COUNT += len(divergences)
        _finalize_divergences(dut, divergences, "INTERNAL")
    else:
        dut._log.info(
            f"[INTERNAL] PASS -- {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_timing_contract(dut):
    """Test 5: Verify timing contract invariants at runtime.

    Checks from spec.json timing_contract:
      - registered_outputs: ready, digest_valid, digest
        These must be stable between posedge and negedge (NBA-driven).
      - pipeline_delay_cycles: 1
    """
    global FAIL_COUNT

    await ensure_clock(dut)
    await reset_dut(dut)

    REGISTERED_OUTPUTS = ["ready", "digest_valid", "digest"]

    # Drive stimulus (same as test_layered)
    if GOLDEN_AVAILABLE and GOLDEN_TEST_VECTORS:
        test_vec = GOLDEN_TEST_VECTORS[0]["inputs"]
        await drive_sha256(dut, test_vec)

    violations = []
    for cycle in range(TIMEOUT_CYCLES):
        await RisingEdge(dut.clk)

        # Registered outputs: sample at RisingEdge, re-check at FallingEdge
        for port_name in REGISTERED_OUTPUTS:
            try:
                sig = getattr(dut, port_name)
                posedge_val = int(sig.value)
                await FallingEdge(dut.clk)
                negedge_val = int(sig.value)
                if posedge_val != negedge_val:
                    violations.append(
                        f"cycle={cycle} {port_name}: changed between "
                        f"posedge (0x{posedge_val:x}) and negedge "
                        f"(0x{negedge_val:x}) -- registered output must be "
                        f"stable (driven by NBA)"
                    )
                await RisingEdge(dut.clk)  # back to posedge for next iter
            except AttributeError:
                await RisingEdge(dut.clk)  # restore alignment
                pass

        # Check if we've reached DONE and returned to IDLE
        try:
            ready_val = int(dut.ready.value)
            digest_valid_val = int(dut.digest_valid.value)
            if ready_val == 1 and digest_valid_val == 0 and cycle > 5:
                # DUT completed the operation and returned to IDLE
                dut._log.info(
                    f"[TIMING CONTRACT] operation completed by cycle {cycle}"
                )
                break
        except AttributeError:
            pass

        if any(v.startswith("cycle") for v in violations):
            break

    if violations:
        dut._log.error(
            f"[TIMING CONTRACT] {len(violations)} violation(s):"
        )
        for v in violations[:5]:
            dut._log.error(f"  {v}")
        FAIL_COUNT += 1
        raise AssertionError(
            f"Timing contract violated: {violations[0]}"
        )
    else:
        dut._log.info("[TIMING CONTRACT] PASS -- all invariants hold")


@cocotb.test()
async def test_multi_block_chaining(dut):
    """Test 6: Multi-block chaining behavior -- catches Patterns 11 & 14.

    For SHA-256 (Merkle-Damgard hash), drives multi-block messages and
    compares the final digest against golden expected values.

    SKIPs gracefully when golden_model.py does not export
    MULTI_BLOCK_INPUTS / MULTI_BLOCK_EXPECTED_DIGEST.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info(
            "[SKIP] test_multi_block_chaining: golden_model.py not available"
        )
        return
    if DIGEST_OUTPUT_PORT is None:
        dut._log.info(
            "[SKIP] test_multi_block_chaining: DIGEST_OUTPUT_PORT not set"
        )
        return

    try:
        from golden_model import MULTI_BLOCK_INPUTS, MULTI_BLOCK_EXPECTED_DIGEST
    except ImportError:
        dut._log.info(
            "[SKIP] test_multi_block_chaining: MULTI_BLOCK_INPUTS / "
            "MULTI_BLOCK_EXPECTED_DIGEST not exported by golden_model.py "
            "(single-block-only golden model)"
        )
        return

    if len(MULTI_BLOCK_INPUTS) != len(MULTI_BLOCK_EXPECTED_DIGEST):
        raise AssertionError(
            f"test_multi_block_chaining: MULTI_BLOCK_INPUTS len="
            f"{len(MULTI_BLOCK_INPUTS)} != MULTI_BLOCK_EXPECTED_DIGEST len="
            f"{len(MULTI_BLOCK_EXPECTED_DIGEST)} -- golden_model.py mismatch."
        )
    if not any(len(blocks) >= 2 for blocks in MULTI_BLOCK_INPUTS):
        raise AssertionError(
            "test_multi_block_chaining: no test vector has 2+ blocks -- "
            "MULTI_BLOCK_INPUTS must include at least one message that "
            "exercises chaining."
        )

    await ensure_clock(dut)

    for msg_idx, blocks in enumerate(MULTI_BLOCK_INPUTS):
        await reset_dut(dut)
        dut._log.info(
            f"[MULTI_BLOCK] msg {msg_idx}: driving {len(blocks)} block(s)"
        )

        # Drive blocks sequentially: init for first, next for all
        for blk_idx, block_inputs in enumerate(blocks):
            is_first = (blk_idx == 0)

            # Wait for ready
            timeout = TIMEOUT_CYCLES
            while int(dut.ready.value) != 1 and timeout > 0:
                await RisingEdge(dut.clk)
                timeout -= 1
            assert timeout > 0, (
                f"[MULTI_BLOCK] msg {msg_idx} block {blk_idx}: "
                f"timeout waiting for ready"
            )

            # Drive init (first block only) and next (every block)
            dut.init.value = 1 if is_first else 0
            dut.next.value = 1
            dut.block.value = block_inputs.get("block", 0)
            await RisingEdge(dut.clk)
            dut.init.value = 0
            dut.next.value = 0

        # Wait for digest_valid
        timeout = TIMEOUT_CYCLES
        while int(dut.digest_valid.value) != 1 and timeout > 0:
            await RisingEdge(dut.clk)
            timeout -= 1
        if timeout == 0:
            FAIL_COUNT += 1
            dut._log.error(
                f"[MULTI_BLOCK] msg {msg_idx}: timed out waiting for digest_valid"
            )
            continue

        # Sample digest at negedge (registered output, NBA needs time to settle)
        await FallingEdge(dut.clk)
        actual = int(dut.digest.value)
        expected = MULTI_BLOCK_EXPECTED_DIGEST[msg_idx]

        if actual != expected:
            FAIL_COUNT += 1
            try:
                width = len(dut.digest)
            except Exception:
                width = 256
            hex_digits = max((width + 3) // 4, 1)
            dut._log.error(
                f"[MULTI_BLOCK] msg {msg_idx} digest mismatch "
                f"(width={width}b):\n"
                f"  expected = 0x{expected:0{hex_digits}x}\n"
                f"  actual   = 0x{actual:0{hex_digits}x}\n"
                f"  xor diff = 0x{expected ^ actual:0{hex_digits}x}\n"
                f"  => Likely Pattern 11 (chaining reset) -- chaining "
                f"registers may not be re-initialized for the new message."
            )
        else:
            dut._log.info(
                f"[MULTI_BLOCK] msg {msg_idx}: digest matches "
                f"(0x{actual:064x})"
            )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail. MUST be the last test defined."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
