// Auto-generated by VeriFlow DSL from module hash_round_one_cycle
`resetall
`timescale 1ns / 1ps
`default_nettype none

module hash_round_one_cycle
(
    input  wire         clk,
    input  wire         rst,
    output wire [31:0] a_reg,
    output wire [31:0] b_reg,
    output wire [31:0] c_reg,
    output wire [31:0] d_reg,
    output wire [31:0] e_reg,
    output wire [31:0] f_reg,
    output wire [31:0] g_reg,
    output wire [31:0] h_reg,
    input  wire [31:0] w_j,
    input  wire [31:0] w_prime_j,
    input  wire calc_en
);

reg [31:0] a_reg_reg = 32'd0;
reg [31:0] b_reg_reg = 32'd0;
reg [31:0] c_reg_reg = 32'd0;
reg [31:0] d_reg_reg = 32'd0;
reg [31:0] e_reg_reg = 32'd0;
reg [31:0] f_reg_reg = 32'd0;
reg [31:0] g_reg_reg = 32'd0;
reg [31:0] h_reg_reg = 32'd0;

// Sequential logic (register update)
wire [33:0] _vf_tmp_0;
assign _vf_tmp_0 = (({a_reg_reg[19:0], a_reg_reg[31:20]} + e_reg_reg) + 31'd2043430169);
wire [35:0] _vf_tmp_1;
assign _vf_tmp_1 = (((((e_reg_reg ^ f_reg_reg) ^ g_reg_reg) + h_reg_reg) + {_vf_tmp_0[26:0], _vf_tmp_0[33:27]}) + w_j);

always @(posedge clk) begin
    if (rst) begin
        a_reg_reg <= 32'd0;
        b_reg_reg <= 32'd0;
        c_reg_reg <= 32'd0;
        d_reg_reg <= 32'd0;
        e_reg_reg <= 32'd0;
        f_reg_reg <= 32'd0;
        g_reg_reg <= 32'd0;
        h_reg_reg <= 32'd0;
    end else begin
        a_reg_reg <= (calc_en ? (((((a_reg_reg ^ b_reg_reg) ^ c_reg_reg) + d_reg_reg) + ({_vf_tmp_0[26:0], _vf_tmp_0[33:27]} ^ {a_reg_reg[19:0], a_reg_reg[31:20]})) + w_prime_j) : a_reg_reg);
        b_reg_reg <= (calc_en ? a_reg_reg : b_reg_reg);
        c_reg_reg <= (calc_en ? {b_reg_reg[22:0], b_reg_reg[31:23]} : c_reg_reg);
        d_reg_reg <= (calc_en ? c_reg_reg : d_reg_reg);
        e_reg_reg <= (calc_en ? (((((((e_reg_reg ^ f_reg_reg) ^ g_reg_reg) + h_reg_reg) + {_vf_tmp_0[26:0], _vf_tmp_0[33:27]}) + w_j) ^ {_vf_tmp_1[26:0], _vf_tmp_1[35:27]}) ^ {_vf_tmp_1[18:0], _vf_tmp_1[35:19]}) : e_reg_reg);
        f_reg_reg <= (calc_en ? e_reg_reg : f_reg_reg);
        g_reg_reg <= (calc_en ? {f_reg_reg[12:0], f_reg_reg[31:13]} : g_reg_reg);
        h_reg_reg <= (calc_en ? g_reg_reg : h_reg_reg);
    end
end

// Output wire assignments
assign a_reg = a_reg_reg;
assign b_reg = b_reg_reg;
assign c_reg = c_reg_reg;
assign d_reg = d_reg_reg;
assign e_reg = e_reg_reg;
assign f_reg = f_reg_reg;
assign g_reg = g_reg_reg;
assign h_reg = h_reg_reg;

endmodule

`resetall