`timescale 1ns / 1ps

// tb_aes_128_core.v -- Self-checking Verilog testbench for aes_128_core.
// Pre-computed expected values from golden_model.py. No Python dependencies.
// Generated by VeriFlow-CC.

module tb_aes_128_core;

    // =========================================================================
    // Port declarations matching DUT
    // =========================================================================
    reg         clk;
    reg         rst_n;
    reg         start;
    reg [127:0] data_in;
    reg [127:0] key_in;
    wire [127:0] data_out;
    wire         valid;

    // Cycle counter and fail counter
    integer cycle_count = 0;
    integer fail_count  = 0;

    // Timeout for valid polling (AES-128 takes ~12 cycles)
    localparam TIMEOUT = 200;

    // =========================================================================
    // Pre-computed expected values from golden_model.py TEST_VECTORS
    // =========================================================================
    // Vector 0: NIST_AES128_FIPS197_Appendix_B
    //   key_in  = 0x2b7e151628aed2a6abf7158809cf4f3c
    //   data_in = 0x6bc1bee22e409f96e93d7e117393172a
    //   expected data_out = 0x3ad77bb40d7a3660a89ecaf32466ef97
    localparam [127:0] V0_KEY   = 128'h2b7e151628aed2a6abf7158809cf4f3c;
    localparam [127:0] V0_DATA  = 128'h6bc1bee22e409f96e93d7e117393172a;
    localparam [127:0] V0_EXPECT = 128'h3ad77bb40d7a3660a89ecaf32466ef97;

    // Vector 1: NIST_AES128_SP800_38A
    //   key_in  = 0x2b7e151628aed2a6abf7158809cf4f3c
    //   data_in = 0x000102030405060708090a0b0c0d0e0f
    //   expected data_out = 0x50fe67cc996d32b6da0937e99bafec60
    localparam [127:0] V1_KEY   = 128'h2b7e151628aed2a6abf7158809cf4f3c;
    localparam [127:0] V1_DATA  = 128'h000102030405060708090a0b0c0d0e0f;
    localparam [127:0] V1_EXPECT = 128'h50fe67cc996d32b6da0937e99bafec60;

    // Vector 2: AES128_all_zeros
    //   key_in  = 0x00000000000000000000000000000000
    //   data_in = 0x00000000000000000000000000000000
    //   expected data_out = 0x66e94bd4ef8a2c3b884cfa59ca342b2e
    localparam [127:0] V2_KEY   = 128'h00000000000000000000000000000000;
    localparam [127:0] V2_DATA  = 128'h00000000000000000000000000000000;
    localparam [127:0] V2_EXPECT = 128'h66e94bd4ef8a2c3b884cfa59ca342b2e;

    // Vector 3: AES128_all_ones
    //   key_in  = 0xffffffffffffffffffffffffffffffff
    //   data_in = 0xffffffffffffffffffffffffffffffff
    //   expected data_out = 0xbcbf217cb280cf30b2517052193ab979
    localparam [127:0] V3_KEY   = 128'hffffffffffffffffffffffffffffffff;
    localparam [127:0] V3_DATA  = 128'hffffffffffffffffffffffffffffffff;
    localparam [127:0] V3_EXPECT = 128'hbcbf217cb280cf30b2517052193ab979;

    // =========================================================================
    // DUT instantiation
    // =========================================================================
    aes_128_core uut (
        .clk(clk),
        .rst_n(rst_n),
        .start(start),
        .data_in(data_in),
        .key_in(key_in),
        .data_out(data_out),
        .valid(valid)
    );

    // =========================================================================
    // Clock generation: 100 MHz -> full period = 10 ns, half period = 5 ns
    // =========================================================================
    initial clk = 0;
    always #5 clk = ~clk;

    // Cycle counter
    always @(posedge clk) cycle_count = cycle_count + 1;

    // =========================================================================
    // VCD capture
    // =========================================================================
    initial begin
        $dumpfile("tb_aes_128_core.vcd");
        $dumpvars(0, tb_aes_128_core);
    end

    // =========================================================================
    // Macros: Race-free sampling helpers
    // =========================================================================
    `define SAMPLE_REGISTERED_OUTPUT(sig, expected, test_name) \
        @(negedge clk); \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s kind=registered width=%0db expected=0x%0h actual=0x%0h xor=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), expected, sig, (expected ^ sig)); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s kind=registered width=%0db actual=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), sig);

    `define SAMPLE_PULSE_OUTPUT(sig, expected, test_name) \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s kind=pulse width=%0db expected=0x%0h actual=0x%0h xor=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), expected, sig, (expected ^ sig)); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s kind=pulse width=%0db actual=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", $bits(sig), sig);

    // =========================================================================
    // RESET TASK: Active-low reset
    // =========================================================================
    task automatic apply_reset;
        begin
            rst_n = 0;                     // blocking OK for reset only
            start   <= 1'b0;               // NBA for all data inputs
            data_in <= 128'd0;
            key_in  <= 128'd0;
            @(posedge clk);                // hold reset for 2 cycles
            @(posedge clk);
            rst_n = 1;                     // deassert reset (blocking OK)
            @(negedge clk);                // wait for NBA to settle
            $display("[TRACE] cycle=%0d rst_n released", cycle_count);
        end
    endtask

    // =========================================================================
    // WAIT_VALID: Poll for valid=1 at posedge, return when found
    // =========================================================================
    task automatic wait_valid;
        input integer max_wait;
        integer timeout;
        begin
            timeout = max_wait;
            while (valid !== 1'b1 && timeout > 0) begin
                @(posedge clk);
                timeout = timeout - 1;
            end
            if (timeout == 0 && valid !== 1'b1) begin
                $display("[FAIL] wait_valid timed out after %0d cycles", max_wait);
                fail_count = fail_count + 1;
            end
        end
    endtask

    // =========================================================================
    // CHECK_DATA_OUT: Sample registered data_out at negedge, compare
    // =========================================================================
    task automatic check_data_out;
        input [127:0] expected;
        input [256*8-1:0] test_name;  // string
        begin
            @(negedge clk);  // wait for NBA to settle on data_out
            if (data_out !== expected) begin
                $display("[FAIL] test=%0s cycle=%0d signal=data_out kind=registered width=128b expected=0x%032h actual=0x%032h xor=0x%032h phase=negedge",
                         test_name, cycle_count, expected, data_out, (expected ^ data_out));
                fail_count = fail_count + 1;
            end else begin
                $display("[PASS] test=%0s cycle=%0d signal=data_out kind=registered width=128b actual=0x%032h phase=negedge",
                         test_name, cycle_count, data_out);
            end
        end
    endtask

    // =========================================================================
    // Test sequence
    // =========================================================================
    initial begin

        // ================================================================
        // Test 1: NIST_AES128_FIPS197_Appendix_B
        // ================================================================
        apply_reset();

        // Drive inputs with NBA (Rule 1: prevent race conditions)
        key_in  <= V0_KEY;
        data_in <= V0_DATA;
        start   <= 1'b1;
        @(posedge clk);               // DUT samples start, data_in, key_in

        // Deassert start (single_cycle pulse), hold data for 1 extra cycle
        start   <= 1'b0;
        // key_in and data_in held stable (Rule 6: data hold time)
        @(posedge clk);               // Wait for pipeline to latch inputs

        // Clear data inputs after hold time
        data_in <= 128'd0;
        key_in  <= 128'd0;

        // Wait for valid pulse (posedge detection per Rule 4A)
        wait_valid(TIMEOUT);

        // valid is a registered output too -- sample pulse at posedge
        `SAMPLE_PULSE_OUTPUT(valid, 1'b1, "v0_NIST_FIPS197_AppB")

        // data_out is registered -- sample at negedge after valid pulse (Rule 4B)
        check_data_out(V0_EXPECT, "v0_NIST_FIPS197_AppB");

        // ================================================================
        // Test 2: NIST_AES128_SP800_38A
        // ================================================================
        apply_reset();

        key_in  <= V1_KEY;
        data_in <= V1_DATA;
        start   <= 1'b1;
        @(posedge clk);

        start   <= 1'b0;
        @(posedge clk);               // hold data 1 extra cycle

        data_in <= 128'd0;
        key_in  <= 128'd0;

        wait_valid(TIMEOUT);
        `SAMPLE_PULSE_OUTPUT(valid, 1'b1, "v1_NIST_SP800_38A")
        check_data_out(V1_EXPECT, "v1_NIST_SP800_38A");

        // ================================================================
        // Test 3: AES128_all_zeros
        // ================================================================
        apply_reset();

        key_in  <= V2_KEY;
        data_in <= V2_DATA;
        start   <= 1'b1;
        @(posedge clk);

        start   <= 1'b0;
        @(posedge clk);               // hold data 1 extra cycle

        data_in <= 128'd0;
        key_in  <= 128'd0;

        wait_valid(TIMEOUT);
        `SAMPLE_PULSE_OUTPUT(valid, 1'b1, "v2_all_zeros")
        check_data_out(V2_EXPECT, "v2_all_zeros");

        // ================================================================
        // Test 4: AES128_all_ones
        // ================================================================
        apply_reset();

        key_in  <= V3_KEY;
        data_in <= V3_DATA;
        start   <= 1'b1;
        @(posedge clk);

        start   <= 1'b0;
        @(posedge clk);               // hold data 1 extra cycle

        data_in <= 128'd0;
        key_in  <= 128'd0;

        wait_valid(TIMEOUT);
        `SAMPLE_PULSE_OUTPUT(valid, 1'b1, "v3_all_ones")
        check_data_out(V3_EXPECT, "v3_all_ones");

        // ================================================================
        // Summary
        // ================================================================
        $display("");
        if (fail_count == 0)
            $display("ALL TESTS PASSED");
        else
            $display("FAILED: %0d assertion(s) failed", fail_count);
        $finish;
    end

endmodule
