"""cocotb integration testbench for aes_128_core -- golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (valid, data_out) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.

Two verification modes:
- test_layered: Golden model cycle-by-cycle output port comparison (algorithm designs)
- test_internal_signals: Per-cycle internal register comparison against golden model
- test_protocol: Protocol compliance checks (all designs)

Port configuration constants below are populated from spec.json by the codegen
stage. If codegen does not populate them, defaults are used and only
top-level port signals are checked.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 10  # 100 MHz target frequency -> full period = 10 ns
RESET_CYCLE_SKIP = 1  # Golden cycle 0 is the reset state; comparison starts at cycle 1
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0  # Accumulates across ALL tests; do NOT reset inside individual tests
_STIMULUS_DELIVERED = False  # Set True by drive_inputs(); checked by comparison tests

# -- Golden model import -------------------------------------------------------
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        from golden_model import get_test_vectors
        from golden_model import TEST_VECTORS
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# -- Port configuration --------------------------------------------------------
# Populated from spec.json by the codegen stage.
INPUT_PORTS = {
    "start":  1,
    "data_in": 128,
    "key_in":  128,
}
OUTPUT_PORTS = {
    "data_out": 128,
    "valid":    1,
}
VALID_OUTPUT_PORTS = ["valid"]
HANDSHAKE_PORTS = {}       # No ready/ack handshake ports
HOLD_UNTIL_ACK_PORTS = []  # No hold_until_ack ports

# DRIVE_PHASE_CYCLES: offset between golden model (software instantaneous) and RTL
# (post-NBA registered). Set from spec.json timing_convention field.
DRIVE_PHASE_CYCLES = 1    # from spec.timing_convention.golden_to_rtl_offset_cycles

# -- Timing contract -----------------------------------------------------------
REGISTERED_OUTPUTS = ["data_out", "valid"]
PIPELINE_DELAY_CYCLES = 1

# -- Divergence collection -----------------------------------------------------
MAX_COLLECTED_DIVERGENCES = int(os.environ.get("COCOTB_MAX_DIVERGENCES", "8"))
FAIL_FAST = os.environ.get("COCOTB_FAIL_FAST", "0") == "1"


def _record_divergence(divergences, sig_name, expected_val, actual_val,
                       cycle_idx, width, kind=None):
    """Append a divergence dict to `divergences`."""
    div = {
        "cycle": cycle_idx,
        "signal": sig_name,
        "expected": expected_val,
        "actual": actual_val,
        "width": width,
    }
    if kind:
        div["kind"] = kind
    divergences.append(div)
    return FAIL_FAST or len(divergences) >= MAX_COLLECTED_DIVERGENCES


def _format_divergence_block(div, tag):
    """Format one divergence as a [tag] FIRST DIVERGENCE-shaped block."""
    width = div.get("width") or 32
    hex_digits = max((width + 3) // 4, 1)
    kind = div.get("kind")
    kind_tag = f" kind={kind}" if kind else ""
    hint = (
        "\n  (testbench driver wrong -- DUT input doesn't match golden stimulus)"
        if kind == "stimulus_mismatch" else ""
    )
    return (
        f"[{tag}] FIRST DIVERGENCE at cycle={div['cycle']} "
        f"signal={div['signal']} (width={width}b){kind_tag}:\n"
        f"  expected = 0x{div['expected']:0{hex_digits}x}\n"
        f"  actual   = 0x{div['actual']:0{hex_digits}x}\n"
        f"  xor diff = 0x{div['expected'] ^ div['actual']:0{hex_digits}x}"
        f"{hint}"
    )


def _finalize_divergences(dut, divergences, tag):
    """Emit each divergence and raise AssertionError with a summary."""
    blocks = [_format_divergence_block(d, tag) for d in divergences]
    for b in blocks:
        dut._log.error(b)
    head = blocks[0]
    if len(blocks) > 1:
        more = "\n\n".join(blocks[1:])
        msg = (
            f"{head}\n\n"
            f"(+{len(blocks) - 1} additional divergence(s) collected; "
            f"set COCOTB_FAIL_FAST=1 to stop at the first):\n\n{more}"
        )
    else:
        msg = head
    raise AssertionError(msg)


# -- Clock management ----------------------------------------------------------

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    assert CLK_PERIOD_NS is not None, (
        "CLK_PERIOD_NS not populated -- codegen must set from spec.timing.target_frequency_mhz"
    )
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# -- Helpers -------------------------------------------------------------------

def _lookup_signal_width(sig_name: str, default: int = 32) -> int:
    """Best-effort width lookup from spec-populated port dicts."""
    seen = {sig_name}
    candidates = [sig_name]
    cursor = 0
    while cursor < len(candidates):
        n = candidates[cursor]
        cursor += 1
        for stripped in (
            n.rsplit(".", 1)[-1] if "." in n else "",
            n[:-4] if n.endswith("_reg") else "",
            n.split("[", 1)[0] if "[" in n else "",
        ):
            if stripped and stripped not in seen:
                seen.add(stripped)
                candidates.append(stripped)

    for name in candidates:
        if name in OUTPUT_PORTS:
            return OUTPUT_PORTS[name]
    for name in candidates:
        if name in INPUT_PORTS:
            return INPUT_PORTS[name]
    return default


async def reset_dut(dut):
    """Apply synchronous active-low reset and wait for outputs to settle."""
    global FAIL_COUNT
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = False
    dut.rst_n.value = 0
    # Zero all input ports
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)  # rst_n deassert sampled, outputs stable


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} "
            f"got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


def _validate_trace_signal_names(expected_cycles, dut, test_name):
    """Pre-check that golden trace signal names exist in DUT hierarchy."""
    if not expected_cycles:
        return [], []

    all_trace_keys = set()
    for entry in expected_cycles:
        if isinstance(entry, dict):
            all_trace_keys.update(entry.keys())

    found = []
    missing = []
    for sig_name in sorted(all_trace_keys):
        try:
            if '.' in sig_name:
                parts = sig_name.split('.')
                obj = dut
                for part in parts:
                    while '[' in part:
                        arr_name, rest = part.split('[', 1)
                        if arr_name:
                            obj = getattr(obj, arr_name)
                        idx_str, part = rest.split(']', 1)
                        obj = obj[int(idx_str)]
                    if part:
                        obj = getattr(obj, part)
            elif '[' in sig_name:
                base, rest = sig_name.split('[', 1)
                obj = getattr(dut, base)
                idx_str, _ = rest.split(']', 1)
                obj = obj[int(idx_str)]
            else:
                getattr(dut, sig_name)
            found.append(sig_name)
        except (AttributeError, IndexError):
            missing.append(sig_name)

    if missing:
        dut._log.warning(
            f"[{test_name}] {len(missing)} golden trace signal(s) not found in DUT: "
            f"{missing[:10]}"
        )
    return found, missing


def _align_trace(expected_cycles):
    """Slice the golden trace to skip the reset state (cycle 0)."""
    return expected_cycles[RESET_CYCLE_SKIP:]


async def drive_inputs(dut, input_values, valid_name='start',
                       hold_data_cycles=None):
    """Drive start=1 with input values, hold for pipeline cycles.

    For aes_128_core: no ready/ack handshake. Drive start pulse with
    data_in and key_in, hold data for DRIVE_PHASE_CYCLES extra cycles.

    Args:
        dut: cocotb DUT handle
        input_values: dict with keys "data_in" and "key_in"
        valid_name: name of the start/valid input port (default "start")
        hold_data_cycles: extra cycles to hold data after deasserting start.
            Defaults to DRIVE_PHASE_CYCLES.
    """
    if hold_data_cycles is None:
        hold_data_cycles = DRIVE_PHASE_CYCLES

    # Drive all inputs and start pulse simultaneously
    dut.data_in.value = input_values["data_in"]
    dut.key_in.value = input_values["key_in"]
    getattr(dut, valid_name).value = 1

    # Wait one rising edge -- DUT samples inputs at this posedge
    await RisingEdge(dut.clk)

    # Mark that stimulus was delivered
    global _STIMULUS_DELIVERED
    _STIMULUS_DELIVERED = True

    # Deassert start (single_cycle pulse)
    getattr(dut, valid_name).value = 0

    # Hold data for pipeline_delay_cycles so DUT has time to latch inputs
    for _ in range(hold_data_cycles):
        await RisingEdge(dut.clk)

    # Clear data inputs
    dut.data_in.value = 0
    dut.key_in.value = 0


async def wait_valid(dut, valid_name='valid', max_cycles=200):
    """Poll for valid=1, return cycle count waited."""
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1  # timeout


# -- Tests ---------------------------------------------------------------------

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior -- outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: verify all output ports are 0
    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance -- valid behavior after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset, valid must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification -- golden model output port comparison.

    Drives all 4 test vectors, waits for valid, compares data_out against
    golden model expected output.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)

    test_vectors = get_test_vectors()

    for vec_idx, vec in enumerate(test_vectors):
        await reset_dut(dut)

        # Drive inputs from test vector
        await drive_inputs(dut, vec["inputs"], valid_name="start")

        # Wait for valid output
        waited = await wait_valid(dut, valid_name="valid", max_cycles=TIMEOUT_CYCLES)
        assert waited >= 0, (
            f"[LAYERED] test vector {vec_idx} ({vec['name']}): "
            f"timed out waiting for valid=1"
        )

        # Sample registered output at next RisingEdge (post-NBA)
        await RisingEdge(dut.clk)

        # Compare data_out
        expected_data = vec["expected"]["data_out"]
        actual_data = int(dut.data_out.value)
        width = 128
        hex_digits = width // 4  # 32 hex digits for 128-bit

        if actual_data != expected_data:
            FAIL_COUNT += 1
            dut._log.error(
                f"[LAYERED] FIRST DIVERGENCE at vector={vec_idx} ({vec['name']}) "
                f"signal=data_out (width={width}b):\n"
                f"  expected = 0x{expected_data:0{hex_digits}x}\n"
                f"  actual   = 0x{actual_data:0{hex_digits}x}\n"
                f"  xor diff = 0x{expected_data ^ actual_data:0{hex_digits}x}"
            )
            raise AssertionError(
                f"[LAYERED] data_out mismatch on vector {vec_idx} ({vec['name']})"
            )
        else:
            dut._log.info(
                f"[PASS] vector={vec_idx} ({vec['name']}) "
                f"data_out=0x{actual_data:0{hex_digits}x}"
            )

    dut._log.info(
        f"[LAYERED] PASS -- {len(test_vectors)} test vectors matched"
    )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    Compares state_reg, round_counter_reg, data_out_reg, valid_reg
    against golden model trace on every clock cycle via VPI.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Run golden model with trace for default test vector (index 0)
    expected_cycles = golden_run(test_vector_index=0)
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    dut._log.info(
        f"[INTERNAL] Comparing {len(expected_cycles)} cycles against golden model"
    )

    # Pre-validate golden trace signal names against DUT hierarchy
    _validate_trace_signal_names(expected_cycles, dut, "test_internal_signals")

    # Drive inputs from default test vector (index 0)
    tv0 = TEST_VECTORS[0]
    await drive_inputs(dut, tv0["inputs"], valid_name="start")

    # Golden trace signal -> DUT signal mapping (internal registers)
    GOLDEN_TO_PORT = {
        "state_reg": "state_reg",
        "round_counter_reg": "round_counter_reg",
        "data_out_reg": "data_out_reg",
        "valid_reg": "valid_reg",
    }

    divergences = []
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    # Alignment: skip golden cycle 0 (reset state).
    compare_cycles = _align_trace(expected_cycles)

    for cycle_idx, expected in enumerate(compare_cycles):
        stop_outer = False
        for sig_name, expected_val in expected.items():
            # Map golden trace name to DUT signal name
            dut_name = GOLDEN_TO_PORT.get(sig_name)
            if dut_name is None:
                # Not a mapped internal signal -- skip
                continue

            try:
                sig = getattr(dut, dut_name)
                actual_val = int(sig.value)
                signals_compared += 1
                if actual_val != expected_val:
                    try:
                        sig_width = len(sig)
                    except Exception:
                        sig_width = _lookup_signal_width(sig_name)
                    if _record_divergence(
                        divergences, sig_name, expected_val, actual_val,
                        cycle_idx, sig_width,
                    ):
                        stop_outer = True
                        break
            except (AttributeError, IndexError):
                if dut_name not in signals_not_found:
                    signals_not_found.append(dut_name)

        cycles_checked += 1

        if stop_outer:
            break

        # Advance DUT one cycle for the NEXT golden entry.
        await RisingEdge(dut.clk)

    # Stimulus sanity check
    if INPUT_PORTS and not _STIMULUS_DELIVERED:
        raise AssertionError(
            "test_internal_signals: drive_inputs() was never called (no stimulus delivered)"
        )

    # Warn about signals that could not be found
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
        )

    # Safety check
    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared -- golden trace signal names "
            "do not match any DUT signals. Check naming convention."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if divergences:
        FAIL_COUNT += len(divergences)
        _finalize_divergences(dut, divergences, "INTERNAL")
    else:
        dut._log.info(
            f"[INTERNAL] PASS -- {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_timing_contract(dut):
    """Test: Verify timing contract invariants at runtime.

    Checks that registered outputs (data_out, valid) remain stable between
    posedge and negedge -- they must not change combinationally.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_timing_contract: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Drive stimulus from test vector 0
    tv0 = TEST_VECTORS[0]
    await drive_inputs(dut, tv0["inputs"], valid_name="start")

    violations = []
    for cycle in range(TIMEOUT_CYCLES):
        # 1. Registered outputs: sample at posedge, re-check at negedge
        await RisingEdge(dut.clk)
        for port_name in REGISTERED_OUTPUTS:
            try:
                sig = getattr(dut, port_name)
                posedge_val = int(sig.value)
                await FallingEdge(dut.clk)
                negedge_val = int(sig.value)
                if posedge_val != negedge_val:
                    violations.append(
                        f"cycle={cycle} {port_name}: changed between "
                        f"posedge (0x{posedge_val:x}) and negedge (0x{negedge_val:x}) "
                        f"-- registered output must be stable"
                    )
            except AttributeError:
                pass

        # Stop early if valid was asserted (operation complete)
        try:
            if int(dut.valid.value) == 1:
                break
        except AttributeError:
            pass

        if any(v.startswith("cycle") for v in violations):
            break

    if violations:
        dut._log.error(f"[TIMING CONTRACT] {len(violations)} violation(s):")
        for v in violations[:5]:
            dut._log.error(f"  {v}")
        FAIL_COUNT += len(violations)
        raise AssertionError(
            f"Timing contract violated: {violations[0]}"
        )
    else:
        dut._log.info("[TIMING CONTRACT] PASS -- all invariants hold")


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail.

    MUST be the last test defined in this file -- cocotb runs tests in
    definition order. This test reads the accumulated FAIL_COUNT.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
