//=============================================================================
// tb_sm3_core.v — Self-checking integration testbench for sm3_core
// Generated by VeriFlow-CC vf-tb-gen agent
//
// Tests two SM3 test vectors:
//   1. "abc"  (GM/T 0004-2012 Appendix A.1)
//   2. "abcd" (4-byte multi-byte padding verification)
//
// Timing methodology:
//   - All DUT input assignments use NBA (<=) except reset
//   - Active-low synchronous reset (rst_n)
//   - Valid-Ready handshake: drive msg_valid=1 when ready=1, deassert next cycle
//   - Data hold time: msg_block held 1 extra cycle after msg_valid deassert
//     to cover pipeline_delay_cycles=1 from FSM to datapath
//=============================================================================

`timescale 1ns / 1ps
`default_nettype none

module tb_sm3_core();

    // ── DUT ports ────────────────────────────────────────────────────────
    reg         clk;
    reg         rst_n;
    reg         msg_valid;
    reg  [511:0] msg_block;
    reg         is_last;
    wire        ready;
    wire        hash_valid;
    wire [255:0] hash_out;

    // ── Test infrastructure ──────────────────────────────────────────────
    integer     cycle_count;
    integer     fail_count;
    integer     test_num;

    // ── Test vector constants ────────────────────────────────────────────
    // "abc" test vector (GM/T 0004-2012, Appendix A.1)
    // Message: 0x616263 (3 bytes). Padded: 0x80 || zeros to 448 bits || length=24=0x18
    reg [511:0] MSG_ABC;
    reg [255:0] HASH_ABC;

    // "abcd" test vector (4-byte multi-byte padding)
    // Message: 0x61626364 (4 bytes). Padded: 0x80 || zeros to 448 bits || length=32=0x20
    reg [511:0] MSG_ABCD;
    reg [255:0] HASH_ABCD;

    initial begin
        MSG_ABC  = 512'h61626380_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000018;
        HASH_ABC = 256'h66c7f0f4_62eeedd9_d1f2d46b_dc10e4e2_4167c487_5cf2f7a2_297da02b_8f4ba8e0;
        MSG_ABCD = 512'h61626364_80000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000020;
        HASH_ABCD = 256'h82ec580f_e6d36ae4_f81cae3c_73f4a5b3_b5a09c94_3172dc90_53c69fd8_e18dca1e;
    end

    // ── DUT instantiation ────────────────────────────────────────────────
    sm3_core u_sm3_core (
        .clk        (clk),
        .rst_n      (rst_n),
        .msg_valid  (msg_valid),
        .msg_block  (msg_block),
        .is_last    (is_last),
        .ready      (ready),
        .hash_valid (hash_valid),
        .hash_out   (hash_out)
    );

    // ── Clock generation (100 MHz = 10ns period) ────────────────────────
    initial clk = 0;
    always #5 clk = ~clk;

    // ── Cycle counter ────────────────────────────────────────────────────
    initial cycle_count = 0;
    always @(posedge clk) cycle_count = cycle_count + 1;

    // ── VCD dump for waveform analysis ───────────────────────────────────
    initial begin
        $dumpfile("tb_sm3_core.vcd");
        $dumpvars(0, tb_sm3_core);
    end

    // ── Timeout watchdog ─────────────────────────────────────────────────
    initial begin
        #500000;  // 500 us at 100MHz = 50000 cycles
        $display("[TIMEOUT] Testbench timed out at cycle=%0d", cycle_count);
        $display("[FAIL] %0d test(s) failed (timeout)", fail_count + 1);
        $finish;
    end

    // ── Test orchestration ───────────────────────────────────────────────
    initial begin
        fail_count = 0;

        // ── Reset sequence ───────────────────────────────────────────────
        $display("================================================================");
        $display(" tb_sm3_core — SM3 Hash Core Self-Checking Testbench");
        $display("================================================================");
        $display();

        rst_n = 0;
        msg_valid <= 0;
        msg_block <= 512'd0;
        is_last <= 0;
        @(posedge clk); @(posedge clk);  // hold reset 2 cycles
        rst_n = 1;
        @(negedge clk);  // wait for NBA region to settle after rst deassert
        $display("[TRACE] cycle=%0d rst_n released", cycle_count);

        // Verify post-reset state
        if (ready !== 1'b1) begin
            $display("[FAIL] Post-reset: ready=%b, expected 1", ready);
            fail_count = fail_count + 1;
        end else begin
            $display("[PASS] Post-reset: ready=1 OK");
        end

        // ── Test 1: "abc" single block ───────────────────────────────────
        test_num = 1;
        $display();
        $display("--- Test %0d: SM3(\"abc\") ---", test_num);
        run_single_block_test(MSG_ABC, HASH_ABC, "abc");

        // Reset between independent tests (V registers must re-initialize to IV)
        rst_n = 0;
        @(posedge clk); @(posedge clk);
        rst_n = 1;
        @(negedge clk);

        // ── Test 2: "abcd" single block ──────────────────────────────────
        test_num = 2;
        $display();
        $display("--- Test %0d: SM3(\"abcd\") ---", test_num);
        run_single_block_test(MSG_ABCD, HASH_ABCD, "abcd");

        // ── Summary ──────────────────────────────────────────────────────
        $display();
        $display("================================================================");
        if (fail_count == 0) begin
            $display(" ALL TESTS PASSED");
        end else begin
            $display(" FAILED: %0d assertion(s) failed", fail_count);
        end
        $display("================================================================");
        $display(" Simulation complete at cycle=%0d", cycle_count);
        #20 $finish;
    end

    // ── Task: run_single_block_test ──────────────────────────────────────
    // Drives a single 512-bit message block through the DUT using the
    // valid-ready handshake protocol and checks the output hash.
    //
    // Timing (pipeline_delay_cycles=1 from FSM to datapath):
    //   Cycle T:   drive msg_valid=1, msg_block, is_last
    //   Cycle T+1: msg_valid=0 (deassert handshake)
    //   Cycle T+2: msg_block=0 (safe to clear — load_en has propagated)
    //   Then wait for hash_valid, sample hash_out at the SAME posedge
    task run_single_block_test;
        input [511:0] block_data;
        input [255:0] expected_hash;
        input [1024*8-1:0] test_name;  // string for display

        integer waited;
        reg    timeout_occurred;

        begin
            timeout_occurred = 0;

            // ── Wait for ready ───────────────────────────────────────────
            waited = 0;
            while (ready !== 1'b1 && waited < 200) begin
                @(posedge clk);
                waited = waited + 1;
            end
            if (ready !== 1'b1) begin
                $display("[FAIL] test=%0s: timeout waiting for ready (cycle=%0d)", test_name, cycle_count);
                fail_count = fail_count + 1;
                timeout_occurred = 1;
            end

            if (!timeout_occurred) begin
                @(negedge clk);  // wait for NBA to settle
                $display("[TRACE] cycle=%0d test=%0s: ready asserted", cycle_count, test_name);

                // ── Drive inputs (NBA) ───────────────────────────────────
                @(posedge clk);
                msg_valid <= 1'b1;
                msg_block <= block_data;
                is_last   <= 1'b1;   // single-block message
                $display("[TRACE] cycle=%0d test=%0s: driving msg_valid=1 is_last=1", cycle_count, test_name);

                // ── Deassert handshake next cycle ────────────────────────
                @(posedge clk);
                msg_valid <= 1'b0;
                $display("[TRACE] cycle=%0d test=%0s: msg_valid deasserted", cycle_count, test_name);

                // ── Hold msg_block for TWO extra cycles (data hold time) ──
                // load_en from FSM is registered (pipeline_delay_cycles=1).
                // We need msg_block stable when w_gen sees load_en:
                //  Cycle 0: FSM samples msg_valid, transitions to CALC
                //  Cycle 1: FSM cal_cycle=0 → load_en goes high (FSM internal)
                //  Cycle 2: load_en visible to w_gen. msg_block MUST be valid HERE.
                @(posedge clk);  // cycle 1: msg_valid now deasserted
                @(posedge clk);  // cycle 2: load_en reaches w_gen
                msg_block <= 512'd0;
                is_last <= 1'b0;
                $display("[TRACE] cycle=%0d test=%0s: msg_block cleared (hold complete)", cycle_count, test_name);

                // ── Wait for hash_valid ──────────────────────────────────
                // hash_valid is a registered 1-cycle pulse from the FSM,
                // asserted in the cycle after DONE when transitioning to IDLE.
                // Poll at posedge; sample hash_out at the SAME posedge.
                waited = 0;
                while (hash_valid !== 1'b1 && waited < 200) begin
                    @(posedge clk);
                    waited = waited + 1;
                end

                if (hash_valid !== 1'b1) begin
                    $display("[FAIL] test=%0s: timeout waiting for hash_valid (cycle=%0d, waited=%0d)",
                             test_name, cycle_count, waited);
                    fail_count = fail_count + 1;
                    timeout_occurred = 1;
                end
            end

            if (!timeout_occurred) begin
                // hash_valid is a registered pulse visible at this posedge.
                // hash_out is combinational and reflects V registers updated in
                // the PREVIOUS cycle (update_v_en). To avoid reading hash_out
                // before combinational wires settle, sample using NBA.
                @(negedge clk);  // wait for all NBA + combinational updates to settle
                $display("[TRACE] cycle=%0d test=%0s: hash_valid asserted", cycle_count, test_name);

                if (hash_out !== expected_hash) begin
                    $display("[FAIL] test=%0s: hash mismatch at cycle=%0d", test_name, cycle_count);
                    $display("       expected: 0x%064h", expected_hash);
                    $display("       got:      0x%064h", hash_out);
                    fail_count = fail_count + 1;
                end else begin
                    $display("[PASS] test=%0s: hash matches GM/T 0004-2012 (cycle=%0d)",
                             test_name, cycle_count);
                end

                // Wait for ready to re-assert before next test
                @(posedge clk);
            end
        end
    endtask

endmodule

`default_nettype wire
