// tb_sm3_core.v — self-checking integration testbench for sm3_core
// Generated by VeriFlow-CC vf-tb-gen agent.
// Zero Python dependencies. Embeds pre-computed expected values from golden_model.py.
//
// Test vector: "abc" (GM/T 0004-2012 Appendix A.1)
//   msg_block = 512'h61626380...00000018
//   expected hash_out = 256'h66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0
//
// Timing: 150 MHz (period = 6.667 ns, half = 3.333 ns)
//   67 cycles per block: IDLE(1) + LOAD(1) + CALC(64) + UPDATE(1) + DONE(hash_valid)

`timescale 1ns / 1ps
`default_nettype none

module tb_sm3_core;

    // =========================================================================
    // DUT port declarations
    // =========================================================================
    reg         clk;
    reg         rst_n;
    reg         msg_valid;
    reg  [511:0] msg_block;
    reg         is_last;
    wire        ready;
    wire        hash_valid;
    wire [255:0] hash_out;

    // =========================================================================
    // Cycle counter and fail counter
    // =========================================================================
    integer cycle_count = 0;
    integer fail_count  = 0;

    // =========================================================================
    // DUT instantiation
    // =========================================================================
    sm3_core uut (
        .clk        (clk),
        .rst_n      (rst_n),
        .msg_valid  (msg_valid),
        .msg_block  (msg_block),
        .is_last    (is_last),
        .ready      (ready),
        .hash_valid (hash_valid),
        .hash_out   (hash_out)
    );

    // =========================================================================
    // Expected values (pre-computed from golden_model.py)
    // =========================================================================
    // "abc" message block: 512-bit padded block per GM/T 0004-2012
    // 0x61626380 = "abc" + 0x80 padding byte (big-endian)
    // 0x00000018 at LSB = bit-length of "abc" (24 bits = 0x18)
    localparam [511:0] MSG_BLOCK_ABC = 512'h61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018;

    // Expected hash_out for "abc": SM3("abc") per GM/T 0004-2012
    localparam [255:0] EXPECTED_HASH_OUT = 256'h66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0;

    // =========================================================================
    // Clock generation — 150 MHz (period = 6.667 ns)
    // =========================================================================
    initial clk = 0;
    always #3.333 clk = ~clk;

    // =========================================================================
    // Cycle counter — increment every posedge
    // =========================================================================
    always @(posedge clk) cycle_count = cycle_count + 1;

    // =========================================================================
    // VCD capture — REQUIRED for waveform analysis
    // =========================================================================
    initial begin
        $dumpfile("tb_sm3_core.vcd");
        $dumpvars(0, tb_sm3_core);
    end

    // =========================================================================
    // TESTBENCH TIMING METHODOLOGY — Read Before Modifying This Testbench
    // =========================================================================
    //
    // Rule 1: NBA FOR DUT INPUTS (MANDATORY)
    //   All DUT input assignments in initial blocks MUST use non-blocking
    //   assignment (<=). This prevents race conditions between the testbench
    //   and the DUT's sequential always blocks at the same posedge.
    //
    //   Exception: Reset signal (rst_n) MAY use blocking (=) in the
    //   dedicated reset sequence only.
    //
    // Rule 2: RESET SEQUENCE TIMING
    //   rst_n is active-low. Hold rst_n=0 for at least 2 posedge cycles.
    //   After rst_n deassert, wait @(negedge clk) for NBA to settle.
    //
    // Rule 3: OUTPUT SAMPLING
    //   - Registered outputs: sample at @(negedge clk) after expected posedge.
    //   - Single-cycle pulse signals (hash_valid): sample at SAME @(posedge clk)
    //     where detection occurs. Do NOT insert @(negedge clk) between detection
    //     and sampling — the pulse may already be cleared.
    //
    // Rule 4: DATA INPUT HOLD TIME
    //   msg_block must remain stable for DRIVE_PHASE_CYCLES+1 = 2 cycles
    //   after msg_valid deassertion. This ensures w_gen (via load_en NBA-delayed
    //   control path) has sampled the data before it's cleared.
    //
    // =========================================================================

    // =========================================================================
    // MACROS: Race-free sampling helpers
    // =========================================================================
    `define SAMPLE_REGISTERED_OUTPUT(sig, expected, test_name) \
        @(negedge clk); \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s expected=0x%0h actual=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", expected, sig); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s actual=0x%0h phase=negedge", \
                     test_name, cycle_count, `"sig`", sig);

    `define SAMPLE_PULSE_OUTPUT(sig, expected, test_name) \
        if (sig !== expected) begin \
            $display("[FAIL] test=%s cycle=%0d signal=%s expected=0x%0h actual=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", expected, sig); \
            fail_count = fail_count + 1; \
        end else \
            $display("[PASS] test=%s cycle=%0d signal=%s actual=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", sig);

    // =========================================================================
    // TASKS
    // =========================================================================

    // Apply active-low reset and wait for DUT to stabilize in IDLE state.
    task automatic apply_reset;
        begin
            rst_n = 1'b0;        // blocking OK for reset only
            msg_valid <= 1'b0;
            msg_block <= 512'd0;
            is_last   <= 1'b0;
            @(posedge clk); @(posedge clk); @(posedge clk);
            rst_n = 1'b1;        // blocking OK for reset only
            @(negedge clk);      // wait for NBA to settle after rst_n deassert
            $display("[TRACE] cycle=%0d rst_n released, DUT in IDLE", cycle_count);
        end
    endtask

    // Poll for hash_valid=1. Returns number of cycles waited (0 on immediate).
    // Because hash_valid is a single-cycle pulse, the caller MUST sample
    // hash_out IMMEDIATELY after this task returns — no @(negedge clk) delay.
    task automatic wait_hash_valid;
        output integer waited;
        begin
            waited = 0;
            while (hash_valid !== 1'b1 && waited < 500) begin
                @(posedge clk);
                waited = waited + 1;
            end
            if (hash_valid !== 1'b1) begin
                $display("[TIMEOUT] cycle=%0d hash_valid never asserted after %0d cycles",
                         cycle_count, waited);
                waited = -1;
            end
        end
    endtask

    // =========================================================================
    // TEST SEQUENCE
    // =========================================================================
    // Local variable for wait_hash_valid return value
    integer cycles_waited;

    initial begin

        // =====================================================================
        // Test 1: Reset behavior
        // =====================================================================
        $display("=== Test 1: Reset ===");
        apply_reset();

        // After reset, DUT should be in IDLE state: ready=1, hash_valid=0
        `SAMPLE_REGISTERED_OUTPUT(ready, 1'b1, "reset");
        `SAMPLE_REGISTERED_OUTPUT(hash_valid, 1'b0, "reset");

        // =====================================================================
        // Test 2: End-to-end "abc" hash
        // =====================================================================
        $display("=== Test 2: E2E 'abc' ===");

        // Drive inputs with non-blocking assignment (Rule 1)
        @(posedge clk);  // gap after reset checks
        msg_block <= MSG_BLOCK_ABC;
        is_last   <= 1'b1;
        msg_valid <= 1'b1;
        $display("[DRIVE] cycle=%0d msg_valid=1 msg_block=abc is_last=1", cycle_count);

        // handshake posedge — DUT samples msg_valid, transitions to CALC
        @(posedge clk);
        msg_valid <= 1'b0;
        $display("[TRACE] cycle=%0d msg_valid deasserted, DUT entering CALC", cycle_count);

        // Hold data for DRIVE_PHASE_CYCLES+1 = 2 cycles (Rule 4)
        // The DUT's w_gen samples msg_block when load_en=1 (2 cycles after handshake).
        @(posedge clk);  // hold cycle 1 — load_en becomes 1 at this posedge's NBA
        $display("[TRACE] cycle=%0d hold cycle 1, load_en being asserted", cycle_count);

        @(posedge clk);  // hold cycle 2 — w_gen samples msg_block at this posedge
        $display("[TRACE] cycle=%0d hold cycle 2, w_gen sampled msg_block", cycle_count);

        // Now safe to clear data inputs
        msg_block <= 512'd0;
        is_last   <= 1'b0;

        // Wait for hash processing to complete (64 calc cycles + UPDATE + DONE)
        // Poll for hash_valid single-cycle pulse
        @(posedge clk);
        $display("[TRACE] cycle=%0d waiting for hash_valid...", cycle_count);

        wait_hash_valid(cycles_waited);
        $display("[TRACE] cycle=%0d hash_valid detected after %0d cycles (from deassert)",
                 cycle_count, cycles_waited);

        if (cycles_waited < 0) begin
            fail_count = fail_count + 1;
            $display("[FAIL] test=e2e_abc hash_valid timeout");
        end else begin
            // Sample hash_out IMMEDIATELY at same posedge (single-cycle pulse — Rule 3)
            // hash_out is combinational from V registers; valid when hash_valid=1.
            if (hash_out !== EXPECTED_HASH_OUT) begin
                fail_count = fail_count + 1;
                $display("[FAIL] test=e2e_abc cycle=%0d signal=hash_out phase=posedge",
                         cycle_count);
                $display("       expected: 0x%064h", EXPECTED_HASH_OUT);
                $display("       actual:   0x%064h", hash_out);
            end else begin
                $display("[PASS] test=e2e_abc cycle=%0d signal=hash_out phase=posedge",
                         cycle_count);
                $display("       hash_out=0x%064h matches expected", hash_out);
            end
        end

        // After hash_valid pulse, DUT should return to IDLE (ready=1)
        @(negedge clk);
        if (ready !== 1'b1) begin
            $display("[WARN] test=e2e_abc cycle=%0d ready=%b after hash_valid, expected 1 (IDLE)",
                     cycle_count, ready);
        end else begin
            $display("[PASS] test=e2e_abc cycle=%0d ready=1 after hash_valid (IDLE)", cycle_count);
        end

        // =====================================================================
        // Test 3: Non-last block test (is_last=0)
        // When is_last=0, DUT should process block, update V internally,
        // return to IDLE (ready=1), and NOT assert hash_valid.
        // =====================================================================
        $display("=== Test 3: Non-last block (is_last=0) ===");
        apply_reset();

        @(posedge clk);  // gap after reset

        // Block 1: "abc", is_last=0
        msg_block <= MSG_BLOCK_ABC;
        is_last   <= 1'b0;
        msg_valid <= 1'b1;
        $display("[DRIVE] cycle=%0d Block 1: msg_valid=1 is_last=0", cycle_count);

        @(posedge clk);
        msg_valid <= 1'b0;
        @(posedge clk); @(posedge clk);  // hold data
        msg_block <= 512'd0;
        is_last   <= 1'b0;

        // Wait for ready to go high (block processed, back to IDLE)
        // NOT hash_valid — hash_valid should stay 0 for is_last=0
        @(posedge clk);
        cycles_waited = 0;
        while (ready !== 1'b1 && cycles_waited < 500) begin
            @(negedge clk);
            if (hash_valid === 1'b1) begin
                fail_count = fail_count + 1;
                $display("[FAIL] test=non_last_block cycle=%0d hash_valid asserted with is_last=0",
                         cycle_count);
            end
            @(posedge clk);
            cycles_waited = cycles_waited + 1;
        end

        if (ready !== 1'b1) begin
            fail_count = fail_count + 1;
            $display("[FAIL] test=non_last_block ready timeout, never returned to IDLE");
        end else begin
            $display("[PASS] test=non_last_block cycle=%0d ready=1 after block (is_last=0), hash_valid stayed 0",
                     cycle_count);
        end

        // =====================================================================
        // Summary
        // =====================================================================
        $display("=== Summary ===");
        if (fail_count == 0) begin
            $display("ALL TESTS PASSED (cycle_count=%0d)", cycle_count);
        end else begin
            $display("FAILED: %0d assertion(s) failed (cycle_count=%0d)",
                     fail_count, cycle_count);
        end

        // Allow a few extra cycles for waveform finalization
        repeat (10) @(posedge clk);
        $finish;
    end

    // =========================================================================
    // Watchdog timer — prevent infinite simulation
    // =========================================================================
    initial begin
        #200000;  // ~30000 cycles at 150 MHz
        $display("[FATAL] Watchdog timeout — simulation hung");
        $finish;
    end

endmodule

`default_nettype wire
