"""cocotb integration testbench for sm3_core — SM3 cryptographic hash verification.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  Registered outputs (ready, hash_valid, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.

Test vectors:
  "abc" message (GM/T 0004-2012 standard test vector):
    Padded block: 512'h61626380_...00000018
    Expected hash: 256'h66c7f0f4_62eeedd9_d1f2d46b_dc10e4e2_4167c487_5cf2f7a2_297da02b_8f4ba8e0
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 10   # 100 MHz
TIMEOUT_CYCLES = 200
FAIL_COUNT = 0

# ─── Golden model import ────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        from golden_model import TEST_VECTORS, compute, get_test_vectors
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# ─── Port configuration ─────────────────────────────────────────────────
INPUT_PORTS = {
    "msg_block": 512,
    "msg_valid": 1,
    "is_last": 1,
}
OUTPUT_PORTS = {
    "ready": 1,
    "hash_valid": 1,
    "hash_out": 256,
}
VALID_OUTPUT_PORTS = ["hash_valid"]
HANDSHAKE_PORTS = {"msg_valid": "ready"}
HOLD_UNTIL_ACK_PORTS = []

# DRIVE_PHASE_CYCLES: from spec.json timing_convention.golden_to_rtl_offset_cycles
DRIVE_PHASE_CYCLES = 1

# ─── Test vector ────────────────────────────────────────────────────────
# "abc" padded message block per GM/T 0004-2012
ABC_MSG_BLOCK = 0x61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018
ABC_EXPECTED_HASH = 0x66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0


# ─── Clock management ───────────────────────────────────────────────────

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Helpers ────────────────────────────────────────────────────────────

async def reset_dut(dut):
    """Apply async reset (active-low rst_n) and wait for outputs to settle."""
    global FAIL_COUNT
    dut.rst_n.value = 0
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    for valid_name in HANDSHAKE_PORTS:
        try:
            getattr(dut, valid_name).value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


async def wait_ready(dut, max_cycles=TIMEOUT_CYCLES):
    """Poll for ready=1, return cycle count waited. Raises on timeout."""
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(dut.ready.value) == 1:
            return i + 1
    raise AssertionError(f"Timeout after {max_cycles} cycles waiting for ready")


async def wait_valid(dut, valid_name='hash_valid', max_cycles=200):
    """Poll for valid=1, return cycle count waited."""
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1  # timeout


async def drive_sm3_inputs(dut, msg_block_val, is_last_val):
    """Drive SM3 inputs with proper data hold timing.

    Protocol:
      1. Set msg_block/is_last BEFORE valid (data must be stable at posedge)
      2. Wait for ready=1
      3. Drive msg_valid=1 for exactly 1 cycle
      4. Keep msg_block and is_last stable for 3 more cycles
      5. Clear data inputs
    """
    # Set data BEFORE the handshake so it's stable at the msg_valid posedge
    dut.msg_block.value = msg_block_val
    dut.is_last.value = is_last_val

    await wait_ready(dut)

    # Drive valid for 1 cycle
    dut.msg_valid.value = 1
    await RisingEdge(dut.clk)
    dut.msg_valid.value = 0

    # Hold data stable for 3 more cycles (msg_valid→FSM CALC→load_en→w_gen latches)
    for _ in range(3):
        await RisingEdge(dut.clk)

    # Safe to clear data
    dut.msg_block.value = 0
    dut.is_last.value = 0


# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    reset_ok = True
    # After reset: hash_valid must be 0
    try:
        val = int(dut.hash_valid.value)
        if val != 0:
            FAIL_COUNT += 1
            dut._log.error(f"[RESET] hash_valid={val} after reset, expected 0")
            reset_ok = False
    except Exception:
        pass

    # After reset: ready should be 1 (FSM is in IDLE)
    try:
        val = int(dut.ready.value)
        if val != 1:
            FAIL_COUNT += 1
            dut._log.error(f"[RESET] ready={val} after reset, expected 1")
            reset_ok = False
    except Exception:
        pass

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance — ready/valid handshake behavior."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check: ready=1 in IDLE state after reset
    if int(dut.ready.value) != 1:
        FAIL_COUNT += 1
        dut._log.error(f"[PROTOCOL] ready={int(dut.ready.value)} after reset, expected 1")

    # Check: hash_valid=0 after reset
    if int(dut.hash_valid.value) != 0:
        FAIL_COUNT += 1
        dut._log.error(f"[PROTOCOL] hash_valid={int(dut.hash_valid.value)} after reset, expected 0")

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: End-to-end verification — "abc" test vector.

    Drives the padded "abc" message block, waits for hash_valid,
    and compares hash_out against the expected GM/T 0004-2012 value.
    """
    global FAIL_COUNT

    await ensure_clock(dut)
    await reset_dut(dut)

    dut._log.info("[LAYERED] Driving 'abc' test vector")

    # Drive the "abc" padded block
    await drive_sm3_inputs(dut, ABC_MSG_BLOCK, is_last_val=1)

    # Wait for hash_valid
    waited = await wait_valid(dut, valid_name='hash_valid', max_cycles=100)
    if waited < 0:
        FAIL_COUNT += 1
        dut._log.error("[LAYERED] Timeout waiting for hash_valid")
        raise AssertionError("hash_valid not asserted within 100 cycles")

    dut._log.info(f"[LAYERED] hash_valid asserted after {waited} cycles")

    # hash_out is registered and updated at same NBA as hash_valid.
    # Wait one more cycle for hash_out to be stable.
    await RisingEdge(dut.clk)

    # Compare hash_out
    actual_hash = int(dut.hash_out.value)
    if actual_hash != ABC_EXPECTED_HASH:
        FAIL_COUNT += 1
        msg = (
            f"[LAYERED] Hash mismatch: "
            f"expected=0x{ABC_EXPECTED_HASH:064x} "
            f"got=0x{actual_hash:064x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)

    dut._log.info(f"[LAYERED] PASS — hash_out=0x{actual_hash:064x} matches expected")


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    Compares RTL internal registers (A-H in sm3_compress) against
    golden_model.py per-round expected values.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden model per-round trace
    try:
        expected_rounds = golden_run(0)  # test vector index 0 = "abc"
    except Exception as e:
        dut._log.warning(f"[INTERNAL] golden_run() failed: {e}")
        return

    if not expected_rounds:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    dut._log.info(f"[INTERNAL] Golden model returned {len(expected_rounds)} rounds")

    # Drive the "abc" test vector
    await drive_sm3_inputs(dut, ABC_MSG_BLOCK, is_last_val=1)

    # Map golden trace keys to VPI hierarchy paths in the RTL
    # The golden model produces keys: A, B, C, D, E, F, G, H, W_j, W_prime_j, SS1, SS2, TT1, TT2
    # RTL internal registers are in sm3_compress submodule
    GOLDEN_TO_VPI = {}
    compress_regs = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
    for reg_name in compress_regs:
        # Try direct name first (cocotb may auto-discover)
        GOLDEN_TO_VPI[reg_name] = reg_name

    first_divergence = None
    rounds_checked = 0
    signals_compared = 0
    signals_not_found = []

    # Align: golden model round N corresponds to RTL internal state after NBA of CALC cycle N+1
    # (round 0 happens after load_en, which is 1 cycle after handshake)
    # The first round trace is the state AFTER round 0 computation
    # RTL: posedge with load_en=1 → NBA loads A-H from V → combinational round 0 logic computes
    # → next posedge NBA updates A-H with round 0 result
    # So golden round 0 is visible at posedge 2 after the handshake.

    for round_idx, expected in enumerate(expected_rounds):
        await RisingEdge(dut.clk)

        for sig_name, expected_val in expected.items():
            # Only compare registered state (skip combinational intermediates)
            if sig_name in ('round', 'W_j', 'W_prime_j', 'SS1', 'SS2', 'TT1', 'TT2'):
                continue

            vpi_name = GOLDEN_TO_VPI.get(sig_name)
            if vpi_name is None:
                continue

            try:
                sig = getattr(dut, vpi_name)
                actual_val = int(sig.value)
                signals_compared += 1
                if actual_val != expected_val:
                    first_divergence = {
                        "round": round_idx,
                        "signal": sig_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        rounds_checked += 1
        if first_divergence:
            break

    # Warn about signals that could not be found
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT hierarchy: "
            f"{signals_not_found}"
        )

    # If we found no signals via direct name, try VPI hierarchy paths
    if signals_compared == 0:
        dut._log.info("[INTERNAL] Trying VPI hierarchy paths (u_compress.A etc.)")
        # Re-drive for a fresh comparison
        await reset_dut(dut)
        await drive_sm3_inputs(dut, ABC_MSG_BLOCK, is_last_val=1)

        for round_idx, expected in enumerate(expected_rounds):
            await RisingEdge(dut.clk)

            for sig_name, expected_val in expected.items():
                if sig_name in ('round', 'W_j', 'W_prime_j', 'SS1', 'SS2', 'TT1', 'TT2'):
                    continue
                try:
                    sig = getattr(dut.u_compress, sig_name)
                    actual_val = int(sig.value)
                    signals_compared += 1
                    if actual_val != expected_val:
                        first_divergence = {
                            "round": round_idx,
                            "signal": sig_name,
                            "expected": expected_val,
                            "actual": actual_val,
                        }
                        break
                except (AttributeError, IndexError):
                    pass

            if first_divergence:
                break

    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals compared — internal register names "
            "do not match RTL. Check VPI hierarchy paths."
        )
        raise AssertionError("test_internal_signals: no signals compared")

    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at round={div['round']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS — {rounds_checked} rounds, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
