"""cocotb per-cycle verification testbench for sm3_core.
Generated by VeriFlow-CC vf-tb-gen agent.

Compares RTL internal signals against golden_model.py trace on EVERY clock cycle.
Uses DRIVE_PHASE_CYCLES=1 to account for registered-FSM-to-combinational-datapath
pipeline delay.

Test vectors: SM3("abc") single block (GM/T 0004-2012 Appendix A.1).

Timing convention:
  - spec.timing_convention.golden_to_rtl_offset_cycles = 1
  - Golden trace T=N corresponds to RTL T=N+1
  - cocotb reads POST-NBA after RisingEdge (for iverilog VPI)
  - DRIVE_PHASE_CYCLES=1 compensates for the offset

FSM timing (from sm3_fsm.v, 3-state: IDLE/CALC/DONE):
  - IDLE: ready=1; on msg_valid & ready → CALC
  - CALC: 65 cycles total
    * cal_cycle 0: load_en=1 (load msg_block into W, V→A~H)
    * cal_cycle 1-64: calc_en=1, round_cnt=0..63 (64 compression rounds)
  - DONE: update_v_en=1 (V = V XOR {A~H}); → IDLE
  - hash_valid: 1-cycle pulse when re-entering IDLE if is_last=1
"""

import os
import sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

# ─── Constants ───────────────────────────────────────────────────────────

CLK_PERIOD_NS = 10       # 100 MHz
CLK_PERIOD_UNIT = "ns"
TIMEOUT_CYCLES = 500
DRIVE_PHASE_CYCLES = 1   # from spec.json: golden_to_rtl_offset_cycles
FAIL_COUNT = 0

# ─── Test vector ─────────────────────────────────────────────────────────
# SM3("abc") single block
MSG_ABC = 0x61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018
EXPECTED_HASH_ABC = 0x66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0

# ─── Port configuration ──────────────────────────────────────────────────
INPUT_PORTS = {
    "msg_valid": 1,
    "msg_block": 512,
    "is_last":   1,
}
OUTPUT_PORTS = {
    "ready":      1,
    "hash_valid": 1,
    "hash_out":   256,
}
VALID_OUTPUT_PORTS = ["hash_valid"]
HANDSHAKE_PORTS = {"msg_valid": "ready"}

# ─── Golden model import ─────────────────────────────────────────────────

GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
GOLDEN_AVAILABLE = False
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run, compute as golden_compute
        from golden_model import MSG_ABC_PADDED as GM_MSG_ABC
        from golden_model import HASH_ABC as GM_HASH_ABC
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# ─── Signal name mapping: golden trace → DUT hierarchy ──────────────────
# Golden model trace uses flat signal names.
# RTL hierarchy: sm3_core (top) -> u_fsm / u_w_gen / u_compress
# We map to DUT internal signals by name.
GOLDEN_TO_RTL = {
    # Top-level ports (visible on DUT directly)
    "ready":       "ready",
    "hash_valid":  "hash_valid",
    "hash_out":    "hash_out",

    # FSM internal state (precise names from sm3_fsm.v RTL)
    "fsm_state":   "u_fsm.state_reg",     # 2-bit: 0=IDLE, 1=CALC, 2=DONE
    "load_en":     "u_fsm.load_en_reg",
    "calc_en":     "u_fsm.calc_en_reg",
    "update_v_en": "u_fsm.update_v_en_reg",
    "round_cnt":   "u_fsm.round_cnt_reg",

    # w_gen internal registers (precise names from sm3_w_gen.v RTL)
    "w_j":         "u_w_gen.w_j",
    "w_prime_j":   "u_w_gen.w_prime_j",

    # compress internal registers (precise names from sm3_compress.v RTL)
    "A":           "u_compress.a_reg_reg",
    "B":           "u_compress.b_reg_reg",
    "C":           "u_compress.c_reg_reg",
    "D":           "u_compress.d_reg_reg",
    "E":           "u_compress.e_reg_reg",
    "F":           "u_compress.f_reg_reg",
    "G":           "u_compress.g_reg_reg",
    "H":           "u_compress.h_reg_reg",
    "V0":          "u_compress.v0_reg_reg",
    "V1":          "u_compress.v1_reg_reg",
    "V2":          "u_compress.v2_reg_reg",
    "V3":          "u_compress.v3_reg_reg",
    "V4":          "u_compress.v4_reg_reg",
    "V5":          "u_compress.v5_reg_reg",
    "V6":          "u_compress.v6_reg_reg",
    "V7":          "u_compress.v7_reg_reg",
}


# ─── Clock management ────────────────────────────────────────────────────

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit=CLK_PERIOD_UNIT)
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Helpers ─────────────────────────────────────────────────────────────

async def reset_dut(dut):
    """Apply synchronous active-low reset and wait for outputs to settle."""
    dut.rst_n.value = 0
    dut.msg_valid.value = 0
    dut.msg_block.value = 0
    dut.is_last.value = 0
    await ClockCycles(dut.clk, 3)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)  # rst_n deassert sampled
    await Timer(1, unit="ns")  # allow NBA to settle


async def drive_msg_block(dut, block_data, is_last_flag=1):
    """Drive a single 512-bit message block via valid-ready handshake.

    Timing:
      1. Wait for ready=1
      2. Drive msg_valid=1, msg_block, is_last simultaneously
      3. Wait 1 cycle — DUT FSM samples handshake, transitions CALC
      4. Deassert msg_valid
      5. Hold msg_block for 1 extra cycle (data hold time)
         This covers pipeline_delay_cycles=1: registered FSM load_en
         arrives at w_gen/compress datapath 1 cycle after FSM transitions.
      6. Clear msg_block

    Returns the cycle count for when driving started.
    """
    # Wait for ready
    for _ in range(TIMEOUT_CYCLES):
        if int(dut.ready.value) == 1:
            break
        await RisingEdge(dut.clk)
    else:
        dut._log.error("Timeout waiting for ready")
        return

    # Drive inputs (cycle 0 of the block transaction)
    dut.msg_valid.value = 1
    dut.msg_block.value = block_data
    dut.is_last.value = is_last_flag
    await RisingEdge(dut.clk)

    # Deassert valid (cycle 1)
    dut.msg_valid.value = 0
    await RisingEdge(dut.clk)

    # Clear data after hold time (cycle 2 — load_en has now propagated)
    dut.msg_block.value = 0
    dut.is_last.value = 0
    await RisingEdge(dut.clk)


async def get_hier_signal(dut, path):
    """Resolve a hierarchical signal path via VPI.

    Supports dotted paths like 'u_fsm.state_reg'.
    Returns (value_int, signal_handle) or (None, None) if not found.
    """
    if '.' not in path:
        sig = getattr(dut, path, None)
        if sig is not None:
            return int(sig.value), sig
        return None, None

    parts = path.split('.')
    obj = dut
    for part in parts:
        obj = getattr(obj, part, None)
        if obj is None:
            return None, None
    try:
        return int(obj.value), obj
    except Exception:
        return None, None


def check_value(actual, expected, signal_name, cycle_idx, test_name):
    """Compare actual vs expected. Returns True if match."""
    global FAIL_COUNT
    if actual == expected:
        return True
    FAIL_COUNT += 1
    width = max(expected.bit_length(), actual.bit_length(), 32)
    fmt_w = (width + 3) // 4
    msg = (
        f"[FAIL] {test_name} cycle={cycle_idx} signal={signal_name}: "
        f"expected=0x{expected:0{fmt_w}x} got=0x{actual:0{fmt_w}x}"
    )
    print(msg)
    return False


# ─── Tests ───────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Verify post-reset state: ready=1, hash_valid=0."""
    await ensure_clock(dut)
    await reset_dut(dut)

    ready_val = int(dut.ready.value)
    hv_val = int(dut.hash_valid.value)

    assert ready_val == 1, f"Post-reset ready={ready_val}, expected 1"
    assert hv_val == 0, f"Post-reset hash_valid={hv_val}, expected 0"
    dut._log.info("[PASS] test_reset: ready=1, hash_valid=0 after reset")


@cocotb.test()
async def test_handshake(dut):
    """Verify valid-ready handshake: msg_valid is accepted only when ready=1."""
    await ensure_clock(dut)
    await reset_dut(dut)

    # Initially ready should be 1
    assert int(dut.ready.value) == 1, "ready not asserted after reset"

    # Drive msg_valid=1 while ready=1 — FSM should accept and go to CALC
    dut.msg_valid.value = 1
    dut.msg_block.value = MSG_ABC
    dut.is_last.value = 1
    await RisingEdge(dut.clk)

    # After sampling, ready should go to 0 (FSM transitioned to CALC)
    # Note: ready is registered, so it's still 1 at this RisingEdge.
    # It will be 0 after the NBA.
    dut.msg_valid.value = 0
    await RisingEdge(dut.clk)

    # Now ready should be 0 (FSM in CALC)
    # But hash_valid should not yet be asserted
    assert int(dut.hash_valid.value) == 0, "hash_valid asserted too early"

    # Clear data after hold
    dut.msg_block.value = 0
    dut.is_last.value = 0

    # Wait for hash_valid
    for _ in range(TIMEOUT_CYCLES):
        await RisingEdge(dut.clk)
        if int(dut.hash_valid.value) == 1:
            break
    else:
        dut._log.error("Timeout waiting for hash_valid")
        return

    dut._log.info("[PASS] test_handshake: valid-ready protocol and hash completion verified")


@cocotb.test()
async def test_abc_hash(dut):
    """End-to-end test: SM3("abc") must match GM/T 0004-2012 expected hash."""
    global FAIL_COUNT

    await ensure_clock(dut)
    await reset_dut(dut)

    # Drive the "abc" test vector
    await drive_msg_block(dut, MSG_ABC, is_last_flag=1)

    # Wait for hash_valid
    for cycle in range(TIMEOUT_CYCLES):
        await RisingEdge(dut.clk)
        if int(dut.hash_valid.value) == 1:
            break
    else:
        FAIL_COUNT += 1
        dut._log.error("[FAIL] test_abc_hash: timeout waiting for hash_valid")
        return

    # Check hash output — samples at the SAME posedge where hash_valid=1
    actual_hash = int(dut.hash_out.value)
    if actual_hash == EXPECTED_HASH_ABC:
        dut._log.info(f"[PASS] test_abc_hash: SM3('abc') = 0x{actual_hash:064x}")
    else:
        FAIL_COUNT += 1
        dut._log.error(
            f"[FAIL] test_abc_hash: hash mismatch\n"
            f"       expected: 0x{EXPECTED_HASH_ABC:064x}\n"
            f"       got:      0x{actual_hash:064x}"
        )


@cocotb.test()
async def test_layered(dut):
    """Per-cycle top-level output comparison against golden model trace.

    Drives the "abc" test vector, then compares ready, hash_valid, and hash_out
    against golden_model.py trace on every cycle.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not found")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden trace
    golden_trace = golden_run()
    if not golden_trace:
        dut._log.info("[SKIP] test_layered: golden_run() returned empty")
        return

    dut._log.info(f"[LAYERED] golden trace: {len(golden_trace)} cycles")
    dut._log.info(f"[LAYERED] DRIVE_PHASE_CYCLES = {DRIVE_PHASE_CYCLES}")

    # Drive the "abc" test vector
    await drive_msg_block(dut, MSG_ABC, is_last_flag=1)

    # Align golden trace with RTL after drive phase
    # Golden trace cycle 0 = initial IDLE (reset state)
    # Golden trace cycle 1 = IDLE->CALC transition (after msg_valid+ready handshake)
    # After drive_msg_block(), we've consumed the handshake and hold cycles.
    # With DRIVE_PHASE_CYCLES=1, we skip golden cycle 0 and start comparing
    # at golden cycle 1 (which corresponds to post-drive RTL state).
    start_offset = 1 + DRIVE_PHASE_CYCLES
    compare_trace = golden_trace[start_offset:]

    first_divergence = None
    cycles_checked = 0

    # Signals to compare at top level
    top_signals = ["ready", "hash_valid", "hash_out"]

    for cycle_idx, expected in enumerate(compare_trace):
        await RisingEdge(dut.clk)

        for sig_name in top_signals:
            expected_val = expected.get(sig_name)
            if expected_val is None:
                continue
            sig = getattr(dut, sig_name, None)
            if sig is None:
                continue
            actual_val = int(sig.value)

            if actual_val != expected_val:
                first_divergence = {
                    "cycle": cycle_idx,
                    "signal": sig_name,
                    "expected": expected_val,
                    "actual": actual_val,
                }
                break

        cycles_checked += 1
        if first_divergence:
            break

    if first_divergence:
        div = first_divergence
        FAIL_COUNT += 1
        msg = (
            f"[LAYERED] FIRST DIVERGENCE at relative cycle {div['cycle']}: "
            f"{div['signal']} expected=0x{div['expected']:x} got=0x{div['actual']:x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(f"[LAYERED] PASS — {cycles_checked} cycles matched golden model")


@cocotb.test()
async def test_internal_signals(dut):
    """Per-cycle internal register comparison against golden model trace.

    This is the KEY verification test. Reads RTL internal registers via VPI
    and compares them against golden_model.py trace on EVERY clock cycle.

    Internal signals checked:
      - FSM: state_reg, load_en_reg, calc_en_reg, update_v_en_reg, round_cnt_reg
      - w_gen: w_j, w_prime_j
      - compress: a_reg_reg..h_reg_reg, v0_reg_reg..v7_reg_reg

    The comparison alignment uses DRIVE_PHASE_CYCLES=1.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not found")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden trace
    golden_trace = golden_run()
    if not golden_trace:
        dut._log.info("[SKIP] test_internal_signals: golden_run() returned empty")
        return

    dut._log.info(f"[INTERNAL] golden trace: {len(golden_trace)} cycles")

    # Drive the "abc" test vector
    await drive_msg_block(dut, MSG_ABC, is_last_flag=1)

    # Align: skip golden cycle 0 (reset/IDLE) + DRIVE_PHASE_CYCLES
    start_offset = DRIVE_PHASE_CYCLES
    compare_trace = golden_trace[start_offset:]

    first_divergence = None
    cycles_checked = 0
    total_signals_checked = 0
    signals_not_found = set()

    # Internal signals we want to check
    internal_map = {
        "ready":       "ready",
        "hash_valid":  "hash_valid",
        "hash_out":    "hash_out",
        "fsm_state":   "u_fsm.state_reg",
        "load_en":     "u_fsm.load_en_reg",
        "calc_en":     "u_fsm.calc_en_reg",
        "update_v_en": "u_fsm.update_v_en_reg",
        "round_cnt":   "u_fsm.round_cnt_reg",
        "w_j":         "u_w_gen.w_j",
        "w_prime_j":   "u_w_gen.w_prime_j",
        "A":           "u_compress.a_reg_reg",
        "B":           "u_compress.b_reg_reg",
        "C":           "u_compress.c_reg_reg",
        "D":           "u_compress.d_reg_reg",
        "E":           "u_compress.e_reg_reg",
        "F":           "u_compress.f_reg_reg",
        "G":           "u_compress.g_reg_reg",
        "H":           "u_compress.h_reg_reg",
        "V0":          "u_compress.v0_reg_reg",
        "V1":          "u_compress.v1_reg_reg",
        "V2":          "u_compress.v2_reg_reg",
        "V3":          "u_compress.v3_reg_reg",
        "V4":          "u_compress.v4_reg_reg",
        "V5":          "u_compress.v5_reg_reg",
        "V6":          "u_compress.v6_reg_reg",
        "V7":          "u_compress.v7_reg_reg",
    }

    for cycle_idx, expected in enumerate(compare_trace):
        await RisingEdge(dut.clk)

        for gold_name, rtl_path in internal_map.items():
            expected_val = expected.get(gold_name)
            if expected_val is None:
                continue

            actual_val, _ = await get_hier_signal(dut, rtl_path)
            if actual_val is None:
                signals_not_found.add(rtl_path)
                continue

            total_signals_checked += 1
            if actual_val != expected_val:
                first_divergence = {
                    "cycle": cycle_idx,
                    "gold_name": gold_name,
                    "rtl_path": rtl_path,
                    "expected": expected_val,
                    "actual": actual_val,
                }
                break

        cycles_checked += 1
        if first_divergence:
            break

    # Report signals not found
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not accessible. "
            f"First few: {sorted(list(signals_not_found))[:8]}"
        )

    # Safety check: ensure we actually compared something
    if total_signals_checked == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals compared — check VPI access and signal names"
        )
        FAIL_COUNT += 1
        raise AssertionError("test_internal_signals: no signals compared")

    if first_divergence:
        div = first_divergence
        FAIL_COUNT += 1
        # Classify the error
        if div["actual"] == 0 and div["expected"] != 0:
            bug_type = "ZERO_OUT (computation produced 0, expected non-zero → init or logic bug)"
        else:
            xor_diff = div["actual"] ^ div["expected"]
            bug_type = (
                f"DATA_MISMATCH (xor_diff=0x{xor_diff:x})"
            )
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at relative cycle {div['cycle']}: "
            f"{div['gold_name']}({div['rtl_path']}) "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x} "
            f"→ {bug_type}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS — {cycles_checked} cycles, "
            f"{total_signals_checked} signal values matched golden model"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail count."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("=" * 60)
        dut._log.info(" ALL TESTS PASSED")
        dut._log.info("=" * 60)
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) across all tests")


if __name__ == "__main__":
    import subprocess
    subprocess.run([sys.executable, "-m", "cocotb", "test_sm3_core"])
