"""cocotb integration testbench for sm3_core — golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.

SM3-SPECIFIC TIMING:
  DRIVE_PHASE_CYCLES = 1 (golden_to_rtl_offset_cycles from spec.json).
  msg_block must remain stable for 2 cycles after msg_valid deassertion.
  rst_n is active-low: assert rst_n=0 for reset, then rst_n=1 to release.
  67 cycles per block: 1 IDLE + 1 LOAD + 64 CALC + 1 UPDATE + DONE(hash_valid).
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 10.0    # 100 MHz (functional sim)
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0

# --- Golden model import --------------------------------------------------
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        from golden_model import compute as golden_compute
        from golden_model import TEST_VECTORS
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# --- Port configuration ---------------------------------------------------
# Populated from spec.json by VeriFlow-CC vf-tb-gen agent.

INPUT_PORTS = {
    "msg_valid": 1,
    "msg_block": 512,
    "is_last": 1,
}

OUTPUT_PORTS = {
    "ready": 1,
    "hash_valid": 1,
    "hash_out": 256,
}

VALID_OUTPUT_PORTS = ["hash_valid"]

# msg_valid -> ready handshake: drive inputs when ready=1, msg_valid pulses for 1 cycle
HANDSHAKE_PORTS = {"msg_valid": "ready"}

# No hold_until_ack ports in this design
HOLD_UNTIL_ACK_PORTS = []

# DRIVE_PHASE_CYCLES: golden model computes instantaneously; RTL has 1-cycle NBA offset.
# Data inputs (msg_block, is_last) must remain stable for DRIVE_PHASE_CYCLES cycles
# after msg_valid deassertion so that downstream modules (w_gen via load_en) have
# sampled them.
DRIVE_PHASE_CYCLES = 1

# --- GOLDEN TRACE TO RTL VPI PATH MAPPING ---------------------------------
# Golden model trace uses abstract module names (sm3_fsm, sm3_compress, sm3_w_gen)
# and conceptual register names (A_reg, V0_reg).
# The RTL uses actual instance names (u_sm3_fsm, u_sm3_compress, u_sm3_w_gen)
# and actual register names (a_reg_reg, v0_reg_reg).
# This dict maps golden trace signal names to VPI hierarchy paths (list of parts).

GOLDEN_TRACE_TO_VPI_PATH = {
    # sm3_fsm signals: registered outputs via _reg internal registers
    "sm3_fsm.ready":       ["u_sm3_fsm", "ready_reg"],
    "sm3_fsm.hash_valid":  ["u_sm3_fsm", "hash_valid_reg"],
    "sm3_fsm.round_cnt":   ["u_sm3_fsm", "round_cnt_reg"],
    "sm3_fsm.load_en":     ["u_sm3_fsm", "load_en_reg"],
    "sm3_fsm.calc_en":     ["u_sm3_fsm", "calc_en_reg"],
    "sm3_fsm.update_v_en": ["u_sm3_fsm", "update_v_en_reg"],
    # sm3_compress signals: working registers A~H (_reg_reg naming)
    "sm3_compress.A_reg":  ["u_sm3_compress", "a_reg_reg"],
    "sm3_compress.B_reg":  ["u_sm3_compress", "b_reg_reg"],
    "sm3_compress.C_reg":  ["u_sm3_compress", "c_reg_reg"],
    "sm3_compress.D_reg":  ["u_sm3_compress", "d_reg_reg"],
    "sm3_compress.E_reg":  ["u_sm3_compress", "e_reg_reg"],
    "sm3_compress.F_reg":  ["u_sm3_compress", "f_reg_reg"],
    "sm3_compress.G_reg":  ["u_sm3_compress", "g_reg_reg"],
    "sm3_compress.H_reg":  ["u_sm3_compress", "h_reg_reg"],
    # sm3_compress V registers
    "sm3_compress.V0_reg": ["u_sm3_compress", "v0_reg_reg"],
    "sm3_compress.V1_reg": ["u_sm3_compress", "v1_reg_reg"],
    "sm3_compress.V2_reg": ["u_sm3_compress", "v2_reg_reg"],
    "sm3_compress.V3_reg": ["u_sm3_compress", "v3_reg_reg"],
    "sm3_compress.V4_reg": ["u_sm3_compress", "v4_reg_reg"],
    "sm3_compress.V5_reg": ["u_sm3_compress", "v5_reg_reg"],
    "sm3_compress.V6_reg": ["u_sm3_compress", "v6_reg_reg"],
    "sm3_compress.V7_reg": ["u_sm3_compress", "v7_reg_reg"],
    # sm3_w_gen signals: combinational outputs from w_reg shift register
    "sm3_w_gen.w_j":       ["u_sm3_w_gen", "w_j"],
    "sm3_w_gen.w_prime_j": ["u_sm3_w_gen", "w_prime_j"],
}

# Map golden trace names to top-level DUT port names for test_layered
GOLDEN_TO_PORT = {
    "sm3_fsm.ready":       "ready",
    "sm3_fsm.hash_valid":  "hash_valid",
}

# --- Test vector values ---------------------------------------------------
# "abc" test vector from GM/T 0004-2012 standard
MSG_BLOCK_ABC = (0x61626380 << 480) | 0x00000018

EXPECTED_HASH_OUT = 0x66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0

# --- Clock management -----------------------------------------------------

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# --- Helpers --------------------------------------------------------------

async def reset_dut(dut):
    """Apply active-low reset and wait for outputs to settle."""
    global FAIL_COUNT
    # Assert reset (active-low: rst_n=0)
    dut.rst_n.value = 0
    # Zero all input ports
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    # Hold reset for 3 cycles
    await ClockCycles(dut.clk, 3)
    # Release reset
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


async def drive_inputs(dut, input_values, valid_name="valid_in",
                       ready_name="ready_out",
                       hold_data_cycles=None):
    """Wait for ready, then drive valid=1 with input values.

    SM3-specific: msg_valid uses single_cycle handshake with ready.
    msg_block and is_last must remain stable for DRIVE_PHASE_CYCLES
    additional cycles after msg_valid deassertion.
    """
    if hold_data_cycles is None:
        hold_data_cycles = DRIVE_PHASE_CYCLES

    # Wait for ready (DUT must be in IDLE state)
    timeout = TIMEOUT_CYCLES
    ready_sig = getattr(dut, ready_name)
    while int(ready_sig.value) != 1 and timeout > 0:
        await RisingEdge(dut.clk)
        timeout -= 1
    assert timeout > 0, "Timeout waiting for ready before drive_inputs"

    # Drive all inputs at once
    for port_name, value in input_values.items():
        getattr(dut, port_name).value = value
    getattr(dut, valid_name).value = 1

    # Wait one rising edge — DUT samples inputs at this posedge
    await RisingEdge(dut.clk)

    # Single_cycle: deassert valid immediately after sampling
    getattr(dut, valid_name).value = 0

    # Hold data for DRIVE_PHASE_CYCLES so load_en (NBA delayed) sees stable data
    for _ in range(hold_data_cycles):
        await RisingEdge(dut.clk)

    # Clear data inputs
    for port_name in input_values:
        getattr(dut, port_name).value = 0


async def wait_valid(dut, valid_name="valid_out", max_cycles=TIMEOUT_CYCLES):
    """Poll for valid=1, return cycle count waited. Returns -1 on timeout."""
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1


def resolve_vpi_path(dut, sig_name):
    """Resolve a golden trace signal name to an actual VPI object.

    Returns (obj, actual_val) or None if not found.
    """
    vpi_path = GOLDEN_TRACE_TO_VPI_PATH.get(sig_name)
    if vpi_path is None:
        # Fallback: try raw name
        try:
            sig = getattr(dut, sig_name)
            return int(sig.value), sig_name
        except AttributeError:
            return None

    try:
        obj = dut
        for part in vpi_path:
            if '[' in part:
                arr_name, idx_str = part.split('[')
                idx = int(idx_str.rstrip(']'))
                obj = getattr(obj, arr_name)
                obj = obj[idx]
            else:
                obj = getattr(obj, part)
        return int(obj.value), ".".join(vpi_path)
    except (AttributeError, IndexError):
        return None


# --- Tests ----------------------------------------------------------------

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: ready should be 1 (IDLE state)
    reset_ok = True
    try:
        ready_val = int(dut.ready.value)
        if ready_val != 1:
            FAIL_COUNT += 1
            dut._log.error(f"[RESET] ready={ready_val} after reset, expected 1")
            reset_ok = False
    except AttributeError:
        dut._log.warning("[RESET] ready port not found in DUT")

    # hash_valid should be 0 after reset
    try:
        hv_val = int(dut.hash_valid.value)
        if hv_val != 0:
            FAIL_COUNT += 1
            dut._log.error(f"[RESET] hash_valid={hv_val} after reset, expected 0")
            reset_ok = False
    except AttributeError:
        pass

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct: ready=1, hash_valid=0")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance — handshake and valid behavior."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check 1: After reset, hash_valid must be 0
    try:
        hv = int(dut.hash_valid.value)
        if hv != 0:
            FAIL_COUNT += 1
            dut._log.error(f"[PROTOCOL] hash_valid={hv} after reset, expected 0")
        else:
            dut._log.info(f"[PROTOCOL] Check 1 PASS: hash_valid=0 after reset")
    except AttributeError:
        dut._log.warning("[PROTOCOL] hash_valid port not found")

    # Check 2: ready must be 1 after reset (IDLE state)
    try:
        rdy = int(dut.ready.value)
        if rdy != 1:
            FAIL_COUNT += 1
            dut._log.error(f"[PROTOCOL] ready={rdy} after reset, expected 1")
        else:
            dut._log.info(f"[PROTOCOL] Check 2 PASS: ready=1 after reset")
    except AttributeError:
        pass

    # Check 3: hash_valid must be a single-cycle pulse (not sticky)
    # Drive a test vector and verify hash_valid returns to 0 after pulsing
    if GOLDEN_AVAILABLE:
        await drive_inputs(dut, {"msg_block": MSG_BLOCK_ABC, "is_last": 1},
                           valid_name="msg_valid", ready_name="ready")

        # Poll for hash_valid
        waited = await wait_valid(dut, valid_name="hash_valid", max_cycles=200)
        if waited < 0:
            FAIL_COUNT += 1
            dut._log.error("[PROTOCOL] Check 3 FAIL: hash_valid never asserted")
        else:
            # Immediately after detection, check hash_valid is 1
            hv1 = int(dut.hash_valid.value)
            if hv1 != 1:
                FAIL_COUNT += 1
                dut._log.error(f"[PROTOCOL] Check 3 FAIL: hash_valid={hv1} at detection cycle")
            else:
                # Next cycle: hash_valid must return to 0 (single-cycle pulse)
                await RisingEdge(dut.clk)
                hv2 = int(dut.hash_valid.value)
                if hv2 != 0:
                    FAIL_COUNT += 1
                    dut._log.error(f"[PROTOCOL] Check 3 FAIL: hash_valid still {hv2} after pulse (not single-cycle)")
                else:
                    dut._log.info(f"[PROTOCOL] Check 3 PASS: hash_valid single-cycle pulse correct")

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] all protocol checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification — golden model per-cycle top-level port comparison.

    Checks top-level output ports (ready, hash_valid, hash_out) against
    golden model expected values at each cycle.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_layered: golden model returned no data")
        return

    dut._log.info(f"[LAYERED] Comparing {len(expected_cycles)} cycles against golden model")

    # Drive the "abc" test vector
    await drive_inputs(dut, {"msg_block": MSG_BLOCK_ABC, "is_last": 1},
                       valid_name="msg_valid", ready_name="ready")

    # Build per-cycle expected hash_out from golden trace V registers
    # hash_out = {V0, V1, V2, V3, V4, V5, V6, V7}
    for entry in expected_cycles:
        hv = 0
        for i in range(8):
            hv = (hv << 32) | entry[f"sm3_compress.V{i}_reg"]
        entry["_hash_out"] = hv

    first_divergence = None
    cycles_checked = 0

    # SM3 timing: golden model abstracts 1-cycle combinational delay.
    # After drive_inputs (handshake + DRIVE_PHASE_CYCLES hold), the first
    # RisingEdge reads POST-NBA of the hold cycle. Golden model cycle 1
    # (LOAD, load_en=1) is the first non-reset cycle visible in RTL.
    # RTL is ahead by golden_to_rtl_offset_cycles(=1) + DRIVE_PHASE_CYCLES(=1) = 2
    rtl_offset = 1 + DRIVE_PHASE_CYCLES
    compare_cycles = expected_cycles[rtl_offset:]

    for cycle_idx, expected in enumerate(compare_cycles):
        await RisingEdge(dut.clk)
        golden_cycle = cycle_idx + rtl_offset

        # Compare top-level output ports
        for sig_name, expected_val in expected.items():
            dut_name = GOLDEN_TO_PORT.get(sig_name)
            if dut_name is None:
                # Check _hash_out (computed from V registers)
                if sig_name == "_hash_out":
                    dut_name = "hash_out"
                else:
                    continue

            try:
                sig = getattr(dut, dut_name)
                actual_val = int(sig.value)
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": golden_cycle,
                        "signal": dut_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except AttributeError:
                pass

        cycles_checked += 1

        if first_divergence:
            break

    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        if div["actual"] == 0 and div["expected"] != 0:
            bug_type = "A (computation=0, expected non-zero -> logic or init error)"
        else:
            diff = div["actual"] ^ div["expected"]
            bug_type = f"A (data-wrong, xor_diff=0x{diff:x} -> logic or init error)"

        msg = (
            f"[LAYERED] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:0{len(str(hex(div['expected']))) - 2}x} "
            f"got=0x{div['actual']:0{len(str(hex(div['actual']))) - 2}x} "
            f"-> bug_type={bug_type}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(f"[LAYERED] PASS — {cycles_checked} cycles matched golden model")


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    Reads RTL internal registers via VPI hierarchy (cocotb's dut.hierarchy.signal.value)
    and compares against golden model trace on EVERY clock cycle.
    Catches bugs that test_layered misses since test_layered only checks top-level ports.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    dut._log.info(f"[INTERNAL] Comparing {len(expected_cycles)} cycles, internal signals")

    # Drive the "abc" test vector
    await drive_inputs(dut, {"msg_block": MSG_BLOCK_ABC, "is_last": 1},
                       valid_name="msg_valid", ready_name="ready")

    first_divergence = None
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    # RTL offset = golden_to_rtl_offset_cycles(1) + DRIVE_PHASE_CYCLES(1) = 2
    rtl_offset = 1 + DRIVE_PHASE_CYCLES
    compare_cycles = expected_cycles[rtl_offset:]

    for cycle_idx, expected in enumerate(compare_cycles):
        golden_cycle = cycle_idx + rtl_offset
        await RisingEdge(dut.clk)

        for sig_name, expected_val in expected.items():
            # Skip cycle number (not a signal)
            if sig_name == "cycle":
                continue

            # Resolve golden trace signal name to VPI path
            result = resolve_vpi_path(dut, sig_name)
            if result is None:
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)
                continue

            actual_val, _ = result
            signals_compared += 1

            if actual_val != expected_val:
                first_divergence = {
                    "cycle": golden_cycle,
                    "signal": sig_name,
                    "expected": expected_val,
                    "actual": actual_val,
                }
                break

        cycles_checked += 1
        if first_divergence:
            break

    # Safety check: verify we actually compared something
    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared -- golden trace signal names "
            "do not match any DUT signals. Check GOLDEN_TRACE_TO_VPI_PATH mapping."
        )
        dut._log.error(f"[INTERNAL] Signals not found: {signals_not_found}")
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    # Warn about signals that could not be found
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (f" ... and {len(signals_not_found) - 5} more" if len(signals_not_found) > 5 else "")
        )

    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS -- {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_end_to_end(dut):
    """Test 5: End-to-end verification — process "abc" block, check final hash.

    Drives the "abc" test vector and verifies the final 256-bit hash output
    matches the known SM3 reference value from GM/T 0004-2012.
    """
    global FAIL_COUNT

    await ensure_clock(dut)
    await reset_dut(dut)

    dut._log.info("[E2E] Driving 'abc' test vector...")

    await drive_inputs(dut, {"msg_block": MSG_BLOCK_ABC, "is_last": 1},
                       valid_name="msg_valid", ready_name="ready")

    # Wait for hash_valid pulse
    waited = await wait_valid(dut, valid_name="hash_valid", max_cycles=200)
    if waited < 0:
        FAIL_COUNT += 1
        dut._log.error("[E2E] FAIL: hash_valid never asserted (timeout)")
        raise AssertionError("Timeout waiting for hash_valid")

    # Read hash_out at the same posedge (single-cycle pulse — no @(negedge) delay)
    actual_hash = int(dut.hash_out.value)

    if actual_hash == EXPECTED_HASH_OUT:
        dut._log.info(
            f"[E2E] PASS: hash_out=0x{actual_hash:064x} "
            f"matches expected (waited {waited} cycles)"
        )
    else:
        FAIL_COUNT += 1
        diff = actual_hash ^ EXPECTED_HASH_OUT
        dut._log.error(
            f"[E2E] FAIL: hash_out mismatch\n"
            f"  expected: 0x{EXPECTED_HASH_OUT:064x}\n"
            f"  actual:   0x{actual_hash:064x}\n"
            f"  xor_diff: 0x{diff:064x}"
        )

    # Verify hash_valid returns to 0 after pulse
    await RisingEdge(dut.clk)
    hv_after = int(dut.hash_valid.value)
    if hv_after != 0:
        FAIL_COUNT += 1
        dut._log.error(f"[E2E] FAIL: hash_valid={hv_after} after pulse, expected 0 (single-cycle)")

    # After completion, DUT should return to IDLE (ready=1)
    rdy = int(dut.ready.value)
    if rdy != 1:
        dut._log.warning(f"[E2E] ready={rdy} after completion, expected 1 (IDLE)")


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
