// tb_sm3_core.v -- Integration testbench for sm3_core (SM3 hash core)
// Generated by VeriFlow-CC.
//
// Test vector: GM/T 0004-2012 official "abc"
//   Input:    "abc" padded to 512 bits
//   Expected: 66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0
//
// Timing contract (from spec.json):
//   - FSM registered outputs have pipeline_delay_cycles=1
//   - msg_block MUST be held stable for >= 2 cycles after msg_valid assertion
//   - Do NOT clear msg_block on the cycle after msg_valid goes low

`timescale 1ns/1ps

module tb_sm3_core;

    // -----------------------------------------------------------------------
    // Port declarations (match sm3_core interface)
    // -----------------------------------------------------------------------
    reg         clk;
    reg         rst_n;
    reg         msg_valid;
    reg  [511:0] msg_block;
    reg         is_last;
    wire        ready;
    wire        hash_valid;
    wire [255:0] hash_out;

    // -----------------------------------------------------------------------
    // Cycle counter for waveform correlation
    // -----------------------------------------------------------------------
    integer cycle_count = 0;
    integer fail_count  = 0;

    // -----------------------------------------------------------------------
    // DUT instantiation
    // -----------------------------------------------------------------------
    sm3_core uut (
        .clk       (clk),
        .rst_n     (rst_n),
        .msg_valid (msg_valid),
        .msg_block (msg_block),
        .is_last   (is_last),
        .ready     (ready),
        .hash_valid(hash_valid),
        .hash_out  (hash_out)
    );

    // -----------------------------------------------------------------------
    // Clock generation -- 10ns period (100 MHz)
    // -----------------------------------------------------------------------
    initial clk = 0;
    always #5 clk = ~clk;

    // Cycle counter
    always @(posedge clk)
        cycle_count = cycle_count + 1;

    // -----------------------------------------------------------------------
    // VCD capture
    // -----------------------------------------------------------------------
    initial begin
        $dumpfile("tb_sm3_core.vcd");
        $dumpvars(0, tb_sm3_core);
    end

    // -----------------------------------------------------------------------
    // Expected hash for "abc": 66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0
    // -----------------------------------------------------------------------
    localparam [255:0] EXPECTED_HASH = 256'h66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0;

    // Padded "abc": 'a'=0x61, 'b'=0x62, 'c'=0x63, then 0x80 padding, zeros,
    // and 0x00000018 (24-bit message length) at the end.
    localparam [511:0] MSG_BLOCK_ABC = 512'h61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018;

    // -----------------------------------------------------------------------
    // Wait for ready (polls at posedge clk)
    // -----------------------------------------------------------------------
    task wait_ready;
        input integer max_cycles;
        integer i;
        begin
            for (i = 0; i < max_cycles; i = i + 1) begin
                @(posedge clk);
                if (ready === 1'b1)
                    i = max_cycles;  // break
            end
        end
    endtask

    // -----------------------------------------------------------------------
    // Wait for hash_valid (polls at posedge clk)
    // Returns 0 on success, 1 on timeout.
    // -----------------------------------------------------------------------
    task wait_hash_valid;
        input integer max_cycles;
        output integer result;
        integer i;
        begin
            result = 1;  // default: timeout
            for (i = 0; i < max_cycles; i = i + 1) begin
                @(posedge clk);
                if (hash_valid === 1'b1) begin
                    result = 0;
                    i = max_cycles;  // break
                end
            end
        end
    endtask

    // -----------------------------------------------------------------------
    // Main test sequence
    // -----------------------------------------------------------------------
    initial begin
        // ===================================================================
        // Reset sequence
        // Rule 2: rst_n blocking OK for reset; data inputs use NBA (<=)
        // ===================================================================
        rst_n     = 0;           // blocking OK for reset only
        msg_valid <= 1'b0;       // NBA for all data inputs
        msg_block <= 512'd0;
        is_last   <= 1'b0;

        @(posedge clk);
        @(posedge clk);
        @(posedge clk);
        @(posedge clk);
        @(posedge clk);          // hold reset 5 cycles

        rst_n     = 1;           // deassert reset (blocking OK)
        @(negedge clk);          // wait for NBA to settle
        $display("[TRACE] cycle=%0d rst_n released", cycle_count);

        // ===================================================================
        // Test: SM3("abc") -- single block, is_last=1
        //
        // Rule 1: Use NBA (<=) for all DUT input assignments.
        // Rule 6: HOLD msg_block for 2 cycles after msg_valid assertion.
        //   Cycle A: assert msg_valid=1, msg_block=DATA, is_last=1
        //   Cycle A+1: deassert msg_valid, KEEP msg_block+is_last stable
        //   Cycle A+2: safe to clear msg_block+is_last
        // ===================================================================

        // Wait for ready
        wait_ready(100);
        $display("[TRACE] cycle=%0d ready=1, driving block", cycle_count);

        // Cycle A: assert handshake + data (NBA)
        msg_block <= MSG_BLOCK_ABC;
        msg_valid <= 1'b1;
        is_last   <= 1'b1;
        @(posedge clk);              // DUT samples inputs at this posedge
        $display("[TRACE] cycle=%0d msg_valid asserted", cycle_count);

        // Cycle A+1: deassert msg_valid, HOLD data stable
        msg_valid <= 1'b0;
        // msg_block and is_last remain stable -- do NOT clear yet
        @(posedge clk);
        $display("[TRACE] cycle=%0d msg_valid deasserted, holding data", cycle_count);

        // Cycle A+2: data still held (load_en fires this cycle)
        // Must hold msg_block until load_en has captured it
        @(posedge clk);

        // Cycle A+3: NOW safe to clear data inputs
        msg_block <= 512'd0;
        is_last   <= 1'b0;
        $display("[TRACE] cycle=%0d data inputs cleared", cycle_count);

        // Wait for hash_valid
        begin : wait_hash_block
            integer hv_result;
            wait_hash_valid(200, hv_result);
            if (hv_result != 0) begin
                $display("[FAIL] Timeout waiting for hash_valid");
                fail_count = fail_count + 1;
                $finish;
            end
        end

        // Check hash_out at SAME posedge where hash_valid=1
        // Rule 5: hash_valid is a single-cycle pulse, check immediately
        $display("[TRACE] cycle=%0d hash_valid=1, hash_out=0x%064h", cycle_count, hash_out);

        if (hash_out !== EXPECTED_HASH) begin
            $display("[FAIL] test=sm3_abc cycle=%0d signal=hash_out");
            $display("  expected: 0x%064h", EXPECTED_HASH);
            $display("  actual:   0x%064h", hash_out);
            fail_count = fail_count + 1;
        end else begin
            $display("[PASS] test=sm3_abc cycle=%0d signal=hash_out actual=0x%064h",
                     cycle_count, hash_out);
        end

        // Wait a few more cycles for clean waveform
        @(posedge clk);
        @(posedge clk);

        // ===================================================================
        // Summary
        // ===================================================================
        $display("");
        if (fail_count == 0)
            $display("ALL TESTS PASSED");
        else
            $display("FAILED: %0d assertion(s) failed", fail_count);

        $finish;
    end

endmodule
