// ============================================================================
// tb_sm3_core.v — Integration testbench for sm3_core
// Generated by VeriFlow-CC vf-tb-gen.
//
// Tests:
//   1. Reset behavior: ready=1, hash_valid=0 after reset release
//   2. "abc" test vector    — SM3("abc") one-block hash
//   3. "empty string" vector — SM3("") one-block hash
//
// Clock: 10ns period (100MHz) for simulation simplicity.
// Active-low reset: rst_n (0=assert, 1=release). Synchronous reset.
// Data hold: msg_block stable for DRIVE_PHASE_CYCLES+1 = 2 cycles after
//            valid deassert (w_gen needs stable data when load_en=1).
//
// Timing methodology (see template for full rules):
//   Rule 1: DUT inputs use NBA (<=) except reset.
//   Rule 2: Reset blocked (=) for rst_n only, 3+ cycles hold, negedge settle.
//   Rule 4: Pulse detected at posedge; registered data sampled at negedge AFTER.
//   Rule 6: Data held for pipeline_delay_cycles+1 after valid deassert.
// ============================================================================

`resetall
`timescale 1ns/1ps
`default_nettype none

module tb_sm3_core;

    // ── DUT ports ─────────────────────────────────────────────────────────
    reg         clk;
    reg         rst_n;
    reg         msg_valid;
    reg  [511:0] msg_block;
    reg         is_last;
    wire        ready;
    wire        hash_valid;
    wire [255:0] hash_out;

    // ── Test infrastructure ───────────────────────────────────────────────
    integer     cycle_count;
    integer     fail_count;

    // ── DUT instantiation ─────────────────────────────────────────────────
    sm3_core uut (
        .clk        (clk),
        .rst_n      (rst_n),
        .msg_valid  (msg_valid),
        .msg_block  (msg_block),
        .is_last    (is_last),
        .ready      (ready),
        .hash_valid (hash_valid),
        .hash_out   (hash_out)
    );

    // ── Clock generation (100 MHz = 10ns period) ──────────────────────────
    initial clk = 0;
    always #5 clk = ~clk;

    // ── Cycle counter ─────────────────────────────────────────────────────
    initial cycle_count = 0;
    always @(posedge clk) cycle_count = cycle_count + 1;

    // ── VCD capture ───────────────────────────────────────────────────────
    initial begin
        $dumpfile("tb_sm3_core.vcd");
        $dumpvars(0, tb_sm3_core);
    end

    // ========================================================================
    // Macros: Race-free sampling
    // ========================================================================
    // Failure log format (parsed by timing_diagnostic.py):
    //   [FAIL] test=<name> cycle=<n> signal=<s> kind=<registered|pulse>
    //          width=<w>b expected=0x<hex> actual=0x<hex> xor=0x<hex> phase=<edge>

    // For hash_out (registered, 256-bit). Caller must @(negedge clk) first.
    `define CHECK_HASH_OUT(expected, test_name)                         \
        if (hash_out !== expected) begin                                \
            $display("[FAIL] test=%s cycle=%0d signal=hash_out kind=registered width=256b expected=0x%0h actual=0x%0h xor=0x%0h phase=negedge", \
                     test_name, cycle_count, expected, hash_out, (expected ^ hash_out)); \
            fail_count = fail_count + 1;                                \
        end else                                                        \
            $display("[PASS] test=%s cycle=%0d signal=hash_out kind=registered width=256b actual=0x%0h phase=negedge", \
                     test_name, cycle_count, hash_out);

    // For pulse signals (hash_valid, ready). Check at current posedge.
    `define CHECK_PULSE(sig, expected, test_name)                       \
        if (sig !== expected) begin                                     \
            $display("[FAIL] test=%s cycle=%0d signal=%s kind=pulse width=1b expected=0x%0h actual=0x%0h xor=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", expected, sig, (expected ^ sig)); \
            fail_count = fail_count + 1;                                \
        end else                                                        \
            $display("[PASS] test=%s cycle=%0d signal=%s kind=pulse width=1b actual=0x%0h phase=posedge", \
                     test_name, cycle_count, `"sig`", sig);

    // ========================================================================
    // Reset Task
    // ========================================================================
    // Rule 2: rst_n uses blocking (=); data inputs use NBA (<=).
    // After reset release, wait negedge for NBA region to settle.
    task automatic apply_reset;
        begin
            rst_n = 0;                     // assert reset (active low)
            msg_valid <= 1'b0;
            msg_block <= 512'd0;
            is_last   <= 1'b0;
            @(posedge clk);
            @(posedge clk);
            @(posedge clk);                // hold reset 3+ cycles
            rst_n = 1;                     // release reset
            @(negedge clk);                // wait for NBA to settle
            $display("[TRACE] cycle=%0d rst_n released, DUT in IDLE", cycle_count);
        end
    endtask

    // ========================================================================
    // Drive Block Task
    // ========================================================================
    // Drives one 512-bit message block via valid/ready handshake.
    // Holds msg_block for DRIVE_PHASE_CYCLES+1 = 2 extra cycles after
    // valid deassert so w_gen sees stable data when load_en=1.
    //
    // Rule 1: All DUT input assignments use NBA (<=).
    // Rule 6: Data held for pipeline_delay_cycles+1 = 2 cycles after deassert.
    task automatic drive_block;
        input [511:0] block_data;
        input         last_flag;
        begin
            // Wait for ready (combinational from FSM IDLE)
            while (ready !== 1'b1) @(posedge clk);

            // Drive inputs at the next posedge
            msg_block <= block_data;
            is_last   <= last_flag;
            msg_valid <= 1'b1;
            @(posedge clk);                // DUT samples inputs here
            $display("[TRACE] cycle=%0d block driven, msg_valid=1", cycle_count);

            // Deassert valid (single-cycle pulse per SM3 protocol)
            msg_valid <= 1'b0;
            is_last   <= 1'b0;

            // Hold msg_block for 2 extra cycles (DRIVE_PHASE_CYCLES+1).
            // w_gen's load_en is registered; it appears 1 cycle after
            // msg_valid sampling. msg_block must still be valid then.
            @(posedge clk);                // hold cycle 1: load_en=1, w_gen loads
            @(posedge clk);                // hold cycle 2: calc_en=1, msg_block no longer needed
            msg_block <= 512'd0;

            $display("[TRACE] cycle=%0d data hold complete, msg_block cleared", cycle_count);
        end
    endtask

    // ========================================================================
    // Test: "abc" (single block, 3-byte message)
    // ========================================================================
    // Padded block: "abc" = 0x61 0x62 0x63 → pad with 0x80, zeros, length=24
    // Big-endian 512-bit: 0x61626380_00...00_00000018
    // Expected SM3:    0x66c7f0f4_62eeedd9_d1f2d46b_dc10e4e2_4167c487_5cf2f7a2_297da02b_8f4ba8e0
    task automatic test_abc;
        reg [255:0] expected_hash;
        begin
            $display("============================================================");
            $display("[TEST] Starting: abc (3 bytes, one block)");
            $display("============================================================");

            expected_hash = 256'h66c7f0f4_62eeedd9_d1f2d46b_dc10e4e2_4167c487_5cf2f7a2_297da02b_8f4ba8e0;

            drive_block(
                512'h61626380_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000018,
                1'b1
            );

            // Wait for hash_valid pulse at posedge (Rule 4)
            while (hash_valid !== 1'b1) @(posedge clk);
            $display("[TRACE] cycle=%0d hash_valid detected at posedge", cycle_count);

            // Sample hash_out at negedge AFTER hash_valid detection (Rule 4)
            @(negedge clk);
            `CHECK_HASH_OUT(expected_hash, "abc")

            $display("[TEST] abc complete");
        end
    endtask

    // ========================================================================
    // Test: "empty string" (single block, 0-byte message)
    // ========================================================================
    // Padded block: 0x80, zeros, length=0
    // Big-endian 512-bit: 0x80000000_00...00_00000000
    // Expected SM3:       0x1ab21d83_55cfa17f_8e611948_31e81a8f_22bec8c7_28fefb74_7ed035eb_5082aa2b
    task automatic test_empty;
        reg [255:0] expected_hash;
        begin
            $display("============================================================");
            $display("[TEST] Starting: empty string (0 bytes, one block)");
            $display("============================================================");

            expected_hash = 256'h1ab21d83_55cfa17f_8e611948_31e81a8f_22bec8c7_28fefb74_7ed035eb_5082aa2b;

            drive_block(
                512'h80000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000000,
                1'b1
            );

            // Wait for hash_valid pulse at posedge
            while (hash_valid !== 1'b1) @(posedge clk);
            $display("[TRACE] cycle=%0d hash_valid detected at posedge", cycle_count);

            // Sample hash_out at negedge (Rule 4)
            @(negedge clk);
            `CHECK_HASH_OUT(expected_hash, "empty")

            $display("[TEST] empty string complete");
        end
    endtask

    // ========================================================================
    // Main Test Sequence
    // ========================================================================
    initial begin
        fail_count = 0;

        // ── Initial reset ─────────────────────────────────────────────────
        apply_reset();

        // Verify reset state: ready should be 1 (combinational from IDLE)
        $display("[TRACE] cycle=%0d checking post-reset state", cycle_count);
        `CHECK_PULSE(ready, 1'b1, "reset");
        `CHECK_PULSE(hash_valid, 1'b0, "reset");

        // ── Test 1: abc ──────────────────────────────────────────────────
        test_abc();

        // ── Re-apply reset between tests to ensure clean V registers ─────
        // (Pattern 11 guard: chaining registers must re-initialize to IV)
        apply_reset();

        // ── Test 2: empty string ─────────────────────────────────────────
        test_empty();

        // ── Summary ─────────────────────────────────────────────────────
        $display("============================================================");
        if (fail_count == 0)
            $display("ALL TESTS PASSED");
        else
            $display("FAILED: %0d assertion(s) failed", fail_count);
        $display("============================================================");
        $dumpflush;
        $finish;
    end

endmodule

`default_nettype wire
