"""cocotb integration testbench for sm3_core -- golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (ready, hash_valid, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = 10  # 10ns period (100 MHz), well within 150 MHz target
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0

# --- Golden model import ---------------------------------------------------
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        import golden_model
        from golden_model import run as golden_run, TEST_VECTORS, compute
        GOLDEN_AVAILABLE = True
    except ImportError:
        pass

# --- Port configuration (from spec.json) -----------------------------------
INPUT_PORTS = {
    "msg_valid": 1,
    "msg_block": 512,
    "is_last":   1,
}
OUTPUT_PORTS = {
    "ready":      1,
    "hash_valid": 1,
    "hash_out":  256,
}
VALID_OUTPUT_PORTS = ["hash_valid"]
HANDSHAKE_PORTS = {"msg_valid": "ready"}
HOLD_UNTIL_ACK_PORTS = []

# DRIVE_PHASE_CYCLES from spec.json module_connectivity timing_contract:
#   max pipeline_delay_cycles across all registered control paths = 1
#   (load_en, calc_en, update_v_en all have pipeline_delay_cycles=1)
DRIVE_PHASE_CYCLES = 1

# HOLD_CYCLES: msg_block and is_last must be held stable for
#   max_pipeline_delay + 1 = 2 cycles after msg_valid assertion.
HOLD_CYCLES = 2

MASK32 = 0xFFFFFFFF
MASK256 = (1 << 256) - 1


# --- Clock management ------------------------------------------------------
async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# --- Helpers ---------------------------------------------------------------

async def reset_dut(dut):
    """Apply async-active-low reset and wait for outputs to settle."""
    global FAIL_COUNT
    dut.rst_n.value = 0
    dut.msg_valid.value = 0
    dut.msg_block.value = 0
    dut.is_last.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)
    await RisingEdge(dut.clk)
    dut._log.info("[RESET] rst_n released, DUT in IDLE")


async def drive_block(dut, msg_block_val, is_last_val):
    """Drive a single message block with proper hold time.

    Protocol:
      1. Wait for ready=1
      2. Assert msg_valid, msg_block, is_last simultaneously
      3. Wait 1 RisingEdge (DUT samples handshake)
      4. Deassert msg_valid
      5. Hold msg_block and is_last stable for HOLD_CYCLES total after msg_valid assertion
    """
    # Wait for ready
    for _ in range(TIMEOUT_CYCLES):
        if int(dut.ready.value) == 1:
            break
        await RisingEdge(dut.clk)
    else:
        raise AssertionError("Timeout waiting for ready before drive_block")

    # Drive msg_valid + msg_block + is_last
    dut.msg_block.value = msg_block_val
    dut.msg_valid.value = 1
    dut.is_last.value = is_last_val
    await RisingEdge(dut.clk)  # DUT samples inputs at this posedge

    # Deassert msg_valid but HOLD msg_block and is_last stable
    dut.msg_valid.value = 0
    # Hold data stable for (HOLD_CYCLES - 1) more cycles (already 1 cycle after assertion)
    for _ in range(HOLD_CYCLES - 1):
        await RisingEdge(dut.clk)

    # Now safe to clear data inputs
    dut.msg_block.value = 0
    dut.is_last.value = 0


async def wait_hash_valid(dut, max_cycles=200):
    """Poll for hash_valid=1, return cycle count waited."""
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(dut.hash_valid.value) == 1:
            return i + 1
    return -1  # timeout


def _parse_msg_block(val):
    """Convert msg_block from hex string or int to 512-bit integer."""
    if isinstance(val, str):
        return int(val, 16)
    return val & ((1 << 512) - 1)


# --- Tests -----------------------------------------------------------------

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior -- outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: ready should be 1 (IDLE state), hash_valid=0, hash_out=IV
    ready_val = int(dut.ready.value)
    if ready_val != 1:
        FAIL_COUNT += 1
        dut._log.error(f"[RESET] ready={ready_val} after reset, expected 1")

    hash_valid_val = int(dut.hash_valid.value)
    if hash_valid_val != 0:
        FAIL_COUNT += 1
        dut._log.error(f"[RESET] hash_valid={hash_valid_val} after reset, expected 0")

    if ready_val == 1 and hash_valid_val == 0:
        dut._log.info("[PASS] reset behavior correct: ready=1, hash_valid=0")


@cocotb.test()
async def test_hash_abc(dut):
    """Test 2: SM3('abc') -- GM/T 0004-2012 official test vector.

    Expected: 66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    expected_hash = 0x66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0
    msg_block_hex = (
        "61626380000000000000000000000000"
        "00000000000000000000000000000000"
        "00000000000000000000000000000000"
        "00000000000000000000000000000018"
    )
    msg_block_val = int(msg_block_hex, 16)

    dut._log.info("[TEST_ABC] Driving padded 'abc' block")
    await drive_block(dut, msg_block_val, is_last_val=1)

    # Wait for hash_valid
    cycles_waited = await wait_hash_valid(dut, max_cycles=200)
    assert cycles_waited >= 0, "Timeout waiting for hash_valid on 'abc' test"

    # Read hash_out at the SAME RisingEdge where hash_valid=1
    actual_hash = int(dut.hash_out.value) & MASK256
    dut._log.info(
        f"[TEST_ABC] hash_valid after {cycles_waited} cycles, "
        f"hash_out=0x{actual_hash:064x}"
    )

    if actual_hash != expected_hash:
        FAIL_COUNT += 1
        msg = (
            f"[FAIL] test_hash_abc: hash mismatch\n"
            f"  expected: 0x{expected_hash:064x}\n"
            f"  actual:   0x{actual_hash:064x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(f"[PASS] test_hash_abc: hash_out matches expected")


@cocotb.test()
async def test_hash_empty(dut):
    """Test 3: SM3('') -- empty string test vector.

    Expected: 1ab21d8355cfa17f8e61194831e81a8f22bec8c728fefb747ed035eb5082aa2b
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    expected_hash = 0x1ab21d8355cfa17f8e61194831e81a8f22bec8c728fefb747ed035eb5082aa2b
    msg_block_hex = (
        "80000000000000000000000000000000"
        "00000000000000000000000000000000"
        "00000000000000000000000000000000"
        "00000000000000000000000000000000"
    )
    msg_block_val = int(msg_block_hex, 16)

    dut._log.info("[TEST_EMPTY] Driving padded '' (empty) block")
    await drive_block(dut, msg_block_val, is_last_val=1)

    cycles_waited = await wait_hash_valid(dut, max_cycles=200)
    assert cycles_waited >= 0, "Timeout waiting for hash_valid on empty test"

    actual_hash = int(dut.hash_out.value) & MASK256
    dut._log.info(
        f"[TEST_EMPTY] hash_valid after {cycles_waited} cycles, "
        f"hash_out=0x{actual_hash:064x}"
    )

    if actual_hash != expected_hash:
        FAIL_COUNT += 1
        msg = (
            f"[FAIL] test_hash_empty: hash mismatch\n"
            f"  expected: 0x{expected_hash:064x}\n"
            f"  actual:   0x{actual_hash:064x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(f"[PASS] test_hash_empty: hash_out matches expected")


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal register comparison against golden model.

    This is the KEY verification test. It drives the 'abc' test vector and
    compares DUT internal registers (A~H, V0~V7, w_j, w_prime_j, round_cnt,
    fsm control signals) against the golden model trace on EVERY clock cycle.

    Timing alignment:
      - Golden model trace[0] = T1 (LOAD): register state after load_en NBA.
      - cocotb RisingEdge after drive_block() reads POST-NBA of the drive posedge.
      - DRIVE_PHASE_CYCLES=1 offsets the golden trace to account for the 1-cycle
        registered control signal delay.
      - First compared RisingEdge corresponds to golden trace[0] (T1 LOAD).

    Reports FIRST DIVERGENCE with cycle, signal name, expected vs actual.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden model trace for test vector 0 ("abc")
    expected_cycles = golden_run(test_vector_index=0)
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    dut._log.info(
        f"[INTERNAL] Golden model trace has {len(expected_cycles)} cycles"
    )

    # Drive the "abc" block
    tv = TEST_VECTORS[0]
    msg_block_val = _parse_msg_block(tv["inputs"]["msg_block"])
    await drive_block(dut, msg_block_val, is_last_val=1)

    # Map golden trace signal names to DUT hierarchical paths.
    # The golden model uses flat names; the RTL uses hierarchy under sm3_core.
    GOLDEN_TO_DUT = {
        # FSM control signals (top-level outputs)
        "load_en":     "load_en",
        "calc_en":     "calc_en",
        "update_v_en": "update_v_en",
        "ready":       "ready",
        "hash_valid":  "hash_valid",
        "round_cnt":   "round_cnt",
        # Compression working registers (inside sm3_compress)
        "A": "u_compress.A",
        "B": "u_compress.B",
        "C": "u_compress.C",
        "D": "u_compress.D",
        "E": "u_compress.E",
        "F": "u_compress.F",
        "G": "u_compress.G",
        "H": "u_compress.H",
        # V registers (inside sm3_compress)
        "V0": "u_compress.V0",
        "V1": "u_compress.V1",
        "V2": "u_compress.V2",
        "V3": "u_compress.V3",
        "V4": "u_compress.V4",
        "V5": "u_compress.V5",
        "V6": "u_compress.V6",
        "V7": "u_compress.V7",
        # W-gen outputs
        "w_j":      "u_w_gen.w_j",
        "w_prime_j": "u_w_gen.w_prime_j",
    }

    first_divergence = None
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    # Align: golden trace starts at T1 (LOAD).
    # drive_block consumed HOLD_CYCLES RisingEdges after msg_valid assertion.
    # With DRIVE_PHASE_CYCLES=1, we skip the first entry to align.
    compare_cycles = expected_cycles[DRIVE_PHASE_CYCLES:]

    for cycle_idx, expected in enumerate(compare_cycles):
        await RisingEdge(dut.clk)

        for sig_name, expected_val in expected.items():
            # Skip input signals and intermediate debug signals
            if sig_name in ("fsm_state", "SS1", "SS2", "TT1", "TT2", "hash_out"):
                continue

            dut_path = GOLDEN_TO_DUT.get(sig_name)
            if dut_path is None:
                continue

            try:
                # Navigate VPI hierarchy for dotted paths
                if '.' in dut_path:
                    parts = dut_path.split('.')
                    obj = dut
                    for part in parts:
                        obj = getattr(obj, part)
                    actual_val = int(obj.value)
                else:
                    sig = getattr(dut, dut_path)
                    actual_val = int(sig.value)

                # Mask to appropriate width
                if sig_name == "round_cnt":
                    actual_val &= 0x3F  # 6-bit
                elif sig_name in ("load_en", "calc_en", "update_v_en",
                                  "ready", "hash_valid"):
                    actual_val &= 1
                elif sig_name.startswith("V") or sig_name in (
                    "A", "B", "C", "D", "E", "F", "G", "H",
                    "w_j", "w_prime_j",
                ):
                    actual_val &= MASK32

                signals_compared += 1
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": cycle_idx,
                        "signal": sig_name,
                        "dut_path": dut_path,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        cycles_checked += 1
        if first_divergence:
            break

    # Report signals not found
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (f" ... and {len(signals_not_found)-5} more"
               if len(signals_not_found) > 5 else "")
        )

    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals compared -- golden trace signal names "
            "do not match any DUT signals. Check naming / hierarchy."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, check RTL hierarchy names"
        )

    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']} (path={div['dut_path']}): "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS -- {cycles_checked} cycles, "
            f"{signals_compared} signal values matched golden model"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
