// tb_conv2d_engine.v — Integration testbench for conv2d_engine.
// Generated by VeriFlow-CC (vf-tb-gen).
//
// Tests: 5x5 image with all-ones 3x3 kernel, stride=1, padding=0.
// Expected 3x3 output: 63, 72, 81, 108, 117, 126, 153, 162, 171.
//
// Timing rules (from spec.json timing_convention):
//   DRIVE_PHASE_CYCLES = 2
//   Data inputs must remain stable for DRIVE_PHASE_CYCLES + 1 = 3 cycles
//   after valid pulse deassertion.

`timescale 1ns / 1ps

module tb_conv2d_engine;

    // ─── Parameters ────────────────────────────────────────────────────
    parameter IMG_W = 5;
    parameter IMG_H = 5;
    parameter CLK_PERIOD = 10;  // 100 MHz
    parameter DRIVE_HOLD = 3;   // DRIVE_PHASE_CYCLES + 1 = 3

    // ─── Signals ───────────────────────────────────────────────────────
    reg        clk;
    reg        rst;
    reg        cfg_valid;
    reg  [7:0] cfg_data;
    wire       cfg_ready;
    reg        in_valid;
    wire       in_ready;
    reg  [7:0] in_pixel;
    wire       out_valid;
    reg        out_ready;
    wire [23:0] out_result;

    // ─── Cycle counter ────────────────────────────────────────────────
    integer cycle_count = 0;
    integer fail_count  = 0;
    integer output_count = 0;
    integer hold_counter = 0;

    // ─── Expected results: test_a (5x5, ones kernel, stride=1, pad=0) ─
    // 3x3 output = [[63,72,81],[108,117,126],[153,162,171]]
    parameter NUM_EXPECTED = 9;
    reg signed [23:0] expected_results [0:NUM_EXPECTED-1];
    integer expected_idx = 0;

    // ─── Test image: 1..25 row-major ──────────────────────────────────
    parameter NUM_PIXELS = IMG_W * IMG_H;  // 25
    reg [7:0] test_image [0:NUM_PIXELS-1];

    // ─── Config words: kernel[0..8]=1, stride=1, padding=0 ───────────
    parameter NUM_CONFIG = 11;
    reg [7:0] config_words [0:NUM_CONFIG-1];

    // ─── DUT instantiation ─────────────────────────────────────────────
    conv2d_engine #(
        .IMG_WIDTH (IMG_W),
        .IMG_HEIGHT(IMG_H)
    ) uut (
        .clk       (clk),
        .rst       (rst),
        .cfg_valid (cfg_valid),
        .cfg_data  (cfg_data),
        .cfg_ready (cfg_ready),
        .in_valid  (in_valid),
        .in_ready  (in_ready),
        .in_pixel  (in_pixel),
        .out_valid (out_valid),
        .out_ready (out_ready),
        .out_result(out_result)
    );

    // ─── Clock generation: 100 MHz ─────────────────────────────────────
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // ─── Cycle counter ────────────────────────────────────────────────
    always @(posedge clk) cycle_count <= cycle_count + 1;

    // ─── VCD capture ──────────────────────────────────────────────────
    initial begin
        $dumpfile("tb_conv2d_engine.vcd");
        $dumpvars(0, tb_conv2d_engine);
    end

    // ─── Output capture: check on posedge when out_valid=1 ────────────
    always @(posedge clk) begin
        if (out_valid === 1'b1 && out_ready === 1'b1 && expected_idx < NUM_EXPECTED) begin
            // Read result at posedge (registered output)
            if ($signed(out_result) !== expected_results[expected_idx]) begin
                $display("[FAIL] test=test_a_basic_conv cycle=%0d output[%0d] expected=%0d got=%0d",
                         cycle_count, expected_idx,
                         expected_results[expected_idx], $signed(out_result));
                fail_count = fail_count + 1;
            end else begin
                $display("[PASS] test=test_a_basic_conv cycle=%0d output[%0d] = %0d",
                         cycle_count, expected_idx, $signed(out_result));
            end
            expected_idx = expected_idx + 1;
            output_count = output_count + 1;
        end
    end

    // ─── Data hold task: keep cfg_data / in_pixel stable ──────────────
    // After deasserting valid, hold data inputs for DRIVE_HOLD cycles
    // to ensure the DUT pipeline has captured them.
    task automatic hold_data;
        input [7:0] data_val;
        begin
            hold_counter = 0;
            while (hold_counter < DRIVE_HOLD) begin
                @(posedge clk);
                hold_counter = hold_counter + 1;
            end
        end
    endtask

    // ─── Main test sequence ───────────────────────────────────────────
    initial begin
        // Initialize expected results
        expected_results[0]  = 24'sd63;
        expected_results[1]  = 24'sd72;
        expected_results[2]  = 24'sd81;
        expected_results[3]  = 24'sd108;
        expected_results[4]  = 24'sd117;
        expected_results[5]  = 24'sd126;
        expected_results[6]  = 24'sd153;
        expected_results[7]  = 24'sd162;
        expected_results[8]  = 24'sd171;

        // Initialize test image: 1..25 in row-major order
        test_image[ 0] = 8'd1;   test_image[ 1] = 8'd2;   test_image[ 2] = 8'd3;
        test_image[ 3] = 8'd4;   test_image[ 4] = 8'd5;   test_image[ 5] = 8'd6;
        test_image[ 6] = 8'd7;   test_image[ 7] = 8'd8;   test_image[ 8] = 8'd9;
        test_image[ 9] = 8'd10;  test_image[10] = 8'd11;  test_image[11] = 8'd12;
        test_image[12] = 8'd13;  test_image[13] = 8'd14;  test_image[14] = 8'd15;
        test_image[15] = 8'd16;  test_image[16] = 8'd17;  test_image[17] = 8'd18;
        test_image[18] = 8'd19;  test_image[19] = 8'd20;  test_image[20] = 8'd21;
        test_image[21] = 8'd22;  test_image[22] = 8'd23;  test_image[23] = 8'd24;
        test_image[24] = 8'd25;

        // Initialize config words: kernel[0..8]=1, stride=1, padding=0
        config_words[ 0] = 8'd1;  // kernel[0]
        config_words[ 1] = 8'd1;  // kernel[1]
        config_words[ 2] = 8'd1;  // kernel[2]
        config_words[ 3] = 8'd1;  // kernel[3]
        config_words[ 4] = 8'd1;  // kernel[4]
        config_words[ 5] = 8'd1;  // kernel[5]
        config_words[ 6] = 8'd1;  // kernel[6]
        config_words[ 7] = 8'd1;  // kernel[7]
        config_words[ 8] = 8'd1;  // kernel[8]
        config_words[ 9] = 8'd1;  // stride = 1
        config_words[10] = 8'd0;  // padding = 0

        // Initialize all inputs
        cfg_valid <= 1'b0;
        cfg_data  <= 8'd0;
        in_valid  <= 1'b0;
        in_pixel  <= 8'd0;
        out_ready <= 1'b1;  // Always ready to accept output

        // ─── Phase 1: Reset ───────────────────────────────────────────
        rst = 1;  // blocking OK for reset only
        @(posedge clk); @(posedge clk); @(posedge clk);
        @(posedge clk); @(posedge clk);  // 5 cycles reset
        rst = 0;
        @(negedge clk);  // wait for NBA to settle
        $display("[TRACE] cycle=%0d rst released", cycle_count);

        // Verify post-reset state
        if (cfg_ready !== 1'b1) begin
            $display("[FAIL] test=reset cfg_ready=%b expected=1", cfg_ready);
            fail_count = fail_count + 1;
        end else begin
            $display("[PASS] test=reset cfg_ready=1 (CONFIG state)");
        end
        if (out_valid !== 1'b0) begin
            $display("[FAIL] test=reset out_valid=%b expected=0", out_valid);
            fail_count = fail_count + 1;
        end else begin
            $display("[PASS] test=reset out_valid=0");
        end

        // ─── Phase 2: Config (11 writes) ──────────────────────────────
        begin : config_phase
            integer i;
            for (i = 0; i < NUM_CONFIG; i = i + 1) begin
                // Wait for cfg_ready
                while (cfg_ready !== 1'b1) @(posedge clk);
                // Drive config word
                cfg_data  <= config_words[i];
                cfg_valid <= 1'b1;
                @(posedge clk);
                // Deassert valid, hold data for pipeline
                cfg_valid <= 1'b0;
                hold_data(config_words[i]);
                cfg_data <= 8'd0;
            end
        end
        $display("[TRACE] cycle=%0d config phase complete (11 words)", cycle_count);

        // ─── Phase 3: Stream pixels ───────────────────────────────────
        begin : stream_phase
            integer p;
            for (p = 0; p < NUM_PIXELS; p = p + 1) begin
                // Wait for in_ready (backpressure)
                while (in_ready !== 1'b1) @(posedge clk);
                // Drive pixel
                in_pixel <= test_image[p];
                in_valid <= 1'b1;
                @(posedge clk);
                // Deassert valid, hold data for pipeline
                in_valid <= 1'b0;
                hold_data(test_image[p]);
                in_pixel <= 8'd0;
            end
        end
        $display("[TRACE] cycle=%0d all %0d pixels streamed", cycle_count, NUM_PIXELS);

        // ─── Phase 4: Drain pipeline ──────────────────────────────────
        // Wait for remaining outputs to appear
        repeat (20) @(posedge clk);

        // ─── Phase 5: Check results ───────────────────────────────────
        if (output_count != NUM_EXPECTED) begin
            $display("[FAIL] test=test_a_basic_conv output_count=%0d expected=%0d",
                     output_count, NUM_EXPECTED);
            fail_count = fail_count + 1;
        end

        // ─── Summary ──────────────────────────────────────────────────
        $display("");
        $display("========================================");
        if (fail_count == 0 && output_count == NUM_EXPECTED)
            $display("ALL TESTS PASSED (%0d outputs verified)", output_count);
        else
            $display("FAILED: %0d assertion(s) failed, %0d/%0d outputs received",
                     fail_count, output_count, NUM_EXPECTED);
        $display("========================================");
        $finish;
    end

    // ─── Watchdog timer ───────────────────────────────────────────────
    initial begin
        #100000;  // 100 us timeout
        $display("[ERROR] Simulation timeout at cycle %0d", cycle_count);
        $display("FAILED: simulation timed out before completion");
        $finish;
    end

endmodule
