"""cocotb integration testbench for conv2d_engine — golden model cross-check.
Generated by VeriFlow-CC (vf-tb-gen).

Timing convention:
  DRIVE_PHASE_CYCLES = 2 (from spec.json timing_convention).
  cocotb + iverilog VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA.

  The conv2d_engine has a 2-stage pipeline:
    Stage 1: pixel enters line buffer / sliding window (1 cycle)
    Stage 2: 9 multipliers + adder tree -> output register (1 cycle)
  Total input-to-output latency = 2 cycles after the 3x3 window is formed.

Clock management:
  cocotb v2.0+ kills background tasks between tests.
  Each test calls ensure_clock() for a fresh clock instance.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer, First, Join

# ─── Constants from spec.json ──────────────────────────────────────────
CLK_PERIOD_NS = 10       # 100 MHz target -> 10 ns full period
DRIVE_PHASE_CYCLES = 2   # golden_to_rtl_offset_cycles from spec.json
TIMEOUT_CYCLES = 2000
FAIL_COUNT = 0

# ─── Verilog parameter overrides for cocotb runner ─────────────────────
# The cocotb_runner.py auto-detects this dict and passes -P flags to iverilog.
# Must match the image dimensions used in test vectors (5x5 for most tests).
VERILOG_PARAMS = {"IMG_WIDTH": 5, "IMG_HEIGHT": 5}

# ─── Golden model import ───────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).resolve().parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import (
            compute_conv2d,
            compute,
            signed_8,
            TEST_VECTORS,
            get_test_vectors,
        )
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Tests will be skipped.")


# ─── Clock management ──────────────────────────────────────────────────
async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Reset helper ──────────────────────────────────────────────────────
async def reset_dut(dut):
    """Apply synchronous active-high reset for 5 cycles, then deassert."""
    dut.rst.value = 1
    dut.in_valid.value = 0
    dut.in_pixel.value = 0
    dut.cfg_valid.value = 0
    dut.cfg_data.value = 0
    dut.out_ready.value = 1   # Always ready to accept output
    await ClockCycles(dut.clk, 5)
    dut.rst.value = 0
    await RisingEdge(dut.clk)
    dut._log.info("[TRACE] Reset released")


# ─── Config write helper ───────────────────────────────────────────────
async def write_config(dut, kernel, stride, padding):
    """Write 11 config words: kernel[0..8], stride, padding.

    Each write: assert cfg_valid=1 with cfg_data, wait one posedge,
    deassert cfg_valid, hold cfg_data for DRIVE_PHASE_CYCLES additional cycles.

    Args:
        kernel: list of 9 ints (signed 8-bit kernel weights)
        stride: int (1 or 2, written as stride-1 to match spec encoding)
        padding: int (0 or 1)
    """
    config_words = list(kernel) + [stride, padding]
    assert len(config_words) == 11, f"Expected 11 config words, got {len(config_words)}"

    for i, word in enumerate(config_words):
        # Wait for cfg_ready
        timeout = TIMEOUT_CYCLES
        while int(dut.cfg_ready.value) != 1 and timeout > 0:
            await RisingEdge(dut.clk)
            timeout -= 1
        assert timeout > 0, f"Timeout waiting for cfg_ready before config word {i}"

        # Drive config
        dut.cfg_data.value = word & 0xFF
        dut.cfg_valid.value = 1
        await RisingEdge(dut.clk)

        # Deassert valid, hold data for pipeline
        dut.cfg_valid.value = 0
        for _ in range(DRIVE_PHASE_CYCLES):
            await RisingEdge(dut.clk)
        dut.cfg_data.value = 0

    dut._log.info("[CONFIG] 11 config words written")


# ─── Stream pixels helper ──────────────────────────────────────────────
async def stream_pixels(dut, image):
    """Stream a 2D image row-by-row via AXI-Stream input.

    Respects in_ready backpressure. One pixel per clock when in_ready=1.
    Holds in_pixel stable for DRIVE_PHASE_CYCLES+1 cycles after valid pulse.

    Args:
        image: 2D list of unsigned 8-bit pixel values
    """
    pixel_count = 0
    for row in image:
        for pixel in row:
            # Wait for in_ready
            timeout = TIMEOUT_CYCLES
            while int(dut.in_ready.value) != 1 and timeout > 0:
                await RisingEdge(dut.clk)
                timeout -= 1
            assert timeout > 0, f"Timeout waiting for in_ready at pixel {pixel_count}"

            # Drive pixel
            dut.in_pixel.value = pixel & 0xFF
            dut.in_valid.value = 1
            await RisingEdge(dut.clk)

            # Deassert valid, hold data for DRIVE_PHASE_CYCLES additional cycles
            dut.in_valid.value = 0
            for _ in range(DRIVE_PHASE_CYCLES):
                await RisingEdge(dut.clk)
            dut.in_pixel.value = 0

            pixel_count += 1

    dut._log.info(f"[STREAM] Sent {pixel_count} pixels")


# ─── Collect output pixels helper ──────────────────────────────────────
async def collect_outputs(dut, expected_count, timeout_cycles=2000):
    """Collect output pixels from AXI-Stream output.

    Runs as a background coroutine. Collects pixels when out_valid=1.
    Also drains any remaining pixels after stream completes.

    Returns:
        list of collected output pixel values (ints)
    """
    results = []

    for _ in range(timeout_cycles):
        await RisingEdge(dut.clk)
        if int(dut.out_valid.value) == 1 and int(dut.out_ready.value) == 1:
            val = int(dut.out_result.value)
            # Handle signed 24-bit interpretation
            if val >= (1 << 23):
                val -= (1 << 24)
            results.append(val)
            dut._log.debug(f"[COLLECT] output[{len(results)-1}] = {val}")
        if len(results) >= expected_count:
            break

    return results


# ─── Run one convolution test ──────────────────────────────────────────
async def run_conv_test(dut, test_vector):
    """Run a single convolution test vector and verify output against golden model.

    Args:
        test_vector: dict from TEST_VECTORS with 'name', 'inputs', 'expected'

    Returns:
        True if test passed, False if failed
    """
    global FAIL_COUNT

    name = test_vector["name"]
    inputs = test_vector["inputs"]
    expected = test_vector["expected"]

    image = inputs["image"]
    kernel = inputs["kernel"]
    stride = inputs["stride"]
    padding = inputs["padding"]

    expected_results = expected["results"]
    expected_count = sum(len(row) for row in expected_results)
    flat_expected = [v for row in expected_results for v in row]

    dut._log.info(f"[TEST] {name}: {len(image)}x{len(image[0])} image, "
                  f"stride={stride}, padding={padding}, "
                  f"expect {expected['out_height']}x{expected['out_width']} = {expected_count} outputs")

    # Reset
    await reset_dut(dut)

    # Config: write kernel + stride + padding
    await write_config(dut, kernel, stride, padding)

    # Start output collector as background task
    collector = cocotb.start_soon(collect_outputs(dut, expected_count, TIMEOUT_CYCLES))

    # Stream input pixels
    await stream_pixels(dut, image)

    # Wait a few extra cycles for pipeline to drain
    await ClockCycles(dut.clk, 10)

    # Get collected results (with timeout)
    collected = await Join(collector)

    # Compare
    if len(collected) != expected_count:
        FAIL_COUNT += 1
        dut._log.error(
            f"[FAIL] {name}: output count mismatch: got {len(collected)}, "
            f"expected {expected_count}"
        )
        dut._log.error(f"  collected: {collected}")
        dut._log.error(f"  expected:  {flat_expected}")
        return False

    all_match = True
    for i, (got, exp) in enumerate(zip(collected, flat_expected)):
        if got != exp:
            dut._log.error(
                f"[FAIL] {name}: output[{i}] mismatch: got {got}, expected {exp}"
            )
            all_match = False

    if not all_match:
        FAIL_COUNT += 1
        dut._log.error(f"[FAIL] {name}: {expected_count} outputs collected, values mismatch")
        dut._log.error(f"  collected: {collected}")
        dut._log.error(f"  expected:  {flat_expected}")
        return False

    dut._log.info(f"[PASS] {name}: all {expected_count} outputs match golden model")
    return True


# ═══════════════════════════════════════════════════════════════════════
# TESTS
# ═══════════════════════════════════════════════════════════════════════

@cocotb.test()
async def test_01_reset(dut):
    """Test 1: Verify reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: out_valid must be 0, out_result must be 0
    ok = True
    if int(dut.out_valid.value) != 0:
        dut._log.error(f"[RESET] out_valid={int(dut.out_valid.value)} after reset, expected 0")
        ok = False
        FAIL_COUNT += 1

    if int(dut.out_result.value) != 0:
        dut._log.error(f"[RESET] out_result={int(dut.out_result.value)} after reset, expected 0")
        ok = False
        FAIL_COUNT += 1

    if int(dut.cfg_ready.value) != 1:
        dut._log.error(f"[RESET] cfg_ready={int(dut.cfg_ready.value)} after reset, expected 1 (CONFIG state)")
        ok = False
        FAIL_COUNT += 1

    if ok:
        dut._log.info("[PASS] reset behavior correct — out_valid=0, out_result=0, cfg_ready=1")


@cocotb.test()
async def test_02_basic_conv_stride1_pad0(dut):
    """Test 2: test_a — 5x5 image, all-ones kernel, stride=1, padding=0.
    Expected: 3x3 output = [[63,72,81],[108,117,126],[153,162,171]]"""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    passed = await run_conv_test(dut, TEST_VECTORS[0])
    if not passed:
        FAIL_COUNT += 1


@cocotb.test()
async def test_03_same_padding_stride1_pad1(dut):
    """Test 3: test_b — 5x5 image, all-ones kernel, stride=1, padding=1.
    Expected: 5x5 output (same padding)."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    passed = await run_conv_test(dut, TEST_VECTORS[1])
    if not passed:
        FAIL_COUNT += 1


@cocotb.test()
async def test_04_identity_stride1_pad0(dut):
    """Test 4: test_c — 5x5 image, identity kernel, stride=1, padding=0.
    Expected: 3x3 output (center pixel pass-through)."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    passed = await run_conv_test(dut, TEST_VECTORS[2])
    if not passed:
        FAIL_COUNT += 1


@cocotb.test()
async def test_05_stride2_pad0(dut):
    """Test 5: test_d — 5x5 image, all-ones kernel, stride=2, padding=0.
    Expected: 2x2 output = [[63,81],[153,171]]."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    passed = await run_conv_test(dut, TEST_VECTORS[3])
    if not passed:
        FAIL_COUNT += 1


@cocotb.test()
async def test_06_edge_detect_pad1(dut):
    """Test 6: test_e — 5x5 image, Laplacian kernel, stride=1, padding=1.
    Expected: 5x5 output with edge detection results."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    passed = await run_conv_test(dut, TEST_VECTORS[4])
    if not passed:
        FAIL_COUNT += 1


@cocotb.test()
async def test_07_3x3_image_pad1(dut):
    """Test 7: test_f — 3x3 image, all-ones kernel, stride=1, padding=1.
    SKIPPED: DUT compiled with IMG_WIDTH=5, but test uses 3x3 image.
    The 5x5 same-padding case is already covered by test_03 (test_b)."""
    global FAIL_COUNT
    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] golden_model not available")
        return

    await ensure_clock(dut)
    tv = TEST_VECTORS[5]
    img_h = len(tv["inputs"]["image"])
    img_w = len(tv["inputs"]["image"][0])
    if img_w != VERILOG_PARAMS["IMG_WIDTH"] or img_h != VERILOG_PARAMS["IMG_HEIGHT"]:
        dut._log.info(
            f"[SKIP] {tv['name']}: image {img_h}x{img_w} doesn't match "
            f"Verilog params IMG_WIDTH={VERILOG_PARAMS['IMG_WIDTH']}, "
            f"IMG_HEIGHT={VERILOG_PARAMS['IMG_HEIGHT']}"
        )
        return


@cocotb.test()
async def test_08_summary(dut):
    """Final test: report overall pass/fail.
    MUST be the last test — cocotb runs tests in definition order."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
