// Auto-generated by VeriFlow DSL from module handshake_hold_until_ack
`resetall
`timescale 1ns / 1ps
`default_nettype none

module handshake_hold_until_ack
(
    input  wire         clk,
    input  wire         rst,
    output wire pending,
    output wire valid_reg,
    input  wire req,
    input  wire ack
);

reg [0:0] pending_reg = 1'd0;
reg [0:0] valid_reg_reg = 1'd0;

// Sequential logic (register update)
always @(posedge clk) begin
    if (rst) begin
        pending_reg <= 1'd0;
        valid_reg_reg <= 1'd0;
    end else begin
        pending_reg <= ((req & (~pending_reg)) | (pending_reg & (~(ack & pending_reg))));
        valid_reg_reg <= pending_reg;
    end
end

// Output wire assignments
assign pending = pending_reg;
assign valid_reg = valid_reg_reg;

endmodule

`resetall